### ISSUE TITLE
Style not render properly

### ISSUE THREAD

**Issue by jeffreyho92** [GeekyAnts/NativeBase#599] opened 2017-03-05 15:54 UTC
Almost all element, style not render properly.
Please Help.

```
"dependencies": {
    "native-base": "^2.0.12",
    "react": "15.4.2",
    "react-native": "0.42.0"
 }
```
Tutorial:
![screen shot 2017-03-05 at 11 49 36 pm](https://cloud.githubusercontent.com/assets/5306309/23588863/bcd7d4d0-01fe-11e7-8d63-066d358e6463.png)

Error:
![screen shot 2017-03-05 at 11 49 14 pm](https://cloud.githubusercontent.com/assets/5306309/23588862/bcd0dfd6-01fe-11e7-9c68-14a0798e4ab8.png)

**Comment by shivrajkumar** [comment] 2017-03-06 11:54
@jeffreyho92 Can you share the use-case for this

**Comment by yunlongz** [comment] 2017-03-07 06:37
I have the same problem with you   and the error is Warning: Failed prop type: Invalid prop `style` of type `number` supplied to `Styled(Content)`, expected `object`.

**Comment by tonylinyy** [comment] 2017-03-07 07:04
I have the same problem,when I use 
`var styles=StyleSheet.create({})`
but when I use 
` var styles={} ` 
the warning gone

**Comment by sankhadeeproy007** [comment] 2017-03-09 12:36
StyleSheet.create is not yet supported by NativeBase. This is a duplicate of #510, #525, #527 and #557

**Closed by sankhadeeproy007** 2017-03-09 12:36 UTC

**Comment by andidev** [comment] 2017-03-12 21:40
So this will be supported?
