### ISSUE TITLE
Overwrite theme types with a custom theme definition

### ISSUE THREAD

**Issue by vladi-strilets** [GeekyAnts/NativeBase#4272] opened 2021-11-05 09:55 UTC
Using typescript, I expect to get the suggestions from my custom theme config, But it still returns the default options. For example: 

```
// src/styles/customTheme.ts

const customTheme = extendTheme({
  fontSizes: {
    sm: 14,
    md: 16,
    lg: 20,
    xl: 30,
    custom: 24,
    '123x': 20,
  }
})
```

```
// src/@types/native-base.d.ts

type CustomThemeType = typeof customTheme
declare module 'native-base' {
  interface ICustomTheme extends CustomThemeType {}
}
```

```
// src/App.tsx

<NativeBaseProvider theme={customTheme}>
  ...
</NativeBaseProvider>
```

```
// tsconfig.json

{
  compilerOptions: {
    ...
    "typeRoots": [
      "./src/@types"
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/29280344/140491089-e9760211-5a86-4f77-8932-294538407264.png)

- NativeBase version 3.2.1
- React Native version 0.66.0

Thanks

**Comment by harryhorton** [comment] 2021-11-09 20:30
Running into the same issue.

If you follow their example, your declaration interface extends the custom theme object.

If you remove the extension, and provide a different type (or your own built limited subset type), it'll work as intended.

```typescript
declare module "native-base" {
  interface ICustomTheme {
    space: {
      theresNoOneHereBesideMEeee: string;
    };
  }
}
```

![image](https://user-images.githubusercontent.com/12238902/140999925-0f57fc40-3b96-4826-9235-355ba3a15405.png)

**Comment by rayan1810** [comment] 2021-11-10 10:45
Closing this since the issue has been answered.

**Closed by rayan1810** 2021-11-10 10:45 UTC
Labels: v3
