### ISSUE TITLE
Icon within item causes infinite rendering loop

### ISSUE THREAD

**Issue by TheRusskiy** [GeekyAnts/NativeBase#2871] opened 2019-08-13 06:04 UTC
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Icon within item and input causes infinite rendering loop.
This started happening after upgrade from react-native 0.58.6 to 0.60.4 (and react upgrade that came with it).
Any time I am on a screen with the following code snippet all JS side of RN would freeze.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

native-base: 2.13.4
react-native: 0.60.4
react: 16.8.6
no expo

### Expected behaviour

Render input with an icon without freezing the UI.

### Actual behaviour

Rendering input with an icon freezes the UI.

### Steps to reproduce

```
import { Input, Item, Icon, Label } from 'native-base'
// ...
<Item>
  <Label>Some Label</Label>
  <Input
    placeholder={placeholder}
    value={value}
    onChangeText={onChange}
  />
  <Icon name='close-circle' />
</Item>
```

### Is the bug present in both iOS and Android or in any one of them?

Happened on iOS, but I haven't checked it on Android yet.

### Any other additional info which would help us debug the issue quicker.

It was hard to boil it down why interface became unresponsive, but I narrowed it down to removing the icon.
Checking stacktraces (had to pause execution) show that it's happening somewhere in the floating label I think.

**Comment by sankhadeeproy007** [comment] 2019-08-13 06:17
@TheRusskiy Thanks for the detailed report. Will take a look.

**Comment by PlabanJr** [comment] 2019-08-13 12:00
Hello @TheRusskiy! This seems to be a duplicate of #2831. A solution for the same was pushed and will be available in the next release.

**Comment by TheRusskiy** [comment] 2019-08-13 12:17
Oh, I didn't see that issue. Thank you then!

**Comment by PlabanJr** [comment] 2019-08-13 12:19
Please wait till the next release 😊

**Closed by PlabanJr** 2019-08-13 12:19 UTC
