### ISSUE TITLE
FAB Button cannot be styled

### ISSUE THREAD

**Issue by Maxeh** [GeekyAnts/NativeBase#1201] opened 2017-08-30 15:11 UTC
```
<Fab
  style={{backgroundColor:'green'}}
>
  <Icon name="add" />
</Fab>
```

## react-native, react and native-base version
2.3.0 and 2.3.1
## Expected behaviour

FAB button should be styled for example with the background "green"
## Actual behaviour

Styles are not applied to the FAB button; it is just blue.

## Steps to reproduce
Use FAB Button with style.

In Native Base 2.2.1 everything is working fine.

**Comment by HackedBeat** [comment] 2017-09-18 08:42
This issue is a duplicate of #1132

**Closed** 2017-10-11 13:22 UTC
Labels: Android, bug, high priority
