### ISSUE TITLE
NextJS integration?

### ISSUE THREAD

**Issue by stan-sack** [GeekyAnts/NativeBase#2709] opened 2019-05-28 05:45 UTC
Apologies as this isn't strictly a bug but has anyone been able to use this in a nextjs app? I've been following the documentation [here]( https://docs.nativebase.io/docs/GetStarted.html#Setup_with_Web) and I am attempting to override the webpack settings by setting `next.config.js` as follows:
```
const path = require("path");

module.exports = {
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.resolve.alias = {
            ...(config.resolve.alias || {}),
            "react-native": "react-native-web",
            "react-native/Libraries/Renderer/shims/ReactNativePropRegistry":
                "react-native-web/dist/modules/ReactNativePropRegistry"
        };

        config.module.rules.unshift({
            test: /\.(js|mjs|jsx)$/,
            use: [
                {
                    loader: defaultLoaders.babel.loader,
                    options: {
                        ...defaultLoaders.babel.options,
                        plugins: [
                          "@babel/plugin-proposal-class-properties",
                          "@babel/plugin-transform-flow-comments"
                        ]
                    }
                }
            ],
            include: [
                path.resolve("node_modules/native-base-shoutem-theme"),
                path.resolve("node_modules/react-navigation"),
                path.resolve("node_modules/react-native-easy-grid"),
                path.resolve("node_modules/react-native-drawer"),
                path.resolve("node_modules/react-native-safe-area-view"),
                path.resolve("node_modules/react-native-vector-icons"),
                path.resolve("node_modules/react-native-keyboard-aware-scroll-view"),
                path.resolve("node_modules/react-native-web"),
                path.resolve("node_modules/react-native-tab-view"),
                path.resolve("node_modules/static-container")
            ]
        });

        return config;
    }
};
```

But I am getting the error:
```
<BASE_DIR>/node_modules/native-base-shoutem-theme/index.js:1
import connectStyle from "./src/connectStyle";
       ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
```

If anyone has been able to do this or has any idea on how to fix this error I'd really appreciate the help.

**Comment by mehmetnyarar** [comment] 2019-06-26 19:11
I couldn’t get it to work neither. I’m trying to do things in a monorepo, which makes it complicated I guess.

**Comment by Arlen22** [comment] 2019-12-16 21:07
It's a total shot in the dark, but https://github.com/martpie/next-transpile-modules might be an idea.

**Comment by stan-sack** [comment] 2019-12-17 00:31
I just changed to semantic UI. There are too many other good UI frameworks out there to waste time on this

**Comment by Arlen22** [comment] 2019-12-17 15:55
Also, the Expo docs talk about this here: https://docs.expo.io/versions/latest/guides/using-nextjs/#font-support

**Comment by velidan** [comment] 2020-04-24 19:28
The same stuff here
```
<BASE_DIR>/node_modules/native-base-shoutem-theme/index.js:1
import connectStyle from "./src/connectStyle";
       ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
```

I can't just understand why guys are publishing stuff in non common.js format. There are tons of problems regarding this thing.

**Comment by Arlen22** [comment] 2020-04-24 19:38
>I can't just understand why guys are publishing stuff in non common.js format. There are tons of problems regarding this thing.

It's actually perfectly normal to publish code that get's compiled using Babel. The problem is there are so many variations and confusing and frustrating frameworks that nothing really works properly. Currently I've given up on react native web because it was way too much frustration and hackiness and I spent most of my work time trying to get it working. I did get it working, but not with native base. I really don't know what the problem is with all of this but it is very crippling when I'm running against deadlines.

**Comment by velidan** [comment] 2020-04-24 20:55
@Arlen22  if it's perfectly normal and totally fine to publish the non-compiled code why people are struggling with all of these? 
The only problem in the case of native-base that it has a lot of its own dependencies in ES6 format. 
In the case of Next.js we can't just configure babel to properly compile it because it by default ignores node_modules.

People are getting to do some ugly modules that allow you to transpile particular modules, some crazy bundling stuff, etc.

The things are going to be even harder when we have an ES6 dep which has its own ES6 dep 

https://stackoverflow.com/questions/61407643/transpile-es6-nested-node-modules-dependency-of-the-top-level-node-modules-depen/61414796#61414796

Why can't we just publish in Common.js and make people live a bit easier?
The frontend is a horrible part even without these issues. Tons of variations of babel config, webpack config, loaders, typescript, shims, crazy dancing with tons of frameworks, etc.

**Comment by stan-sack** [comment] 2020-04-24 21:36
12 months after initially starting to deal with this - my advice would be to just do your own styling and vendor individual component packages only when necessary. It will save you a lot of pain. These UI kits are great until something doesn't work and then you will waste all the time you initially saved trying to fix extremely difficult problems. Also, most of them are extremely difficult to setup and have a very heavy initial download. There is almost no benefit.

**Comment by stan-sack** [comment] 2020-12-21 20:13
Still doesn't work

**Comment by redbar0n** [comment] 2021-07-04 15:47
Isn't it supposed to work with NextJS?

Re, the docs: https://docs.nativebase.io/install-next

**Comment by sanketsahu** [comment] 2021-07-04 17:18
NativeBase 3.x works very well with Next. Please check the docs: https://docs.nativebase.io/installation

Closing this issues as the support has been added.

**Closed by sanketsahu** 2021-07-04 17:18 UTC
