### ISSUE TITLE
Header and Footer on iPhone XR and XS Max wrong SafeArea

### ISSUE THREAD

**Issue by benzman81** [GeekyAnts/NativeBase#2291] opened 2018-09-21 14:23 UTC
## Issue Description
Header and Footer currently do not work on iPhone XR and XS Max as the SafeArea does seem to be wrong. iPhone X and XS works well.

### node, npm, react-native, react and native-base version, expo version if used
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 25.59 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-app-id: 0.0.5
      react-native-cli: 2.0.1

"native-base": "^2.8.0",

### Expected behaviour
Should respect correct SafeArea and display nicely.

### Actual behaviour
Header and Footer are within SafeArea.

### Steps to reproduce
- react-native init my app
- install nativebase
- add header and footer to app.js
- start with iPhone XR or XS Max

### Is the bug present in both iOS and Android or in any one of them?
iOS only issue

### Any other additional info which would help us debug the issue quicker.
maybe #2283 fixes it, so it should be merged and a release should be pushed to fix this.

**Comment by msnow345** [comment] 2018-09-27 10:32
Any update on this? Still seems broken.

I can put together a PR to fix this if the one above doesn't but I'm not sure how quickly they're being merged.

**Comment by jorgebaralt** [comment] 2018-09-30 02:42
I am also experiencing this issue on Iphone XS Max, but only with the header. seems like the height is wrong for this device. Tested both on emulator and real device.
<img width="445" alt="header iphone xs max" src="https://user-images.githubusercontent.com/14077430/46252608-eb518100-c438-11e8-9869-1381a479e9a5.png">

**Comment by ducpt2** [comment] 2018-10-01 08:40
+1 i facing same issue, when iphoneX safearea is work.

**Comment by hohien** [comment] 2018-10-04 07:42
so what is solution to resolve now?

**Comment by kimkong88** [comment] 2018-10-05 07:36
any solution yet?

**Comment by alexisbronchart** [comment] 2018-10-10 07:13
See my comment https://github.com/GeekyAnts/NativeBase/pull/2283#issuecomment-428102438 it's quite easy to fix by yourself if you can't wait for the PR to be merged.

**Comment by jorgebaralt** [comment] 2018-10-15 01:41
@alexisbronchart when I add the changes on #2283 to my code (in node_modules and native base) for some reason it still does not work

**Comment by jorgebaralt** [comment] 2018-10-15 12:59
this is how my package.json looks:

**Comment by jorgebaralt** [comment] 2018-10-15 13:00
@alexisbronchart  thanks for answering, 
This is how my package.json looks right now: 

`{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^28.0.1",
    "firebase": "^5.5.1",
    "jshint": "^2.9.5",
    "lodash": "^4.17.11",
    "native-base": "^2.8.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
    "react-native-linear-gradient": "^2.4.2",
    "react-native-ratings": "https://github.com/jorgebaralt/react-native-ratings",
    "react-navigation": "^2.17.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "ws": "^3.3.1"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.6",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1"
  }
}
`

**Comment by ducpt2** [comment] 2018-10-22 09:56
@alexisbronchart  follow your guild it working now :) Thanks alot.

**Comment by youssefmeskini** [comment] 2018-11-08 10:20
> @jorgebaralt since this is a direct change in node_modules, did you change the `main` property in `package.json` to `src/index.js` to avoid using the transpiled code?

Hi could you explain me what is the action to do because I didn't get it and what happen in production ?

**Comment by egold** [comment] 2018-11-19 23:41
Here's what I did to workaround this issue until the maintainers fix this.

1. Made a component called `CommonHeader` that wraps the native base `Header`
2. Added `react-native-device-info` package
3. Added a helper function to see if the current device is one that happens to work correctly on native-base (2.8.1 as of this comment)
4. Made the following helper function:

```
  nativeBaseDoesHeightCorrectlyAlready() {
    if (!DeviceInfo.hasNotch()) {
      return true
    }
    const model = DeviceInfo.getModel()
    switch (model) {
      case "iPhone X":
      case "iPhone XS":
        return true
    }
    return false
  }
```

5. Added a style function to add padding to top if it's one of the devices for which native-base 💩the 🛏 

```
  getContainerStyles() {
    const defaultStyles = {
      backgroundColor: "#ffffff",
    }
    if (!this.nativeBaseDoesHeightCorrectlyAlready()) {
      return {
        ...defaultStyles,
        paddingTop: 40,
        height: 100,
      }
    }
    return defaultStyles
  }
```

There's probably all sorts of issues with this, and devices this doesn't quite work on, but this is a temporary workaround for these specific devices (iPhone XR, XS Max)

Hopefully this works well for others. Works for my needs for now, but looking forward to a real fix!

**Comment by daemoncahill-qb** [comment] 2018-11-30 21:14
Any updates on when a fix for this is triaged for?

**Comment by SupriyaKalghatgi** [comment] 2018-12-20 07:55
Released 2.9.2

**Closed by SupriyaKalghatgi** 2018-12-20 07:55 UTC
Labels: theme

**Comment by benzman81** [comment] 2018-12-20 14:03
@SupriyaKalghatgi working now, thanks

**Comment by lebreRafael** [comment] 2019-07-02 15:05
It seems that this problem is back.

native-base@2.8.0
<img width="353" alt="Screen Shot 2019-07-02 at 11 42 09" src="https://user-images.githubusercontent.com/13899924/60523434-15ceb400-9cc1-11e9-9761-85f9c8046445.png">

native-base@2.9.2
<img width="346" alt="Screen Shot 2019-07-02 at 12 00 28" src="https://user-images.githubusercontent.com/13899924/60523477-2bdc7480-9cc1-11e9-8279-c86ea37bcb51.png">

native-base@2.12.1
<img width="353" alt="Screen Shot 2019-07-02 at 11 42 09" src="https://user-images.githubusercontent.com/13899924/60523434-15ceb400-9cc1-11e9-9761-85f9c8046445.png">

Device: Iphone XS Max

**Comment by Hraph** [comment] 2019-07-06 16:18
> It seems that this problem is back.
> 
> native-base@2.8.0
> <img alt="Screen Shot 2019-07-02 at 11 42 09" width="353" src="https://user-images.githubusercontent.com/13899924/60523434-15ceb400-9cc1-11e9-9761-85f9c8046445.png">
> 
> native-base@2.9.2
> <img alt="Screen Shot 2019-07-02 at 12 00 28" width="346" src="https://user-images.githubusercontent.com/13899924/60523477-2bdc7480-9cc1-11e9-8279-c86ea37bcb51.png">
> 
> native-base@2.12.1
> <img alt="Screen Shot 2019-07-02 at 11 42 09" width="353" src="https://user-images.githubusercontent.com/13899924/60523434-15ceb400-9cc1-11e9-9761-85f9c8046445.png">
> 
> Device: Iphone XS Max

Facing same problem. It appeared between version 2.11.0 and 2.12.0.

**Comment by andrewhamill** [comment] 2019-07-06 19:10
Reproduced the problem as well on the versions stated above. Reverted to 2.11.0 for now as 2.12.1 has the issue.

**Comment by ansarikhurshid786** [comment] 2019-07-08 06:07
I am also facing misalignment of header issue in iphone x

**Comment by RobertSasak** [comment] 2019-07-08 13:42
@lebreRafael @Hraph @andrewhamill 
I faced similar issue and then I realise that perhaps I need to eject and update theme. It seems like that there was some refactoring done in last versions.
```sh
node node_modules/native-base/ejectTheme.js
```

**Comment by lebreRafael** [comment] 2019-07-08 13:47
@RobertSasak Thank's for sharing that! I will try it soon and tell here if it worked.

**Comment by lebreRafael** [comment] 2019-07-10 20:49
It worked!

**Comment by hossamnasser938** [comment] 2020-01-18 13:51
I'm experiencing a similar issue with the footer. On iPhone Xr, it is pushed above a little bit while it works on iPhone 8.
![Uploading Screen Shot 2020-01-18 at 3.48.46 PM.png…]()

**Comment by hossamnasser938** [comment] 2020-01-18 14:01
I'm experiencing a similar issue with the footer. On iPhone Xr, it is pushed above a little bit while it works on iPhone 8.
![Screen Shot 2020-01-18 at 3 48 46 PM](https://user-images.githubusercontent.com/27894818/72664763-69f57780-3a0a-11ea-9d5b-62dd548adcd9.png)

**Comment by michaelVictoriaDev** [comment] 2020-03-04 01:29
I have the same issue in iphone x and up

I have the screenshot in iphone 6 plus - react-native-modal for pop up
![image](https://user-images.githubusercontent.com/44763288/75834747-e7791980-5df7-11ea-9615-6383a80ed2be.png)



My code looks like this 

```
<Modal isVisible={this.state.isModalVisible} backdropColor={'rgba(0,0,0,.4)'} backdropOpacity={1} animationIn={'zoomInDown'} animationOut={'zoomOutUp'}
        animationInTiming={1000} animationOutTiming={1000} backdropTransitionInTiming={1000} backdropTransitionOutTiming={1000}
        onBackdropPress={() => {
          this.closeModal();
        }}
        onRequestClose={() => {
          this.closeModal();
        }}
        style={{ justifyContent: 'center', zIndex: 2 }} >
        <Content  >

          {/* End of Header Modal */}
          <View style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 10, backgroundColor: '#3F71D7',paddingHorizontal: 20 }}>
            <View style={{ alignSelf: 'flex-start'}}>
             <Text style={{ fontSize: pRatioToFontSize() > 20 ? 20 : pRatioToFontSize(), color: 'white' }}>
              Filter Leads
						</Text>

            </View>
           
            <Button transparent style={{ position: 'absolute', right: 0, marginRight: 20, }}
              onPress={() => {
                this.setState({ showFilterHeader: false }, () => {
                  this.closeModal();
                });
              }}>
              <Ionicons name='md-close' size={25} color='white' />
            </Button>
      
          </View>

          <Content style={{ backgroundColor: colors.WHITE, paddingHorizontal: 20 }} >
              <Text style={{ fontSize: 14, paddingTop: 6 }}>Filter By</Text>
              <Row>
                <Col size={50}>
                <ListItem style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                  <CheckBox checked={this.state.checkBoxLeadStatus} onPress={(e) => this.checkBoxLeadStatus()} />
                  <Body>
                    <Text style={{ fontSize: 14 }}>Lead Status</Text>
                  </Body>
                </ListItem>
                <ListItem style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                  <CheckBox checked={this.state.checkBoxLeadSource} onPress={(e) => this.checkBoxLeadSource()} />
                  <Body>
                    <Text style={{ fontSize: 14 }}>Lead Source</Text>
                  </Body>
                </ListItem>
                <ListItem style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                  <CheckBox checked={this.state.checkBoxChooseDate} onPress={(e) => this.checkBoxChooseDate()} />
                  <Body>
                    <Text style={{ fontSize: 14 }}>Choose Date</Text>
                  </Body>
                </ListItem>
                </Col>
                
              <Col size={50}>
                <ListItem style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                  <CheckBox checked={this.state.checkBoxRating} onPress={(e) => this.checkBoxRating()} />
                  <Body>
                    <Text style={{ fontSize: 14 }}>Rating</Text>
                  </Body>
                </ListItem>
                <ListItem style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                  <CheckBox checked={this.state.checkBoxPriority} onPress={(e) => this.checkBoxPriority()} />
                  <Body>
                    <Text style={{ fontSize: 14 }}>Priority</Text>
                  </Body>
                </ListItem>
                <ListItem style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                  <CheckBox checked={this.state.checkBoxTags} onPress={(e) => this.checkBoxTags()} />
                  <Body>
                    <Text style={{ fontSize: 14 }}>Tags</Text>
                  </Body>
                </ListItem>
              </Col>

              </Row>
            <View >
              <ListItem icon style={{ marginLeft: 0, borderBottomWidth: 0 }}>
                <Left>
                  <Text>Include Shared Leads</Text>
                </Left>
                <Body style={{ borderBottomWidth: 0}} />
                <Right style={{ borderBottomWidth: 0 }}>
                  <Switch value={this.state.sharedLead} onValueChange={() => this.setState({ sharedLead: !this.state.sharedLead})} />
                </Right>
              </ListItem>
            </View>
          </Content>
          <Footer >
            <FooterTab style={{ backgroundColor: "#FFF"}}>
              <Button light full
                onPress={() => {
                    console.log(Clear All)
                }}>
                <Text >
                  Clear All
								</Text>
              </Button>
              <Button full
                style={{ backgroundColor: '#2ca84f', borderRadius: 0}}
                onPress={() => {
                  console.log(apply)
                }}>
                <Text style={{ color: 'white' }}>
                  Apply
								</Text>
              </Button>
            </FooterTab>
          </Footer>
        </Content>
      </Modal>;
```

But in iphone x  and up the footer height is not responsive or there's a big gap on the buttons
I hope someone help me on this sort of problem.
![image](https://user-images.githubusercontent.com/44763288/75835711-90c10f00-5dfa-11ea-95b2-c7c3c94130eb.png)
