### ISSUE TITLE
Doen not work onChangeText for input

### ISSUE THREAD

**Issue by mounlion** [GeekyAnts/NativeBase#490] opened 2017-02-09 08:59 UTC
When i pass floatingLabel function onChangeText doen work

`<Item floatingLabel>
                            <Label>Password</Label>
                            <Input
                                style={{height: 40}}
                                onChangeText={(login) => AlertIOS.alert(
                                    login,
                                    'All your data are belong to us.'
                                )}
                            />
                        </Item>`

**Comment by sankhadeeproy007** [comment] 2017-02-09 09:09
Duplicate of #483

**Closed by sankhadeeproy007** 2017-02-09 09:09 UTC
