### ISSUE TITLE
Cannot open page with Item Component on the new version

### ISSUE THREAD

**Issue by ryantando** [GeekyAnts/NativeBase#2790] opened 2019-07-20 19:23 UTC
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []x   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I just updated to native-base 2.12.2 and when I navigate (by the way I'm using react-navigation) to the page that has 'Item' component it refused to render. When I delete the Item component I could render the page so I decided to downgrade to 2.12.1. I haven't investigated what causes it.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 11.3.0
npm: 6.4.1
react native: 0.59.4
react: 16.6.3
native-base 2.12.2

### Expected behaviour
Could access the page that has 'Item' component

### Actual behaviour
with react-navigation, it refuses to render

### Steps to reproduce
Navigate to the page that has 'Item' component in it with native base version 2.12.2

### Is the bug present in both iOS and Android or in any one of them?
Tested on Android

**Comment by ViktorAksionov** [comment] 2019-07-21 06:41
I have the same issue with `Item`. Item component is broken. Please fix.

![image](https://user-images.githubusercontent.com/2520890/61587913-d371f780-ab47-11e9-9111-5c54943bbfe2.png)

**Comment by sankhadeeproy007** [comment] 2019-07-22 06:34
@ryantando @ViktorAksionov can you please check and let me know if it is a duplicate of #2786 ?
If it is, the fix for it will be merged to master in a while. If not, please provide more details.

**Comment by sankhadeeproy007** [comment] 2019-07-24 12:41
Fixed in 2.13.0

**Closed by sankhadeeproy007** 2019-07-24 12:41 UTC
Labels: duplicate
