### ISSUE TITLE
Native base not working with este?

### ISSUE THREAD

**Issue by Anima-t3d** [GeekyAnts/NativeBase#678] opened 2017-03-23 10:28 UTC
## react-native, react and native-base version
```
"native-base": "^2.0.13",
"react": "^15.4.1",
"react-native": "^0.42.0",
```
## Expected behaviour
Code using native-base components to render when used inside [este](https://github.com/este/este)
## Actual behaviour
Red error screen on both iOS and Android.
Error on iOS: `theme.createComponentStyle is not a function. (In 'theme.createComponentStyle(componentStyleName, componentStyle)', 'theme.createComponentStyle' is undefined`
Error on Android: `undefined is not a function (evaluating 'theme.createComponentStyle(componentStyleName, componentStyle)')`
## Steps to reproduce (code snippet or screenshot)
1. Download and run [este](https://github.com/este/este)
1. Add `native-base`
1. Use any native-base component (e.g. Text, Picker, Title, ...)
1. Run `gulp ios` or `gulp android`
1. Go to the page with the implemented code
1. Observe red error screen

## Is the bug present in both ios and android or in any one of them?
Both
## Any other additional info which would help us debug the issue quicker.
Perhaps a conflict with [fela](https://github.com/rofrischmann/fela)?

**Comment by Justin-Palmer** [comment] 2017-10-13 15:47
I'm also getting the same error, and I'm using fela.js in my project as well.

**Comment by wcastand** [comment] 2017-11-24 09:44
Hi, we're having the same problem right now and it's related to fela.
The problem is the ThemeProvider of fela use the context with a theme key, same as Native-base.

Neither Native-base or fela provide us with a way to change the name of this key.

The simplest solution right now seems to scope the key in context with something like `native_base_theme`

**Comment by wcastand** [comment] 2017-11-24 13:23
Fixed in the last version of fela. Fela changed his keyName to a scoped one. Should resolve the issues with native-base;

https://github.com/rofrischmann/fela/pull/475

**Comment by sanketsahusoft** [comment] 2017-12-19 05:33
It's been fixed. The conflict can be resolved by overriding _FELA_THEME_. There was a conflict between the two using the same key.

**Closed by sanketsahusoft** 2017-12-19 05:33 UTC
Labels: low priority
