### ISSUE TITLE
Startup issues reported on Discord, not solved for a month

### ISSUE THREAD

**Issue by mmfire118** [GeekyAnts/NativeBase#4930] opened 2022-04-14 11:10 UTC
### Description

Multiple Problems with NativeBase and Startup+

### Steps to reproduce

I have been using Startup+ for a while now. My app is 80% done. I have reported several critical issues for launch a while back on Discord, email, and other channels. 

- Startup+ Screens don't scroll on Android, no interaction is possible.
- Startup+ Project Updated to 3.4, Select is Broken
- Mixing Select and Input in Form causes unexpected scrolling for user
- While using Input, sometimes it scrolls to the wrong place, covering the Input
- On iOS, if you have many screens in a navigator, the app flickers between light and dark mode when you re-enter the app

I have already created a GitHub project for the team to reproduce my issues: [https://github.com/mmfire118/example-app.git](https://github.com/mmfire118/example-app.git) and I have not received a reply in a while.

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by mmfire118** [comment] 2022-04-14 11:25
Here are a few of the many videos I have shared on Discord: [https://drive.google.com/drive/folders/1rrRTOBft8c6v3yGp2nyTSuPdy4kCdAYL?usp=sharing](https://drive.google.com/drive/folders/1rrRTOBft8c6v3yGp2nyTSuPdy4kCdAYL?usp=sharing)

**Comment by mmfire118** [comment] 2022-04-14 11:35
Here are a few of the links that I have shared that seem related to my issues: 

- [](https://github.com/facebook/react-native/issues/28525)
- [](https://github.com/expo/expo/issues/10815#issuecomment-719116736)
- [](https://github.com/expo/expo/issues/10815#issuecomment-719113200)

The scrolling in mixed forms issue is the most critical. There seems to be two main issues. One is occasionally covering inputs. The other is scrolling up when trying to use a Select from an Input. If you are clicked into an input, and scroll down without focusing out of the input, when you tap on what you think is a select, the keyboard closes and you scroll all the way back up. This is annoying. It would be great if there was a way to persist taps without scrolling back to the original position if the user clicks a select. It would make the experience much better. The only solution I see at the moment is to separate selects and inputs onto different pages which is unacceptable. 

It would be amazing if you could provide an example of a working mixed form.

Startup+ Screens not working on Android is also very strange. It would be great if you could provide an example that works on Android.

**Comment by gauravguha** [comment] 2022-04-14 12:42
Hello @mmfire118! Sorry for the inconvenience. We are looking into these issues as a top priority. Thanks for sharing the Github repo. This will help us debug. Rest assured we will make your app work :)

**Comment by Abhineetk47** [comment] 2022-04-22 11:10
Hello @mmfire118, thanks for reporting issues, Please upgrade your NB version to 3.4.3

**Comment by Abhineetk47** [comment] 2022-04-26 11:45
@mmfire118 upgrading the Native Base library version to 3.4.3 in Startup+ project will fix the 
1. Broken Select component
2. Scrolling issue on android ..screens will start interacting on android device 
3. Flickering issue reported on ios after re-entering the app 
4. scrolling issue causing covering of input box is mainly due to inappropriate placement of KeyboardAwareScrollView component in this repo( https://github.com/mmfire118/example-app.git )
moving the KeyboardAwareScrollView component to the parent level(topmost level) of the screen will fix this issue

**Comment by mmfire118** [comment] 2022-04-26 13:11
Upgrading to 3.4.3 fixes:

1. Broken Select component
2. Scrolling issue on android ..screens will start interacting on android device

It does not fix:

1. Flickering issue reported on ios after re-entering the app
2. scrolling issue causing covering of input box is mainly due to inappropriate placement of KeyboardAwareScrollView component in this repo( https://github.com/mmfire118/example-app.git )
moving the KeyboardAwareScrollView component to the parent level(topmost level) of the screen will fix this issue

**Comment by Abhineetk47** [comment] 2022-06-09 11:00
Hi @mmfire118 
1. For Flickering issue reported on ios after re-entering the app, Instead of Using useSystemColorMode you can do following work around.
import { Appearance } from "react-native";
const colorScheme = Appearance.getColorScheme();
const theme = extendTheme({
  config: {
    initialColorMode: colorScheme,
  },
  colors: {
    primary: nbTheme.colors.blue,
  },
});
2. And was not able to reproduce the scrolling issue caused by mixing Select and Input components in the same form

**Comment by Viraj-10** [comment] 2022-08-04 07:06
This Issue has been resolved in `v3.4.11`

**Closed by Viraj-10** 2022-08-04 07:06 UTC
Labels: bug, v3, triage
