### ISSUE TITLE
Disable scrolling in Modal body

### ISSUE THREAD

**Issue by dillondrobena** [GeekyAnts/NativeBase#3984] opened 2021-08-22 21:15 UTC
Haven't found an answer for this anywhere so I thought I'd ask the question here. The default modal body component seems to be a `ScrollView` or something similar, but doesn't seem to provide a `scrollEnabled` property. Is there a way to disable the scrollable behavior?

Simple code example
```
    <Modal isOpen={true}>
          <Modal.Content>
              <Modal.CloseButton/>
              <Modal.Header >Modal Title</Modal.Header>
              <Modal.Body >
                  Sit nulla est ex deserunt exercitation anim occaecat.
              </Modal.Body>
              <Modal.Footer >
                  <Button.Group variant="ghost" space={2}>
                      <Button>LEARN MORE</Button>
                      <Button>Accept</Button>
                  </Button.Group>
              </Modal.Footer>
          </Modal.Content>
      </Modal>
```

This is using NativeBase 3.1.0 with ReactNative 0.63.3 on iOS

**Comment by rayan1810** [comment] 2021-08-24 08:02
Thanks for Reporting this @dillondrobena, it will be fixed in the next Patch release.

**Comment by amosbastian** [comment] 2021-10-15 09:07
@rayan1810 it's not fixed yet.

**Comment by rayan1810** [comment] 2021-10-18 11:14
Once this PR https://github.com/GeekyAnts/NativeBase/pull/4215 gets merged and released, you can pass _scrollview to Modal.Body and it takes ScrollView props so you have full control over the underlying ScrollView. 
eg - <Modal.Body _scrollview={{ scrollEnable: false }}>

**Comment by yamatsum** [comment] 2021-11-13 13:23
Correctly is `scrollEnabled: false`

**Comment by rayan1810** [comment] 2021-11-13 14:31
My bad typo 🙈, thanks for correcting it @yamatsum

**Comment by surajahmed** [comment] 2022-01-17 13:08
This issue has been fixed in version `3.2.2` or later.

**Closed by surajahmed** 2022-01-17 13:08 UTC
Labels: v3

**Comment by scipilot** [comment] 2022-05-13 15:22
Is it possible to effectively remove the ScrollView? 

When there's a virtualised list in the modal body content I get this error: `"VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. "` (as the virtualised list does its own scrolling while managing the list item construction and destruction off screen). 

I previously have solved this by removing the enclosing ScrollView - but in this case setting `scrollEnabled: false` doesn't resolve the error, even though it does affect the scroll behaviour.

**Comment by saurabhghadi0401** [comment] 2022-07-07 10:09
Yes, the issue is still there with Modal Body.

**Comment by erclem1998** [comment] 2022-11-02 22:16
Does anyone know if the problem will be fixed?

**Comment by amanape** [comment] 2023-02-07 14:46
Removing the inner `<Modal.Body>` works as a temporary solution.

**Comment by JavaScriptJohn** [comment] 2023-05-04 14:52
Still causing me issues.

**Comment by Christopher-Marim** [comment] 2023-07-13 03:49
Change ```<Modal.Body>``` for ```<VStack p={4}```

**Comment by sangayt1997** [comment] 2023-11-09 08:03
It's still in `"native-base": "^3.4.28"` but `_scrollview={{scrollEnabled: false}}` work well
