### ISSUE TITLE
Avatar Source uri: must be a string.

### ISSUE THREAD

**Issue by Vercjames** [GeekyAnts/NativeBase#4673] opened 2022-02-25 00:15 UTC
### Description

Avatar component breaks stack

### CodeSandbox/Snack link

n/a

### Steps to reproduce

1: make an Avatar component
2: pass in a dynamic variable to the source uri
3: make that variable undefined 

### NativeBase Version

3.3.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

When using a dynamic variables in the <Avatar> component like so: 

`
<Avatar source={{ uri: UserModel?.profilePictureURI }}>
  <Text>AK</Text>
</Avatar>
`

The app stack breaks. Introducing other conditionals into the source like so:

`
<Avatar source={{ uri: UserModel?.profilePictureURI || null }}>
<Avatar source={{ uri: UserModel?.profilePictureURI || undefined }}>
`

may solve the stack issue, however, then the sub component of <Text>AK</Text> wont render. Additionally typescript does not support passing in a null value, nor is this a clean approach. I'd make a PR myself however, I'm not sure which approach the team wants to take to resolve this issue. 

`
WARN  source.uri should not be an empty string 
Image@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:75802:42
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:190447:23
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:205188:69
RCTView
View
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:190447:23
Box@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:180631:24
Avatar@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:209838:24
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
TouchableOpacity@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:65864:36
RCTView
View
RCTView
View
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:137306:43
StaticContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:119043:17
EnsureSingleNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:115398:24
SceneView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:118927:22
RCTView
View
RCTView
View
RCTView
View
CardSheet@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:130839:23
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:124390:38
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:123216:34
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
RCTView
View
Card@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:130194:36
CardContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:130915:34
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
Screen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129891:36
MaybeScreen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129770:24
RCTView
View
ScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129972:36
MaybeScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129741:23
RCTView
View
Background@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:121433:21
CardStack@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:127405:36
RCTView
View
SafeAreaProviderCompat@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:122958:24
RCTView
View
StackView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:120829:36
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:118691:24
StackNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:113068:32
PortalStackProfile
StaticContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:119043:17
EnsureSingleNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:115398:24
SceneView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:118927:22
RCTView
View
RCTView
View
Background@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:121433:21
Screen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:123034:71
RCTView
View
RCTView
View
ResourceSavingScene@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:122857:23
MaybeScreen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:145978:24
RCTView
View
MaybeScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:145947:23
RCTView
View
SafeAreaProviderCompat@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:122958:24
BottomTabView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:144793:30
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:118691:24
BottomTabNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:144672:32
_c@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:137306:43
StaticContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:119043:17
EnsureSingleNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:115398:24
SceneView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:118927:22
RCTView
View
RCTView
View
RCTView
View
CardSheet@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:130839:23
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:124390:38
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:123216:34
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
RCTView
View
Card@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:130194:36
CardContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:130915:34
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:70677:24
AnimatedComponentWrapper
Screen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129891:36
MaybeScreen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129770:24
RCTView
View
ScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129972:36
MaybeScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:129741:23
RCTView
View
Background@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:121433:21
CardStack@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:127405:36
RCTView
View
SafeAreaProviderCompat@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&:122958:24
RCTView
View
`

**Comment by mayank-96** [comment] 2022-03-01 11:01
Hello @Vercjames, I'm not able to reproduce your bug, can you please provide a snack/codeSandBox link.

**Comment by Vercjames** [comment] 2022-03-01 17:46
@mayank-96 of course friend!

https://snack.expo.dev/@vercjames/avatar-catch 

Additionally, any incoming variable with null or undefined tripes typescript (which is ugly) and adding an "image catch" string is both ugly and causes the actual device to throw a warning in both the console and on the device. 

![Screen Shot 2022-03-01 at 11 43 22 AM](https://user-images.githubusercontent.com/9423143/156220898-284c3b2d-155e-4fff-b302-c131ee2ecc0b.png)
![Screen Shot 2022-03-01 at 11 43 48 AM](https://user-images.githubusercontent.com/9423143/156220903-7c760b73-fe41-4977-abb8-410e07dd855d.png)
![Screen Shot 2022-03-01 at 11 43 54 AM](https://user-images.githubusercontent.com/9423143/156220904-bfd718a6-7a51-477d-bc73-694ebbb68ac3.png)

**Comment by surajahmed** [comment] 2022-03-30 08:53
@Vercjames This issue has been resolved in version `3.3.9`.

**Closed by surajahmed** 2022-03-30 08:53 UTC
Labels: bug, v3, triage
