### ISSUE TITLE
ActionSheet does not close smoothly by swipe down action

### ISSUE THREAD

**Issue by Great-hijack** [GeekyAnts/NativeBase#5068] opened 2022-06-08 12:39 UTC
### Description

ActionSheet does not close smoothly by swipe down action

### CodeSandbox/Snack link

https://snack.expo.dev/@zhen-zhu/actionsheet-issue-reporo

### Steps to reproduce

1. Tap 'ActionSheet' button 
2. Press the drag indicator and swipe down
3. ActionSheet will slide down and up and down. 

this is so quick action, though can detectable by naked eyes.

### NativeBase Version

3.4.6

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

Here is the video.

https://user-images.githubusercontent.com/57619523/173394115-b92978a4-7a30-4d8f-9a74-bd5d08f134b7.MP4

**Comment by Krithikj20** [comment] 2022-06-08 13:13
Hi @Great-hijack, Thank you for reporting this issue. We will look into it.

**Comment by Viraj-10** [comment] 2022-06-13 05:22
Hi @Great-hijack, I am unable to reproduce it. Can record your screen and upload a video?

**Comment by Great-hijack** [comment] 2022-06-13 15:59
> Hi @Great-hijack, I am unable to reproduce it. Can record your screen and upload a video?

@Viraj-10 edited the issue for the video.

**Comment by Viraj-10** [comment] 2022-06-21 10:53
This issue has been fixed in NativeBase `v3.4.7`

**Closed by Viraj-10** 2022-06-21 10:53 UTC
Labels: bug, v3, triage

**Comment by Great-hijack** [comment] 2022-06-24 13:50
@Viraj-10 It works like a charm. Thanks thousand!
