### ISSUE TITLE
[Ionicons] Two outline icons is broken in version >= 2.8.2

### ISSUE THREAD

**Issue by ahce** [GeekyAnts/NativeBase#2503] opened 2018-12-24 18:12 UTC
### Expected behaviour
- md-add-circle-outline
![image](https://user-images.githubusercontent.com/12452003/50405043-afa32a80-078d-11e9-8ac5-199d32d01c5e.png)
- ios-square-outline
![image](https://user-images.githubusercontent.com/12452003/50405038-a3b76880-078d-11e9-97f7-32af12fda3e3.png)

### Actual behaviour
- md-add-circle-outline
![image](https://user-images.githubusercontent.com/12452003/50405029-8edad500-078d-11e9-83ab-6895e765a6ec.png)
- ios-square-outline 
![image](https://user-images.githubusercontent.com/12452003/50405018-7d91c880-078d-11e9-82ed-5c59f461cf16.png)

### Environment
- native-base 2.10.0
- react 16.6.3
- react-native 0.57.8

**Comment by suvenduchhatoi** [comment] 2018-12-27 10:40
Actually, code snippet working as expected...No issues found here...Hope above snippet helps you...Closing the issue. You can reopen the issue if you feel it is exclusive to "native-base"...

**Comment by ahce** [comment] 2018-12-27 12:21
@suvenduchhatoi Thanks for your reply!
The bug persist.
Other people have the same problem.
[Check this](https://github.com/ionic-team/ionicons/issues/585)

I tried this:
- delete metro-cache and haste-map-metro
- npm cache clean --force
- delete icons link and run react-native link
- react-native run-android -- --reset-cache

**Comment by suvenduchhatoi** [comment] 2018-12-27 12:47
@ahce 
Ohh yes, it doesn't run fine on Android, but it is a 'react-native-vector-icons' issue...Since 'native-base' imports its Icon component from 'react-native-vector-icons', it is also rendering the wrong icon...So, it is not a 'native-base' issue...Check these:-
![screen shot 1440-04-20 at 6 12 01 pm](https://user-images.githubusercontent.com/44160581/50480693-812e8500-0a03-11e9-8f8e-9a1c53576f0e.png)
![screen shot 1440-04-20 at 6 12 36 pm](https://user-images.githubusercontent.com/44160581/50480694-812e8500-0a03-11e9-97ee-fa14a0ec58d5.png)

**Comment by suvenduchhatoi** [comment] 2018-12-27 12:53
It would be better if you create an issue to
https://github.com/oblador/react-native-vector-icons/issues

**Comment by suvenduchhatoi** [comment] 2018-12-28 07:54
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Closed by suvenduchhatoi** 2018-12-28 07:54 UTC
Labels: awaiting response
