### ISSUE TITLE
Passing new source to Image component does not updates it.

### ISSUE THREAD

**Issue by zoolyka** [GeekyAnts/NativeBase#4268] opened 2021-11-03 10:57 UTC
**Describe the bug**

The `<Image />` component does not re-render the image when its `source` property is updated.

**To Reproduce**

`<Image source={{ uri:  'https://via.placeholder.com/150/0000FF/FFFFFF/?text=one' }} />`

Then change the `uri` to `https://via.placeholder.com/150/0000FF/FFFFFF/?text=two` (via state update or such).

**Expected behaviour**

Render the image from the latest source.

**Platform**

- NativeBase version 3.2.1

**Additional information**

I think things went wrong with [this](https://github.com/GeekyAnts/NativeBase/commit/270f4eb64986b310480bb1b0644549d8458bc233#diff-27b7d5d466e41a1a338fca3b9859eb655d9badc47233d72c94a2bd8db87dfafc) commit.

**Comment by intergalacticspacehighway** [comment] 2021-11-03 11:16
@zoolyka thanks for reporting, can you checkout this comment?
https://github.com/GeekyAnts/NativeBase/issues/4242#issuecomment-954630156

**Comment by zoolyka** [comment] 2021-11-03 11:23
With the additional `key` property (and updating it along with the source) the re-render is triggered.

**Comment by intergalacticspacehighway** [comment] 2021-11-03 11:25
@zoolyka yes, can you verify if the Image component from React Native works as expected? 
AFAIK it also happens in React native's `Image` component which is being used under the hood by NativeBase's Image component.

**Comment by zoolyka** [comment] 2021-11-03 11:31
With the react-native Image component the key property is not needed. I think this is related to React.memo, in 3.1 a useEffect listener updated the internal source with a state update - if source changed a setSource(getSource()) was fired -, currently nothing happens and memo keeps the component as is.

**Comment by ankit-tailor** [comment] 2022-01-18 07:30
Hi @zoolyka , Solution for the issue is provided, closing the issue still if you have doubt you can reopen the issue.

**Closed by ankit-tailor** 2022-01-18 07:30 UTC
Labels: v3
