### ISSUE TITLE
paddingLeft StyleSheeet applied to Content component doesn't work on iPhone X

### ISSUE THREAD

**Issue by paour** [GeekyAnts/NativeBase#2293] opened 2018-09-24 08:17 UTC
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used

native-base 2.6.0
snack

### Expected behaviour

Stylesheets should work the same as inline styles.

### Actual behaviour

On iPhone X, inline styles applied to the NativeBase Content component are honored. However, if the Content style is defined as a stylesheet, some of its parameters are ignored.

### Steps to reproduce

This works:
```
      <NB.Container>
        <NB.Content
          style={{
            flex: 1,
            paddingLeft: 16,
            paddingRight: 16,
            paddingTop: 32,
          }}>
          <NB.H1>Working on iPhone X</NB.H1>
          <NB.Text>
            In this snack, running on any phone the paddingLeft is honored,
            because the style is inline.
          </NB.Text>
        </NB.Content>
      </NB.Container>
```

https://snack.expo.io/@paour/iphone-x-paddingleft-inline

![image](https://user-images.githubusercontent.com/90963/45942504-fcd2fd00-bfe2-11e8-9848-21140d127a1d.png)

This doesn't (on iPhone X only):

```
      <NB.Container>
        <NB.Content style={styles.content}>
          <NB.H1>Broken on iPhone X</NB.H1>
          <NB.Text>In this snack, running on a phone other than iPhone X, the left and right padding are honored.</NB.Text>
          <NB.Text>However, on iPhone X, the left padding is ignored.</NB.Text>
        </NB.Content>
      </NB.Container>
```

https://snack.expo.io/@paour/iphone-x-paddingleft-stylesheet

![simulator screen shot - iphone x - 2018-09-24 at 10 19 07](https://user-images.githubusercontent.com/90963/45942576-4facb480-bfe3-11e8-9b61-d4d064610f91.png)

### Is the bug present in both iOS and Android or in any one of them?

iPhone X

**Comment by SupriyaKalghatgi** [comment] 2018-12-20 09:52
Works similar for iPhoneX and iPhone7

![image](https://user-images.githubusercontent.com/13464885/50277656-00074900-046b-11e9-80b8-7c32fd6c63f6.png)

**Comment by paour** [comment] 2018-12-20 11:12
The working case should be the same on all phones. The broken case is I think different on iPhone 7 than iPhone X. Or did I misunderstand the question?

**Comment by paour** [comment] 2018-12-21 17:07
There are two snacks:
- https://snack.expo.io/@paour/iphone-x-paddingleft-inline which works on all platforms.

![working](https://user-images.githubusercontent.com/90963/50354218-1389e100-054b-11e9-9b2d-93a1c2f73b2d.png)

- https://snack.expo.io/@paour/iphone-x-paddingleft-stylesheet which works on notch-less iPhones, but is broken on the X (paddingLeft is not applied and the view is offset to the left)

![broken](https://user-images.githubusercontent.com/90963/50354269-403df880-054b-11e9-9002-93320cd09d6d.png)

**Comment by suvenduchhatoi** [comment] 2018-12-26 06:37
@paour 
Check using :
"react": "16.5.0",
 "react-native": "0.57.1",
"native-base":"2.10.0"

Code on iPhone X(11.2) & iPhone 7(11.2) working fine both using inline-style and Stylesheet
![screenshot 2018-12-26 at 11 59 11 am](https://user-images.githubusercontent.com/44160581/50435311-b43f1e80-0906-11e9-9c7b-d75ec7679dca.png)
![screenshot 2018-12-26 at 12 01 22 pm](https://user-images.githubusercontent.com/44160581/50435312-b43f1e80-0906-11e9-8747-741270680cf9.png)

**Comment by suvenduchhatoi** [comment] 2018-12-26 07:57
Closing the issue...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Closed by suvenduchhatoi** 2018-12-26 07:57 UTC
Labels: awaiting response, theme
