### ISSUE TITLE
Android: Slow performance

### ISSUE THREAD

**Issue by KrajncJ** [GeekyAnts/NativeBase#1012] opened 2017-07-03 12:23 UTC
## react-native, react and native-base version
RN: 0.41.2
NB: 2.1.0
## Expected behaviour
Smooth performance without delay.
## Actual behaviour

If Styleprovider is included in my component, I am noticing significantly slower performance (ex. it takes about 2s to mark checkbox). It also sometimes happens that the styleprovider's style is applied to component even component was not wrapped in it. After reload JS, style is restored back to normal.

**It seems that when remote JS debugging is on, it works much smoother.**

I had a similar problem with performance before, but with the upgrade NativeBase to v2.1.0,  I achieved a better performance, but since android on my phone has updated to 7.0, the application became very slow again.

## Steps to reproduce (code snippet or screenshot)
Wrap complex component into StyleProvider. I am using Content => ListItem => Checkbox. 

## Is the bug present in both ios and android or in any one of them?
Running only on Android

**Comment by srhise** [comment] 2017-07-20 23:38
Really good cache @KrajncJ. I have found that when the remote debugger is connected, the performance is much faster on a dev build.

Is it fair to say that performance issues are isolated to dev builds with remote debugging turned off? 

If so, what could possibly be the issue in that case?

**Comment by ianjwood** [comment] 2017-09-21 16:04
I've seen the same; although I was using an older version (only 6 weeks old). I've upgraded to react-native 0.48.3 and native-base 2.3.2 but still lag when the debugger isn't connected.

Looking at the framerates on device (I'm using a deliberately low end Android 6 phone - HOMTOM HT-16 device for testing) I see the JS framerate drop from a rock solid 49.7/8 to an impossible -2.1 when tapping a TouchableOpacity to slide in a react-native-modal. Other users using better devices see the lag too. I also see similar lag when moving between Tabs which is more native-base territory.

I"m going to have a look through the performance related issues here to see if there is anything known that I'm doing. The are alot of semi-transparent or fading layers flying around here :)

**Comment by kylanhurt** [comment] 2017-10-06 00:53
Yeah it seems that performance on React Native in general may be an uphill battle.

**Comment by inv2004** [comment] 2017-11-18 00:47
The same problem.
Is it styleprovider only problem and better to avoid it ?

**Comment by Laurensdc** [comment] 2018-02-05 07:22
Same issue, but has nothing to do with the remote JS debugger.
Even when publishing the app, the same performance issues arise.
Unfortunately it makes NativeBase unusable.

Having the issue in combination with Redux and React Navigation (TabNavigator).

**Comment by douglasjunior** [comment] 2018-02-17 11:16
Same issue here.

**Comment by XuanPH** [comment] 2018-02-28 16:03
Same issue on ios. 
It's very slow When I build release on Iphone and Ipad.

**Comment by fxhereng** [comment] 2018-03-06 15:13
Same issue here, takes 1 minute to change a tab.. Makes library unusable.

**Comment by fxhereng** [comment] 2018-03-06 16:17
Rendering a custom tabbar with prop `renderTabBar` using `ScrollableTab` component makes it much smoother.

Also adding `prerenderingSiblingsNumber={NUMBER_OF_TABS}` reduces flickering when changing tab.

**Comment by userbq201** [comment] 2018-08-01 09:54
with StyleProvider - whery slow

**Comment by userbq201** [comment] 2018-08-01 15:40
I created own check box

**Comment by kala888** [comment] 2019-04-04 02:56
same issue

**Comment by masierraf** [comment] 2019-05-28 21:27
I got the same problem with Tabs > 3 Tab (with FlatList each). it is to slow when i press or swipe between tabs

**Comment by masierraf** [comment] 2019-05-28 21:28
> with StyleProvider - very slow

@userbq201 did you found a way to solve it?

**Comment by waqaramjad** [comment] 2019-12-18 10:29
same problem app is super slow with native base

**Comment by laithfawwaz** [comment] 2020-12-23 08:10
Did anyone fix the issue here?

**Comment by chiubaka** [comment] 2021-11-02 02:03
Following up on my own comment here: after some investigation, I've discovered that performance degradation in my app has little to do with Native Base. In my particular case, things slowed down by almost 100x after attempting to set the default timezone using `luxon`, likely due to some inefficient polyfills I was using for i18n support. I've found a way around using those polyfills, and Android performance profile has returned to normal.

**Comment by leonardomdr** [comment] 2021-12-04 14:26
> Following up on my own comment here: after some investigation, I've discovered that performance degradation in my app has little to do with Native Base. In my particular case, things slowed down by almost 100x after attempting to set the default timezone using `luxon`, likely due to some inefficient polyfills I was using for i18n support. I've found a way around using those polyfills, and Android performance profile has returned to normal.

How did that investigation @chiubaka? I would like to understand your process to check that. I'm using luxon here, and my native-base modal looks slow.

**Comment by chiubaka** [comment] 2021-12-04 23:50
I ran a `git bisect` on my app until I isolated a commit that was clearly causing the problem. This left me with many, many commits with Native Base enabled and no issues, and narrowed down to a single commit with a `luxon` default timezone configuration that was clearly causing the problem.

**Comment by leonardomdr** [comment] 2021-12-05 11:33
> I ran a `git bisect` on my app until I isolated a commit that was clearly causing the problem. This left me with many, many commits with Native Base enabled and no issues, and narrowed down to a single commit with a `luxon` default timezone configuration that was clearly causing the problem.

Aww.. got it. I'm in the beginning of this app development, I will just remove luxon and check if the modal gets a better performance. Thanks anyways.

**Comment by pierroo** [comment] 2021-12-10 17:42
I'm afraid I'll have to join the party: NativeBase Modals are incredibly slow to open / close; it takes almost 1 full second to appear / disappear; even with barely anything in it. (just text and a few boxes)

I don't have any luxon or complicated components in there; 
I'm on the latest versions of React Native and NativeBase.
this is quite frustrating, unable to pinpoint the issue :/

@leonardomdr you mentioned you had the issue with their modal too; is it still happening on your end?

**Comment by leonardomdr** [comment] 2021-12-12 21:58
Yes, it is still slow. Not a published app yet, it's under development, but
if it's still slow in the future, I will have to look for another solution.

I haven't tested yet, because I have been studying react memo and
other stuff about performance for react native apps.

I'm using the latest versions as well (native-base and react-native)..



Em sex., 10 de dez. de 2021 às 14:42, Pierre ***@***.***>
escreveu:

**Comment by one-god** [comment] 2022-01-18 02:08
I have the same  issue 
I'm on the latest versions of React Native and NativeBase.

**Comment by ishwarATanveshak** [comment] 2022-01-19 04:47
In my case problem gets resolved after uploading build on play store. I don't know how. But performance of the app has increased and does not show laggy behavior.

**Comment by bitfield66** [comment] 2022-05-23 16:57
did anyone find any solution? I have the same issue here

**Comment by ankit-tailor** [comment] 2022-09-12 10:15
This issue is a duplicate of #4302. We are actively working on this issue.

**Closed by ankit-tailor** 2022-09-12 10:15 UTC
Labels: duplicate, performance, android, theme

**Comment by hotaryuzaki** [comment] 2023-01-12 12:37
I face the same issue, i have a gallery of photos and each photo has a checkbox.
i am using Flatlist and native base checkbox, and I create different state for the checked item (not in flatlist data).
in debug it takes 3 seconds to get checked, more datas more time it takes.
i dont know the problem because of Flatlist or checkbox or both.

is there any solution that can i try?
