### ISSUE TITLE
Item component crashes when conditionally rendering another component inside it

### ISSUE THREAD

**Issue by wakiem** [GeekyAnts/NativeBase#2350] opened 2018-10-10 17:15 UTC
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used
node: v9.9.0
npm: 4.6.1
react: 16.3.1
react-native: 0.57
native-base: 2.8.1

### Expected behaviour
I can conditionally render an icon inside an Item component

### Actual behaviour
App is crashing when using conditional rendering inside Item component

### Steps to reproduce
On mount the 2nd icon is hidden as expected.
When I type something the 2nd icon shows up, as expected.
When I clear the search (either by pressing the icon or be deleting the text myself) the app crashes.
```
import React from 'react';

import { TouchableOpacity } from 'react-native';
import { Item, Input, Icon } from 'native-base';

class Search extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      search: '',
    };
  }

  onSearch = (text) => {
    this.setState({ search: text });
  }

  render() {
    const { search } = this.state;

    return (
            <Item>
              <Icon name="ios-search" style={{ marginLeft: 10 }} />
              <Input
                placeholder="Search"
                autoCapitalize="none"
                value={search}
                onChangeText={this.onSearch}
              />
              {search &&
                <TouchableOpacity onPress={() => this.onSearch('')}>
                  <Icon name="ios-close" style={{ marginRight: 10 }} />
                </TouchableOpacity>
              }
            </Item>
    );
  }
}

export default Search;
```

![img_0894](https://user-images.githubusercontent.com/21678441/46753671-c70b6500-ccc0-11e8-9da1-c302f4e2930a.png)

### Is the bug present in both iOS and Android or in any one of them?
Only tested on iOS

**Comment by SupriyaKalghatgi** [comment] 2018-10-30 10:05
@wakiem After trying out above snippet, I get different error

![image](https://user-images.githubusercontent.com/13464885/47710666-5a4d1000-dc59-11e8-9e9d-c7caecbfbba5.png)

Please verify the above snippet posted

**Comment by minhdang-idev** [comment] 2018-10-31 08:57
Please my snippet: https://snack.expo.io/@yanghuyming/dHJlbW
Even though I think my issue is different: #2364

**Comment by suvenduchhatoi** [comment] 2018-12-21 07:44
@wakiem 
Please check again with the code snippet you have provided for the corresponding error. On running your snippet, we are getting the error as mentioned above by @SupriyaKalghatgi... but I tried out for conditional rendering of Icon within an Item component as below
```
import React, { Component } from "react";
import { Item, Icon } from "native-base";
export default class ItemViewComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isGreeting: false,
    };
  }
  render() {
    const helloMessage = <Icon name="ios-home" />;
    const goodbyeMessage = <Icon name="ios-menu" />;
    return console.log(this.state.isGreeting), (
      <Item style={{ marginTop: 30 }}>
        {this.state.isGreeting ? helloMessage : goodbyeMessage}
      </Item>
    );
  }
}
```
It works fine...You can try this out...

**Comment by minhdang-idev** [comment] 2018-12-24 07:05
> 
> 
> Please my snippet: https://snack.expo.io/@yanghuyming/dHJlbW
> Even though I think my issue is different: #2364

Can you please also check my issue? My issue is marked as duplicated with this issue but it is actually not! It is different. And my snippet show that it is really simple to reproduce my issue.

**Comment by suvenduchhatoi** [comment] 2018-12-26 07:54
@minhdang-idev 
#2364
@wakiem 
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Closed by suvenduchhatoi** 2018-12-26 07:54 UTC
Labels: awaiting response
