### ISSUE TITLE
activeTextStyle and activeTabStyle are not working in react-native 0.60.4

### ISSUE THREAD

**Issue by DivinoMatheus** [GeekyAnts/NativeBase#2815] opened 2019-07-25 17:38 UTC
Apparently the props `activeTextStyle` and `activeTabStyle` from component `<Tab>` are not working when the active tab changes in react-native version 0.60.4.

**Example:**
![image](https://user-images.githubusercontent.com/27539713/61895548-5947c700-aee9-11e9-8e8c-5d2049b0d524.png)

Someone can help me in this case?

**Comment by sankhadeeproy007** [comment] 2019-07-26 08:09
Please check with 2.13.3

**Comment by nirre7** [comment] 2019-08-07 06:20
Same as #2795

**Comment by Srishti-Sharma** [comment] 2019-08-07 11:57
Please follow the issue template. Provide proper steps to reproduce the issue at our end.

**Comment by nirre7** [comment] 2019-08-09 07:38
No worries I'll add it 👍 





## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Before updating our app to RN 0.60.4 and NB 2.13.4 the native base theme variables topTabBarTextColor, topTabBarActiveTextColor worked great. After the update they don't.
If we downgrade NB to 2.12.1 they work.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node               12.8.0 
npm                6.10.3 
app rn version     0.60.4
react-native-cli   2.0.1 
xcode              10.3

### Expected behaviour
topTabBarTextColor, topTabBarActiveTextColor work

### Actual behaviour
topTabBarTextColor, topTabBarActiveTextColor doesn't work, we get the default styling

### Steps to reproduce
Please refer to reporters screen shot

Use NB 2.13.4 with RN 0.60.4

### Is the bug present in both iOS and Android or in any one of them?
Yes

### Any other additional info which would help us debug the issue quicker.
Could be a duplicate of #2795

**Comment by PlabanJr** [comment] 2019-08-16 14:20
This is a duplicate of #2795. Please refer to #2795.

**Closed by PlabanJr** 2019-08-16 14:20 UTC
Labels: awaiting response
