### ISSUE TITLE
Text hidden in Header Title

### ISSUE THREAD

**Issue by andidev** [GeekyAnts/NativeBase#670] opened 2017-03-22 08:47 UTC
Body hides text in Header Title and wraps text in Subtitle even though there is no content to the Right.

e.g.  
```xml
<Header>
    <Left>
        <Button transparent onPress={RouterActions.pop}>
            <Icon name="arrow-back" />
        </Button>
    </Left>
    <Body>
        <Title>A Long Header Title</Title>
        <Subtitle>A Long Header Subtitle</Subtitle>
    </Body>
    <Right />
</Header>
```
renders to:
![skarmavbild 2017-03-22 kl 09 40 50](https://cloud.githubusercontent.com/assets/571389/24189012/bb6d1bd6-0ee3-11e7-8f6f-1981e89da7f7.png)

Removing the Right-tag results in that the Body is not centered:
![skarmavbild 2017-03-22 kl 09 42 34](https://cloud.githubusercontent.com/assets/571389/24189074/eb5a8798-0ee3-11e7-9358-c88f792f09d3.png)

Shouldn't the Right-tag and Left-tag only take up as much place as needed while the Body takes up as much as possible?

```
"native-base": "2.0.13",
"react": "15.4.2",
"react-native": "0.42.3",
```

**Comment by sankhadeeproy007** [comment] 2017-03-22 08:54
Duplicate of #605 and #567.

**Closed by sankhadeeproy007** 2017-03-22 08:54 UTC

**Comment by andidev** [comment] 2017-03-22 21:09
Thanks! That solves it.
