### ISSUE TITLE
How to fix the SSRProvider Warning in React Native?

### ISSUE THREAD

**Issue by sanketsahu** [GeekyAnts/NativeBase#4273] opened 2021-11-05 18:29 UTC
I am using NativeBase with my ReactNative App. It is running ok. However there is a warning that is bugging me a little bit.

How do I fix the warning below?

> When server rendering, you must wrap your application in an to ensure consistent ids are generated between the client and server. FormControl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.wenyang.DanceConnectyCube:162364:111 RCTView View

**Comment by MuhammadKaleem171** [comment] 2021-11-06 06:40
same issue 
any solution ?

**Comment by rkritskiy** [comment] 2021-11-08 23:03
+1

**Comment by milkyway044** [comment] 2021-11-09 13:07
+ 1

**Comment by Mahuton** [comment] 2021-11-14 07:06
It's like you are using a UI library probably based on Bootstrap

Steps to solve:
1-Install react-bootstrap  -->  npm install react-bootstrap bootstrap@5.1.3
2-import SSRProvider from 'react-bootstrap/SSRProvider'
3- Wrap your app like below
<SSRProvider>
  <App />
</SSRProvider>

Hope this helps

**Comment by lvschlee** [comment] 2021-11-16 01:08
+1

**Comment by Luca8991** [comment] 2021-11-19 09:15
+1

**Comment by Luca8991** [comment] 2021-11-19 09:19
I get this warning when using Slider:
```
When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:49:24 in useId
at node_modules/@react-aria/utils/dist/main.js:661:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider

```

**Comment by rs6g10** [comment] 2021-11-20 00:52
Facing exact same problem. I get error pointed at FormControl
<img width="1251" alt="Screenshot 2021-11-20 at 00 51 22" src="https://user-images.githubusercontent.com/1889234/142708293-2a3a0ca9-1a40-4aed-bd13-2120c0642000.png">

**Comment by chenkaiC4** [comment] 2021-11-20 13:52
anyone know how to fix it? too many warning

**Comment by chenkaiC4** [comment] 2021-11-20 13:56
i have fix it, it' a third lib named **`react-aria`**。

https://react-spectrum.adobe.com/react-aria/ssr.html

install and wrap the root App.

**Comment by chewyx212** [comment] 2021-11-23 03:43
Same problem when using Menu.

**Comment by harrychow2** [comment] 2021-11-30 05:15
Same issue there when using Modal

**Comment by arun-aswathanarayan** [comment] 2021-12-17 01:11
I too am getting a bunch of errors when using a Slider in a Modal. 

```
When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:21:12 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18671 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:22:21 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18671 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/utils/dist/main.js:678:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18671 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:21:12 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18671 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:22:21 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18671 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/utils/dist/main.js:678:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18671 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:21:12 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:23666 in B$argument_0.callback
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:22:21 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:23666 in B$argument_0.callback
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/utils/dist/main.js:678:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:23666 in B$argument_0.callback
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:21:12 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:23666 in B$argument_0.callback
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:22:21 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:23666 in B$argument_0.callback
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/utils/dist/main.js:678:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:23666 in B$argument_0.callback
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:21:12 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:22:21 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/utils/dist/main.js:678:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:21:12 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/label/dist/main.js:22:21 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>

When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:54:4 in useSSRSafeId
at node_modules/@react-aria/utils/dist/main.js:48:24 in useId
at node_modules/@react-aria/utils/dist/main.js:678:12 in useLabels
at node_modules/@react-aria/label/dist/main.js:35:28 in useLabel
at node_modules/@react-native-aria/slider/src/useSliderThumb.ts:44:37 in useSliderThumb
at node_modules/native-base/src/components/primitives/Slider/SliderThumb.tsx:32:37 in SliderThumb
at node_modules/react-hook-form/dist/index.cjs.js:1:5895 in next
at node_modules/react-hook-form/dist/index.cjs.js:1:18849 in <anonymous>
```

**Comment by Monisankarnath** [comment] 2021-12-20 12:06
I am facing the same issue when using nativebase modal. Any solution on this @sanketsahu

**Comment by Bamorem** [comment] 2022-01-05 08:53
same for me , but the weirdest thing is that it does it to me only on IOS. when i'm using Actionsheet

**Comment by edgaraskazlauskas** [comment] 2022-01-05 13:26
Same, form control inside action sheet.

**Comment by nabinem** [comment] 2022-01-12 12:28
For me its happening only on IOS when Menu used inside Modal.Header

**Comment by Dramex** [comment] 2022-01-19 17:37
same

**Comment by razorwebs** [comment] 2022-01-21 10:35
I had this same issue. I am using React Native and Nativebase.IO

Terminal Error: "When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server."

Solution:

1. Add SSR Package
`npm i @react-aria/ssr or yarn add @react-aria/ssr`

2. Import SSR
`import {SSRProvider} from '@react-aria/ssr'; `

3. Wrap your main app or current provider with SSRProvider. Example below: React Native + Nativebase.IO

 `<SSRProvider>
<NativeBaseProvider>
<AppProvider />
</NativeBaseProvider>
</SSRProvider>`

4. Terminate, rebuild, and/or reload the app.


Sources:
https://react-spectrum.adobe.com/react-aria/ssr.html
https://react-spectrum.adobe.com/react-aria/SSRProvider.html
https://www.razorwebs.com/how-to-fix-ssrprovider-warning-on-react-native-nextjs-native-base/

**Comment by zettaka** [comment] 2022-02-04 07:38
I still have the same issue. I followed the instructions of razorwebs solution without any effect. The warning remains.

**Comment by razorwebs** [comment] 2022-02-04 07:51
> I still have the same issue. I followed the instructions of razorwebs solution without any effect. The warning remains.

Are you making any data fetches in say a dynamic component that is out of the scope of the SSR wrapper? Any data fetch that somehow gets past the SSR Wrapper will continue to throw the error when executed on the client device.

**Comment by zettaka** [comment] 2022-02-04 08:44
> Are you making any data fetches in say a dynamic component that is out of the scope of the SSR wrapper? Any data fetch that somehow gets past the SSR Wrapper will continue to throw the error when executed on the client device.

I'm not sure what in detail you're talking about. I've added a native-base menu overlay which raises the warning from it's useMenuTrigger function (origin is useSSRSafeId). I placed the SSRProvider at the app root, just before the NativeBaseProvider. I've also tried to wrap the screen component that uses the menu without success.

Basically I don't understand the SSR topic. SSR shouldn't be a matter in a react native app or am I missing something? For me it looks like the native-base menu uses an id generating function from react-aria which causes the warning. Wouldn't it be better to generate the id in a different way? Isn't it a bug? It doen't feel right to use that SSRProvider without using SSR only to get rid of that warning...

**Comment by johnf** [comment] 2022-02-08 09:12
I'm seeing this and wondering if it has something to do with the Modal creating a context.
I'm doing something like

```jsx
  <Formik>
    <Modal>
     <FormControl>
  </Modal>
</Formik>
```

Strange thing is it's fine on android but I have issues on ios and web

**Comment by geoffreyLB** [comment] 2022-02-25 13:05
Same problem when using Modal.

**Comment by newme616** [comment] 2022-03-03 14:43
same problem

**Comment by jrluizcarlos** [comment] 2022-03-22 00:43
As long as there is no solution.

I used SSRProvider and also:

import { LogBox } from 'react-native';
...
LogBox.ignoreLogs([
    'When rendering the server, you must wrap your app in a <SSRPrvider>',
]);
...

**Comment by jologz** [comment] 2022-03-22 18:38
For now, I have replaced `FormControl` with `Box` until there is a fix.

**Comment by johnf** [comment] 2022-03-25 06:14
I think I've tracked down the issue here. 
See NativeBaseProvider https://github.com/GeekyAnts/NativeBase/blob/master/src/core/NativeBaseProvider.tsx#L76-L105

```jsx
<OverlayProvider>
  <ToastProvider>
    <InitializeToastRef />
      {isSSR ? <SSRProvider>{children}</SSRProvider> : children}
  </ToastProvider>
</OverlayProvider>
```

the SSRProvider is mounted inside the ToasProvider.

However the OverlayViews for Modals, ActionSheets etc are mounted as siblings to the ToastProvider

![image](https://user-images.githubusercontent.com/42590/160064867-b1641de8-bcb0-4d58-931a-2ef9b6b81026.png)

perhaps the SSRProvider needs to be placed outside the OvaerlayProvider?

**Comment by mcatal** [comment] 2022-03-30 06:56
> 

Hi, i'm upgrade to 3.3.8 and i get this error(warn) now. I'm using react-navigation, expo and native-base 3.3.8

**Comment by surajahmed** [comment] 2022-03-30 07:40
@johnf Thanks for working on this. We're going to make those changes in the coming release.

**Comment by johnf** [comment] 2022-04-06 21:12
@surajahmed #4824  hasn't fixed this issue. (Not sure if it was intended to).

I think to fix it properly the SSRProvider needs to be moved further up the JSX Element hierarchy. or the Modals need to be attached lower down.

Also for testing purposes, this mainly seems to affect iOS for me, I suspect that is due to the different implementations in Overlay https://github.com/GeekyAnts/NativeBase/blob/master/src/components/primitives/Overlay/Overlay.tsx#L44-L67

**Comment by surajahmed** [comment] 2022-04-13 08:15
@johnf We've found the issue. We're using `react-aria` for accessibility. Which throws an error in the native platform. We're working on it.

**Comment by johnf** [comment] 2022-05-11 08:07
@surajahmed Semi realated but something I've hit a couple of times where things work fine on Android but break on ios

Native Base <Modal>
* On android uses react-natve Modal
* on ios uses Overlay which in turn users react-aria overlay

The key issue here is that the modal will get attache to different places.
On android it is attached where it's called
On ios it gets attached to the OverlayProvider at the top of the tree.

This means you can't do this
```jsx
<Context.Provider>
  <Modal>
   <Context.Consumer>
```
The above works fine on android but breaks on ios

If I remove the RNModalAndroid check  in Overlay.tsx and just use react-native Modal then everything works on both platforms.

**Comment by johnf** [comment] 2022-05-11 21:24
I'm now using the following patch with patch-package to work around these issues.
Will let you know if I come across any issues

```diff
diff --git a/node_modules/native-base/src/components/primitives/Overlay/Overlay.tsx b/node_modules/native-base/src/components/primitives/Overlay/Overlay.tsx
index 2ceb401..85b8234 100644
--- a/node_modules/native-base/src/components/primitives/Overlay/Overlay.tsx
+++ b/node_modules/native-base/src/components/primitives/Overlay/Overlay.tsx
@@ -21,7 +21,6 @@ export interface IOverlayProps {
 export function Overlay({
   children,
   isOpen,
-  useRNModalOnAndroid = false,
   isKeyboardDismissable = true,
   //@ts-ignore
   animationPreset = 'fade',
@@ -47,27 +46,16 @@ export function Overlay({
     return null;
   }
 
-  if (Platform.OS === 'android' && useRNModalOnAndroid) {
-    return (
-      <ExitAnimationContext.Provider value={{ exited, setExited }}>
-        <Modal
-          transparent
-          visible={isOpen}
-          onRequestClose={onRequestClose}
-          animationType={animationPreset}
-        >
-          {children}
-        </Modal>
-      </ExitAnimationContext.Provider>
-    );
-  }
-
   return (
-    //@ts-ignore
-    <OverlayContainer style={{ ...styleObj }}>
-      <ExitAnimationContext.Provider value={{ exited, setExited }}>
+    <ExitAnimationContext.Provider value={{ exited, setExited }}>
+      <Modal
+        transparent
+        visible={isOpen}
+        onRequestClose={onRequestClose}
+        animationType={animationPreset}
+      >
         {children}
-      </ExitAnimationContext.Provider>
-    </OverlayContainer>
+      </Modal>
+    </ExitAnimationContext.Provider>
   );
 }
```

**Comment by manuelsechi** [comment] 2022-05-22 07:20
> It's like you are using a UI library probably based on Bootstrap
> 
> Steps to solve: 1-Install react-bootstrap --> npm install react-bootstrap bootstrap@5.1.3 2-import SSRProvider from 'react-bootstrap/SSRProvider' 3- Wrap your app like below
> 
> ```
>  <SSRProvider> 
>      <App /> 
> </SSRProvider>
> ```
> 
> Hope this helps

this solved for me. thank you.

**Comment by biskis** [comment] 2022-05-30 20:18
I tried to install `@react-aria/ssr` and add `<SSRProvider>` first in the App.tsx return statement, but the error is still here. 

Do we have an estimate of when this will be fixed? 

This is my App.tsx

```
import { SSRProvider } from '@react-aria/ssr';

....

return (
        <SSRProvider>
            <Provider store={store}>
                <NativeBaseProvider theme={customTheme}>
                    <Navigation/>
                </NativeBaseProvider>
            </Provider>
        </SSRProvider>
    );
```

**Comment by veho-paul** [comment] 2022-06-09 20:42
So FormControls in Modals are a no go, right? Any progress on this?

**Comment by Djauron** [comment] 2022-06-29 15:46
any update ?

**Comment by koniushko** [comment] 2022-07-04 08:16
+1

**Comment by Abhineetk47** [comment] 2022-07-12 07:24
Getting this warning while using Slider and Popover in Nativebase 3.4.6

> When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
at node_modules/@react-aria/ssr/dist/main.js:61:90 in $29383e587d62412a$export$619500959fc48b26
at node_modules/@react-aria/utils/dist/main.js:48:14 in $8c61827343eed941$export$f680877a34711e37
at node_modules/@react-aria/label/dist/main.js:31:9 in $ce7359c25a7dec1c$export$8467354a121f1b9f
at node_modules/@react-native-aria/slider/src/useSlider.ts:37:35 in useSlider
at node_modules/native-base/src/components/primitives/Slider/Slider.tsx:55:25 in Slider
at [native code]:null in performSyncWorkOnRoot
at [native code]:null in callFunctionReturnFlushedQueue

**Comment by FelipeCruzat** [comment] 2022-07-13 13:12
It's like you are using a UI library probably based on Bootstrap and Next. Thank Mahuton

Steps to solve:
1-Install react-bootstrap --> npm install react-bootstrap bootstrap@5.1.3
2-import SSRProvider from 'react-bootstrap/SSRProvider'
3- Wrap your app like below

function MyApp({ Component, pageProps }) {
  return (
    <SSRProvider> 
  <Component {...pageProps} />
  </SSRProvider>
  )
}

**Comment by FelipeCruzat** [comment] 2022-07-13 13:17
Para Next Envuelve con SSRProvider en archivo _app.js, elemento Component

**Comment by lisimba** [comment] 2022-07-13 15:44
None of the mentioned fixes have worked for me so what I resorted to is filtering out those particular log messages using something like this in my `index.js` file:

```/**
 * @format
 */

import {AppRegistry, LogBox} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
LogBox.ignoreLogs([
  'When server rendering',
]);
AppRegistry.registerComponent(appName, () => App);
```

Obviously, this doesn’t address the actual issue but it should make development more tolerable by not having logs spammed with that warning.

**Comment by kaaax0815** [comment] 2022-07-27 17:54
How is this not fixed?

**Comment by surajahmed** [comment] 2022-08-03 06:43
Thanks for your patience. We have to prioritize this issue. We'll fix this soon.

**Comment by inform880** [comment] 2022-08-06 00:12
@surajahmed Thank you!

**Comment by aendel** [comment] 2022-08-12 13:58
+1

**Comment by rvkayy** [comment] 2022-08-19 06:11
Any update on this?

**Comment by MuflahNasir** [comment] 2022-08-27 07:21
When are we expecting a permanent fix on this issue?

**Comment by joviksdev** [comment] 2022-08-30 10:57
have Similar issues, which only occurs when running ios but for android, I didn't get this error. Any update on this?

**Comment by fleecmf** [comment] 2022-09-07 11:38
same with Popover

**Comment by surajahmed** [comment] 2022-09-08 07:09
This issue is fixed in this [PR](https://github.com/GeekyAnts/NativeBase/pull/5327). Going to merge and release it in the coming release. Thanks for your patience.

**Comment by ankit-tailor** [comment] 2022-09-09 08:10
Hi Everyone, Thanks for your patience. This issue is fixed in `3.4.14`.

**Closed by ankit-tailor** 2022-09-09 08:10 UTC
Labels: v3

**Comment by sarulathadurai** [comment] 2023-03-08 13:07
Hi I am facing this issue in slider component of nativebase V3.4.26 in ios

**Comment by localjo** [comment] 2023-03-27 07:18
I'm also seeing this issue in the slider component in v3.4.25 in iOS

**Comment by arun-aswathanarayan** [comment] 2023-04-24 05:42
I don't see how this issue is fixed yet. It is happening in v3.4.25 in iOS.

**Comment by mfrfinbox** [comment] 2023-06-27 21:58
This issue is neither resolved in 3.4.14 as mentioned by @ankit-tailor, neither is on 3.4.28, not sure what went wrong there, but it is a very annoying warning.

**Comment by ayranlouro** [comment] 2023-06-27 22:11
im on react 18.2v and this alerts appears to me after installed native base:

In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.

Any ideas?

**Comment by lucaslozz** [comment] 2023-06-28 18:12
> im on react 18.2v and this alerts appears to me after installed native base:
> 
> In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
> 
> Any ideas?

I'm geting the same issue.

**Comment by shrikkkk** [comment] 2023-07-01 03:42
I am still getting this issue in 3.4.28

**Comment by darkomenx** [comment] 2023-07-01 15:40
![image](https://github.com/GeekyAnts/NativeBase/assets/16452686/c3ec9047-3054-4a9d-b9e3-9ec2200bfdb8)

Same also if I use SSProvider wrapper tag app...

**Comment by ahirdman** [comment] 2023-07-29 10:35
Still not resolved for me either. Packages used:

```json
 "dependencies": {
    "@react-navigation/native": "^6.0.2",,
    "expo": "~49.0.3",
    "expo-application": "~5.3.0",
    "expo-auth-session": "~5.0.2",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-crypto": "~12.4.1",
    "expo-dev-client": "~2.4.6",
    "expo-device": "~5.4.0",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-network": "~5.4.0",
    "expo-router": "2.0.0",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-updates": "~0.18.10",
    "expo-web-browser": "~12.3.2",
    "native-base": "^3.4.28",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.45.2",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "~0.19.6",
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@testing-library/jest-native": "^5.4.2",
    "@testing-library/react-native": "^12.1.2",
    "@types/jest": "^29.5.3",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.45.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-import-resolver-typescript": "^3.5.5",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.3",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-react-native-a11y": "^3.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "prettier": "^3.0.0",
    "react-test-renderer": "^18.2.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.3"
  },
  "overrides": {
    "react-refresh": "~0.14.0"
  },
  "resolutions": {
    "react-refresh": "~0.14.0"
  }
}
```
