### ISSUE TITLE
The issue with Input in Tabs

### ISSUE THREAD

**Issue by alexn777** [GeekyAnts/NativeBase#550] opened 2017-02-22 13:29 UTC
Hello,

I have created a test project on Windows 7 to show you the issues with the Input component in Tabs. I am using Exponent XDE v14.0.0 and running the project on Genymotion emulator for Google Nexus 5 4.4.4 API 19.

## Versions used
* node.js 7.6.0
* exponent 14.0.0
* react 15.4.0
* react-native 0.41.0
* native-base 2.0.7

## Expected behaviour
I am able to enter a long text in the input box.

## Actual behaviour
After entering the text, which fills the visible area of the input box, I am able to enter few more letters and then after entering a letter the current tab moves to the left showing some part of the next tab on the right hand side of the current tab and the input box stops receiving any keyboard input. Then If I set the focus after the last letter, enter a letter, the current tab moves to the left again and the input box stops receiving any keyboard input again and so on.

## The project code
```javascript
import Exponent from 'exponent';
import React from 'react';
import {
  Platform,
  StyleSheet
} from 'react-native';
import {
  Container,
  Header,
  Title,
  Body,
  Icon,
  Tabs,
  Tab,
  TabHeading,
  Item,
  Input,
  Text,
  View
} from 'native-base';

class App extends React.Component {
  constructor (props) {
    super(props);

    this.state = {
      isReady: false
    };
  }

  async componentWillMount() {
    if (Platform.OS === 'android') {
      await Exponent.Font.loadAsync({
        'Roboto': require('native-base/Fonts/Roboto.ttf'),
        'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf')
      });

      this.setState({
        isReady: true
      });
    }
  }

  render() {
    if (!this.state.isReady) {
      return <Exponent.Components.AppLoading />;
    }

    return (
      <Container style={{ flex: 1 }}>
        <Header hasTabs>
          <Body>
            <Title style={{ alignSelf: 'stretch' }}>Test</Title>
          </Body>
        </Header>
        <Tabs tabBarPosition='bottom'>
          <Tab heading={ <TabHeading><Icon name="md-people" /></TabHeading> }>
            <View style={{ padding: 20 }}>
              <Text>Tab1 contents</Text>
              <Item regular>
                <Input placeholder='Enter text...' />
              </Item>
            </View>
          </Tab>
          <Tab heading={ <TabHeading><Icon name="md-chatboxes" /></TabHeading> }>
            <Text>Tab2 contents</Text>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}

Exponent.registerRootComponent(App);
```

## The screenshots
![screenshot1](https://cloud.githubusercontent.com/assets/25953890/23213378/637fc99a-f913-11e6-85bb-ffd6f84374cd.png)
![screenshot2](https://cloud.githubusercontent.com/assets/25953890/23213396/6bd1da0c-f913-11e6-838b-d0e1370f7734.png)

## The device
I have tested the project only on Android.

**Comment by shivrajkumar** [comment] 2017-03-15 13:08
@alexn777 This seems to be fixed in the newer version

**Comment by alexn777** [comment] 2017-03-15 13:42
I have just checked it with native-base 2.0.12. The issue still exists.

**Comment by shivrajkumar** [comment] 2017-03-15 14:11
![tab issue](https://cloud.githubusercontent.com/assets/17001305/23952366/4bc5ab76-09b7-11e7-9d83-e2772afc383a.gif)
@alexn777 Works the same for android as well.

**Comment by shivrajkumar** [comment] 2017-03-15 14:13
If you had ejected the theme, you need to eject again and merge

**Comment by alexn777** [comment] 2017-03-15 18:29
I did not eject the theme. You can check the code I initially posted. Here is how it works for me now:
![test project](https://cloud.githubusercontent.com/assets/25953890/23964675/f88d5b3c-09bd-11e7-81a6-5f007c4ee914.gif)

**Comment by jjsaguit** [comment] 2017-05-06 17:21
Any updates on this? I'm having this problem and there is no work around

**Comment by realfresh** [comment] 2017-07-25 23:54
Having this issue as well

**Comment by matejstrasek** [comment] 2017-10-23 07:41
Is there any solution for this already? 🤔

**Comment by jaded-Viper** [comment] 2018-05-05 13:14
This seems to be getting worse.  I have two Text Inputs side by side.  when focus on the left input it causes the tab to scroll slightly but when you focus on the right input the whole tab scrolls 50% to the next screen and the keyboard will not pop up.  Is there any fix for this on the horizon?

**Comment by Frans-L** [comment] 2018-08-14 14:47
A dirty fix, which I have used, is to wrap \<Content\> with fixed height around \<Tabs\>.

```
<Content contentContainerStyle={{ height: 200 }} >
  <Tabs>
    ....
  </Tabs>
</Content>
```

Has anyone found a proper fix?

**Comment by XeCtvi** [comment] 2018-08-24 06:53
Hi @Frans-L ,

The fix doesn't work for me, still waiting for a solution for this issue.

Thanks.

**Comment by sharanrprasad** [comment] 2018-10-29 23:54
Issue still exists for me in version 2.7.2. Any fix yet?

**Comment by suvenduchhatoi** [comment] 2018-12-21 11:02
@alexn777 @realfresh @matejstrasek @jaded-Viper @Frans-L @XeCtvi @sharanrprasad 
Plz check. The issue seems to have been fixed in the latest native-base version(2.9 released)...And also check your "react-native" version compatibility with "native-base"...Hopefully, the following code should show the expected behaviour...
```
import React, { Component } from "react";
import {
  View,
  Container,
  Header,
  Body,
  Title,
  Tabs,
  Tab,
  TabHeading,
  Icon,
  Item,
  Text,
  Input,
} from "native-base";

export default class BoldAndBeautiful extends Component {
  render() {
    return (
      <Container style={{ flex: 1 }}>
        <Header hasTabs>
          <Body>
            <Title style={{ alignSelf: "stretch" }}>Test</Title>
          </Body>
        </Header>
        <Tabs tabBasrPosition="bottom">
          <Tab
            heading={
              <TabHeading>
                <Icon name="ios-menu" />
              </TabHeading>
            }
          >
            <View style={{ padding: 20 }}>
              <Text>Tab1 Content</Text>
              <Item regular>
                <Input placeholder="Enter text..." />
              </Item>
            </View>
          </Tab>
          <Tab
            heading={
              <TabHeading>
                <Icon name="ios-home" />
              </TabHeading>
            }
          >
            <Text>Tab2 content</Text>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}
```

**Comment by suvenduchhatoi** [comment] 2018-12-21 11:05
![screenshot 2018-12-21 at 4 35 10 pm](https://user-images.githubusercontent.com/44160581/50339820-6f01a200-053e-11e9-98e3-d369f9d4b9b0.png)

**Comment by XeCtvi** [comment] 2018-12-23 11:58
Hi @suvenduchhatoi ,

Thanks for your suggestion, I will have a try on it.

**Closed** 2018-12-24 12:51 UTC
Labels: awaiting response

**Comment by lalitkhedkar** [comment] 2019-05-29 15:18
Hi @suvenduchhatoi ,I am also having the issue while typing in tabs..here is my package.json
![image](https://user-images.githubusercontent.com/38528864/58569061-06d48c00-8253-11e9-9004-52712ec1f699.png)

**Comment by AlirezaAzizi145** [comment] 2019-09-02 09:14
still i have this problem

**Comment by AlirezaAzizi145** [comment] 2019-09-02 09:15
but on some android mobiles for example nexus 5 with android 6.0.0
