### ISSUE TITLE
Dynamic Item List of Picker are throwing exception on iOS (working with warnings on Android)

### ISSUE THREAD

**Issue by chetnadaffodil** [GeekyAnts/NativeBase#341] opened 2016-12-05 16:07 UTC
Hi

This is my code to render items dynamically. The state "states" is a non empty array of states with properties.
But it's throwing an exception. 

![screen shot 2016-12-05 at 5 27 45 pm](https://cloud.githubusercontent.com/assets/17562095/20884214/ebf6707c-bb0f-11e6-99fe-b4aeecf8b710.png)
![screen shot 2016-12-05 at 1 11 21 pm]
(https://cloud.githubusercontent.com/assets/17562095/20884234/fff0aa34-bb0f-11e6-9eca-52c75b7fdc6d.png)

**Comment by palmsey** [comment] 2016-12-16 15:53
I think this is a duplicate of #314

**Closed** 2016-12-28 11:26 UTC
Labels: bug, duplicate

**Comment by westcode** [comment] 2016-12-28 12:09
Hi @sankhadeeproy007 is this resolved?

**Comment by amitbravo** [comment] 2017-04-24 18:57
constructor(props) {
  super(props);
  this.state = {
    categories: null,
    categoryActive: '1',
  }
}

//getting categories list from http request or asyncstorage

updateDropdown(){
      const self = this;
      const all_items = self.state.categories.map((category, i) => {
        return (
            <PickerItem key={i} label={category.cat_name} value={category.cat_id} />
          )
       });
       return all_items;
}



render(){
    return (
            <Container>
               <Content>
              { this.state.categories != null && this.state.categories.length>1 ?
              <Picker
                  iosHeader="Select one"
                  mode="dropdown"
                  selectedValue={this.state.categoryActive}
                  onValueChange={this.onValueChange.bind(this)}>
                    {this.updateDropdown()}
             </Picker> : <View />
             }

             </Content>
             </Container>
            );
}

**Comment by amitbravo** [comment] 2017-04-24 18:58
`constructor(props) {
  super(props);
  this.state = {
    categories: null,
    categoryActive: '1',
  }
}

//getting categories list from http request or asyncstorage

updateDropdown(){
      const self = this;
      const all_items = self.state.categories.map((category, i) => {
        return (
            <PickerItem key={i} label={category.cat_name} value={category.cat_id} />
          )
       });
       return all_items;
}



render(){
    return (
            <Container>
               <Content>
              { this.state.categories != null && this.state.categories.length>1 ?
              <Picker
                  iosHeader="Select one"
                  mode="dropdown"
                  selectedValue={this.state.categoryActive}
                  onValueChange={this.onValueChange.bind(this)}>
                    {this.updateDropdown()}
             </Picker> : <View />
             }
</Content>
             </Container>
            );
}         
          `

**Comment by amitbravo** [comment] 2017-04-24 19:02
```
constructor(props) {
  super(props);
  this.state = {
    categories: null,
    categoryActive: '1',
  }
}
//getting categories list from http request or asyncstorage
updateDropdown(){
      const self = this;
      const all_items = self.state.categories.map((category, i) => {
        return (
            <PickerItem key={i} label={category.cat_name} value={category.cat_id} />
          )
       });
       return all_items;
}
render(){
    return (
            <Container>
               <Content>
              { this.state.categories != null && this.state.categories.length>1 ?
              <Picker
                  iosHeader="Select one"
                  mode="dropdown"
                  selectedValue={this.state.categoryActive}
                  onValueChange={this.onValueChange.bind(this)}>
                    {this.updateDropdown()}
             </Picker> : <View />
             }
             </Content>
             </Container>
            );
}
```
