### ISSUE TITLE
ListItem style padding not working

### ISSUE THREAD

**Issue by jannikbuschke** [GeekyAnts/NativeBase#2917] opened 2019-09-04 18:58 UTC
I expected this code to work:
```
<ListItem style={{padding: 0}}>....
```

However it doesnt seem to have any effect. Should this be supported?

I also tried setting the height, it works. However I cannot use it as some of my items have larger content and its difficult to calculate the exact height. Setting the padding would solve my problem neatly.

**Comment by sankhadeeproy007** [comment] 2019-09-05 06:25
Hey, thanks for the report!
Can you please add a minimal snack reproduction so that I can test it out?

**Comment by jannikbuschke** [comment] 2019-09-05 07:45
https://snack.expo.io/@yyannekk/laughing-cashew

**Comment by sankhadeeproy007** [comment] 2019-09-06 03:58
Fixed it here
https://snack.expo.io/ryXWtIJUH
Currently it only works when we specifically mention the directions where we want the margin/padding. ie `paddingTop: 0`.
Working on a fix for this.

**Closed** 2020-12-28 15:14 UTC
Labels: bug, wontfix

**Comment by Kolyunya** [comment] 2021-01-12 13:42
Can this be reopened? I can confirm the issue is still present in `2.15`.
