### ISSUE TITLE
Error setting Content contentContainerStyle

### ISSUE THREAD

**Issue by L3V147H4N** [GeekyAnts/NativeBase#434] opened 2017-01-17 20:17 UTC
react-native 0.40
native-base 0.5.21

When using the contentContainerStyle property of Content I get:

`you attempted to set the key padding with the value 0 on an object that is meant to be immutable and hes been frozen.
`

whenever I transition out of the view or activating a Fab button inside the Content

example code:

```jsx
const styles = {
  content: {
    backgroundColor: 'white',
    flex: 1
  },
  contentContainer: {
    flex: 1
  }
};

<Content
          style={content}
          contentContainerStyle={contentContainer} >
          <ScrollView>
            {
              order ?
                <Card>
                  <CardItem>
                    <Icon name={`md-${order.icon}`} style={{ color: '#DD5044', fontSize: 48 }} />
                    <Text>{order.client}</Text>
                    <Text note>{order.address}</Text>
                  </CardItem>
                  <CardItem header>
                    <Text>Detalles</Text>
                  </CardItem>
                </Card> : null
            }
          </ScrollView>

          <Fab
            active={active}
            direction="up"
            containerStyle={{ marginLeft: 10 }}
            style={{ backgroundColor: '#5067FF' }}
            position="bottomRight"
            onPress={() => this.setState({ active: !this.state.active })}
          >
            <Icon name="md-add" />
            <Button style={{ backgroundColor: '#34A34F' }}>
              <Icon name="logo-whatsapp" />
            </Button>
            <Button style={{ backgroundColor: '#3B5998' }}>
              <Icon name="logo-facebook" />
            </Button>
            <Button disabled style={{ backgroundColor: '#DD5144' }}>
              <Icon name="ios-mail" />
            </Button>
          </Fab>
        </Content>
```

If I remove the contentContainerStyle property it works fine but the Content doesn't cover the entire screen

**Comment by L3V147H4N** [comment] 2017-01-17 20:30
I discovered the error by looking in:
https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Content/index.js#L38

Content is attempting to assign .padding to contentContainerStyle object, but when passed down as an object is frozen:

so I had to do:

```
<Content
          style={content}
          contentContainerStyle={{
            flex: 1
          }} >
```

**Comment by sankhadeeproy007** [comment] 2017-01-18 06:36
Yes, this is a known bug as of now and will be fixed in the future release. It's also a duplicate of #227, so let's track it there.

**Closed by sankhadeeproy007** 2017-01-18 06:36 UTC

**Comment by L3V147H4N** [comment] 2017-01-18 14:59
thx, sorry for the duplicate, I did search for issues related to 'contentContainerStyle' but nothing came up on the search
