### ISSUE TITLE
Problem with list in tabs

### ISSUE THREAD

**Issue by gperdomor** [GeekyAnts/NativeBase#221] opened 2016-10-05 16:04 UTC
Hi, i have two tabs and each one render a List, the initial tab shows all the elements, but when i switch to the second one, is empty but when i scroll shows all the elements.

**Comment by SupriyaKalghatgi** [comment] 2016-10-06 06:06
I tried the same example from docs of NativeBase and included two separate lists for tabs.
This works fine for me.
![tabs](https://cloud.githubusercontent.com/assets/13464885/19142155/f62e0932-8bb8-11e6-86e9-d297acdf9625.gif)

**Comment by gperdomor** [comment] 2016-10-06 14:57
The main view is:
 ```
<Container theme={myTheme} style={styles.container}>
    <Header>
        <Button transparent onPress={this.props.openDrawer}>
            <Icon name="ios-menu"/>
        </Button>
        <Title>ZBox Now</Title>
    </Header>
    <View style={{flex:1}}>
        <Tabs>
            <Tab1 tabLabel="Tab 1" I18n={I18n}/>
            <Tab2 tabLabel="Tab 2" I18n={I18n}/>
        </Tabs>
    </View>
</Container>
```

And Tab1 and Tab2 are simple List...
```
<List dataArray={items} renderRow={this.renderRow}/>
```

**Comment by mynameisnoise** [comment] 2016-10-21 11:52
I have the same issue.
Looks that this is happening only with dynamic lists. But I had found solution for me.

Here is some code samples.
I have issue with next code:
`<Container>
    <Content>
        <Tabs>
            <TabOne tabLabel="One" />
            <TabTwo tabLabel="Two" />
        </Tabs>
    </Content>
</Container>`

But if a change <Content> to <View> then two lists are rendered correctly.

Code for TabOne and TabTwo is next:
`<Content>
    <List
        dataArray={items}
        renderRow={(item) => (
            <ListItem>
                <Text>{item}</Text>
            </ListItem>
        )}
    />
</Content>`

**Comment by fbacker** [comment] 2016-10-24 09:57
Same issue here with dynamic list, is there a way to force re-render maybe? When scrolling the list the content suddenly appears.

**Comment by mynameisnoise** [comment] 2016-10-24 10:32
I do not know, will it suit anyone else, but I had done next thing to solve this problem:

`_listRow(item)
{
    return (<ListItem key={item.id}>
        <Text>{item.title}</Text>
    </ListItem>);
}

render()
{
    var listItems = [];
    for (var item of this.state.items) {
        listItems.push(this._listRow(item));
    }

    <ScrollView style={{flex: 1}}>
        <List>
            {listItems}
        </List>
    </ScrollView>
}`

**Comment by fbacker** [comment] 2016-10-24 11:03
That worked for me as well.

**Comment by kiranruth** [comment] 2016-11-08 12:49
Any fix for this ?
TIA

**Comment by SupriyaKalghatgi** [comment] 2016-11-17 07:33
NativeBase Tabs worked fine for me with Dynamic Lists

```
render() { // eslint-disable-line

    const items = [
      'Simon Mignolet',
      'Nathaniel Clyne',
      'Dejan Lovren',
      'Mama Sakho',
      'Emre Can',
    ];

    return (
      <Container style={styles.container}>
        <Content padder>
          <List
            dataArray={items}
            renderRow={item =>
              <ListItem>
                <Text>{item}</Text>
              </ListItem>
            }
          />
        </Content>
      </Container>
    );
  }
```

**Comment by mynameisnoise** [comment] 2016-11-17 07:46
@SupriyaKalghatgi, your code is not dynamic list.
dynamic is all about built-in `ListView` object.

`this.state.list = filters: new ListView.DataSource({
            rowHasChanged: (row1, row2) => true
        });`

`this.setState({
                    list: this.state.list.cloneWithRows(responsen.list)
                })`

**Comment by SupriyaKalghatgi** [comment] 2016-11-18 13:51
NativeBase does not support Dynamic Data in Picker (ListView.DataSource)

This will be up within the upcoming release

**Comment by mynameisnoise** [comment] 2016-11-18 14:05
@SupriyaKalghatgi, are you serious?
we are talking here about **TABS**. and **TABS** do not display react-native built-in components correctly.
* or your comment means, that inside nativebase components we are allowed to use only nativebase "supported" components?
* or cause nativebase heavily uses a bunch of another libraries, you just can't tell where exactly is the problem?

**Comment by kiranruth** [comment] 2016-11-18 14:17
@SupriyaKalghatgi  and @mynameisnoise 

Strangely setting the width for the List seems to work
 
`style={{width: Dimensions.get('window').width}}`

So far i've set `removeClippedSubviews={false}` to get this working.

Lists in Tabs are still a issue. I think it only makes sense to keep this issue open until an exact fix is found. 

That or club all list inside tab issues into one.

**Comment by SupriyaKalghatgi** [comment] 2016-11-18 14:18
@mynameisnoise NativeBase is being re-written to solve the issues that you listed.

And NativeBase components will use other custom components as well

**Comment by gody** [comment] 2017-02-24 19:51
Have the same issue and @kiranruth solutions work for me!

**Comment by vzhen** [comment] 2017-03-28 05:43
Have the same issue, I am using tabs as well. It works before but suddenlly list view empty.

**Comment by Slooowpoke** [comment] 2017-06-08 13:16
@SupriyaKalghatgi This issue still persists in version 2.1.4 with RN 0.44.2.

Odly enough, the list is only blank if it is the first list loaded. Eg: populate both lists dynamically, if you are on the first tab, the second tab's list will load fine, and vice versa for the other order.

Perhaps this is sorted in .45 of RN? But I doubt it. Maybe I am missing new documentation for tabs?

**Comment by sankhadeeproy007** [comment] 2017-06-08 13:27
Has anyone tried out [this](https://github.com/GeekyAnts/NativeBase/issues/131#issuecomment-241969326) solution?

**Comment by Slooowpoke** [comment] 2017-06-08 13:41
Just tried this again to be thorough, both lists have this property already. 

To clarify, the List holds a View, then a ListItem with another View inside. Not sure if that helps at all. The list does load, but only the second tab that is navigated to.

**Comment by shivrajkumar** [comment] 2017-06-29 06:57
@vzhen @Slooowpoke We are not able to reproduce the issue on our side.
It will be easier if you could setup a repo with the issue or post code snippets along with the screenshots/gif to help us resolve the issue.

**Comment by shivrajkumar** [comment] 2017-07-26 12:19
Closing this due to inactivity. Let us know if you are still facing the issue

**Comment by krishnazden** [comment] 2017-07-27 11:55
@shivrajkumar,  The problem still exists, In Tabs, if I use dynamic lists, the list is not scrollable, If I remove tabs, It is scrollable then. 
Above mentioned solution doesn't work either. Please, reopen the case.

**Comment by shivrajkumar** [comment] 2017-07-27 12:00
@krishnazden We are not able to reproduce this issue on our end. Can you just setup a repo with this issue

**Comment by krishnazden** [comment] 2017-07-27 12:35
@shivrajkumar 

![tab-issue](https://user-images.githubusercontent.com/13718622/28670364-f1c94346-72f5-11e7-8ec9-a0d478b6f461.gif)
Thanks...resolved it.. by removing extra parent views such as content tag

**Comment by mgit7** [comment] 2017-09-07 08:07
> @SupriyaKalghatgi This issue still persists in version 2.1.4 with RN 0.44.2.

Odly enough, the list is only blank if it is the first list loaded. Eg: populate both lists dynamically, if you are on the first tab, the second tab's list will load fine, and vice versa for the other order.

Perhaps this is sorted in .45 of RN? But I doubt it. Maybe I am missing new documentation for tabs?

I am having this same problem. I am just using .map to display a list of components and it does not  populate if I set "initialpage={1}" only when I swipe to a different index and back it will populate the items. Only started happening after updating native base and react native.

package.json
----------------
"reat-native":"^0.48.1"
"native-base": "^2.3.1",

**Closed** 2017-11-07 12:32 UTC
Labels: can't reproduce, high priority
