### ISSUE TITLE
Icons not showing after upgrade to 0.60

### ISSUE THREAD

**Issue by shardick** [GeekyAnts/NativeBase#2927] opened 2019-09-15 20:13 UTC
I'm trying to use FontAwesome5 in my app instead of MaterialIcons (after last update i receive a huge quantity of warnings to refactor completely the app so i wanted to get the moment to switch to FontAwesome5).

But doesnt work.

I can use FontAwesome5 icon sets only specifying explicitly the type="FontAwesome5" in icons but not setting it from iconFamily in theme variable.

I tried to:
- copy manually all fonts from react-native-vector-icons to assets/fonts in Android
- add apply from: "../../node_modules/react-native-vector-icons/fonts.gradle" in android/app/build.gradle
- install explicitly react-native-vector-icons and link them with react-native link
- clean the build
- rebuild a lot of times
- try to debug with console.log and console.warn to check if iconFamily prop was setted correctly.

No way.

Android 9 Emulator
"native-base": "^2.13.8",
"react": "16.8.6",
"react-native": "0.60.0",
"react-native-vector-icons": "^6.6.0"

Please help

**Comment by tmaly1980** [comment] 2019-09-16 20:09
I'm experiencing the same thing too! Perhaps the theme files have changed dramatically? I'll try using the default (with the icon font changed) and report back.

**Comment by tmaly1980** [comment] 2019-09-16 20:46
https://github.com/GeekyAnts/NativeBase/pull/2924

**Comment by jramalho** [comment] 2019-09-17 14:18
So actually you need to especify the Type of the icon to use the Icon component (like materialCommunityIcons, FontAwesome and stuff), like NativeBase ignores your theme. That's easy doe, but the problem is using an icon on an actionSheet

**Comment by tmaly1980** [comment] 2019-09-17 14:20
@jramalho Honestly I just gave up with NativeBase and am using react-native-vector-icons directly. I ended up writing a very simple custom icon component to wrap some sensible defaults (size).

**Comment by jramalho** [comment] 2019-09-17 14:52
@tmaly1980 I wish i had the same luck, our project heavily rely on NativeBase haha.

**Comment by tmaly1980** [comment] 2019-09-17 14:53
@jramalho I'm still using NativeBase for everything else. It is just wrapping react-native-vector-icons anyway! Nothing is stopping you from using it directly.

**Comment by jramalho** [comment] 2019-09-17 16:40
@tmaly1980 Thanks for the suggestion, gonna try that.

**Comment by shardick** [comment] 2019-09-17 17:41
@jramalho true. but it's a stupid bug, I think and should be fixed

**Comment by xstable** [comment] 2019-09-25 11:37
Had the same issue after upgrading to 0.60.5.
Adding `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"` in `/app/build.gradle` worked for me.

**Comment by kerimkuscu** [comment] 2019-10-02 05:11
See here 
[](https://docs.nativebase.io/Components.html#icon-def-headref)

**Comment by ale-ishizawa** [comment] 2020-01-17 14:46
@xstable it works.

**Comment by hanykumar** [comment] 2020-09-18 12:58
Hi, please update Native-Base with latest v2.13.14 and let us know if the issue still persists by providing minimal code reproduction. Closing for now.

**Closed by hanykumar** 2020-09-18 12:58 UTC

**Comment by tree1891** [comment] 2020-11-17 05:45
not work  with v2.13.14

**Comment by tomvrampio** [comment] 2020-11-24 16:53
Can't use 2.13.14 as it has a breaking build error in web. Looking forward to the next release
