### ISSUE TITLE
Box height jumping around

### ISSUE THREAD

**Issue by stacey-gammon** [GeekyAnts/NativeBase#3948] opened 2021-08-12 20:21 UTC
I am able to reproduce this right in the examples shown on https://docs.nativebase.io/box.

Height set to 20:
<img width="790" alt="Screen Shot 2021-08-12 at 4 18 12 PM" src="https://user-images.githubusercontent.com/16563603/129264064-0fbce4cc-c76b-4023-b6c7-8e23cf9fde06.png">

Height set to 19, much smaller!
<img width="818" alt="Screen Shot 2021-08-12 at 4 18 18 PM" src="https://user-images.githubusercontent.com/16563603/129264062-ab51218f-914d-4f28-8ee6-20044e54c48e.png">

Height set to 40, okay looks twice that of 20 about
<img width="828" alt="Screen Shot 2021-08-12 at 4 18 51 PM" src="https://user-images.githubusercontent.com/16563603/129264058-f963d0fb-2735-4956-bdae-dee1bcd240e6.png">

Height set to 30. Huh?? Shorter than 20.
<img width="832" alt="Screen Shot 2021-08-12 at 4 18 40 PM" src="https://user-images.githubusercontent.com/16563603/129264061-4502f830-0936-4b2c-8dfb-e981f2724fab.png">

Am I missing something about this property? Shouldn't it be treated as a pixel value?

**Comment by rayan1810** [comment] 2021-08-13 05:17
@stacey-gammon Hey, please have a look at https://docs.nativebase.io/design-tokens this is not a bug it's an intended behaviour. I'm closing this issue feel free to reopen if required.

**Closed** 2021-08-13 05:18 UTC
Labels: v3
