### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by pablohpsilva** [GeekyAnts/NativeBase#3997] opened 2021-08-26 16:59 UTC
**Describe the bug**
I'm using native-base + nextjs.
```
{[...Array(10).keys()].map((_, i) => 
    <Image
        key={`image-${i}`}
        source={{
          uri: imgSource,
        }}
        resizeMode="cover"
        height={{
          base: 220,
          sm: 210,
          md: 220,
          lg: 250,
          xlg: 250,
        }}
        width={{
          base: 155,
          sm: 145,
          md: 155,
          lg: 185,
          xlg: 185,
        }}
      />
}
```

The bug is the following:
* If you start your build or refresh your browser, I always get the height 250 and width 250;
* If I remove the `xlg` and refresh the page, the default height is 220 and width 155 (base value), no matter what screen I check (iphone size, for example), the `lg, md, and sm` sizes are being ignored;
* If I put back the `xlg` and remove the `base`, then the value is height 250 and width 250, no matter what screen I check (iphone size, for example), the `lg, md, and sm` sizes are being ignored;

Overall: responsive breakpoints are not working. `sm` size is not enough for iphone display size.

**OBS**.: `useMediaQuery` has the very same problem on SSR

**Platform**

node: v16.5.0
npm: v7.20.0
yarn: v1.22.10
"native-base": "^3.0.7",
"next": "latest",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-native-safe-area-context": "^3.3.0",
"react-native-svg": "^12.1.1",
"react-native-web": "^0.17.1",
"styled-components": "^5.3.0",
"styled-system": "^5.1.5"

**Comment by georgii-ivanov** [comment] 2021-09-10 23:00
Any progress there?
It would be nice to generate a separate style with a real media queries for web specifically.

**Comment by georgii-ivanov** [comment] 2021-09-10 23:26
https://www.npmjs.com/package/react-native-media-query

That might be an option

**Comment by pablohpsilva** [comment] 2021-09-11 06:40
I've decided to stick with `native-base@3.0.0` for now. The responsiveness is much better and the latest version has nothing extra that's impacting me right now.

@georgii-ivanov I was also using this: [use-breakpoint](https://github.com/wintercounter/use-breakpoint). It was flawless. But then I decided to move to native-base@3.0.0 and I use whatever they provide.

**Comment by cereallarceny** [comment] 2021-12-12 20:15
Wow, this does actually fix a lot of bugs @intergalacticspacehighway. Very surprised by this. Please remember to close this issue once that PR is merged so we can all receive updates to remove your patch. 😄

**Comment by vidhi499** [comment] 2022-01-21 06:13
@kenchoong We fixed the above in the latest release of native-base(3.3.3). We are now implementing the styles using media query, this will also solve the flicker issue caused by forced re render. You can. checkout the implementation [here](https://github.com/GeekyAnts/NativeBase/pull/4495).

**Closed** 2022-01-21 06:13 UTC
Labels: v3

**Comment by marclester-tang** [comment] 2022-05-05 03:30
> @kenchoong Responsive props currently won't work with NextJS or Server side rendering as Reach Native Web currently [doesn't support media-queries](https://github.com/necolas/react-native-web/issues/1688#issuecomment-944628208) in stylesheet so we're relying on RN's dimension API which can't return device dimension on server. We have a [work-in-progress](https://github.com/GeekyAnts/NativeBase/tree/media-query-next) media query implementation for this, that should solve this issue. For now, I'd recommend wrapping your entire app or only responsive styled component with below component.
> 
> ```js
> const ClientOnly = ({children}) => {
>     const [mounted, setMounted] = React.useState(false);
> 
>     React.useEffect({
>         setMounted(true);
>     }, [])
>  
>     return mounted ? children : null;
> }
> ```
> 
> ```js
> // Use it like below
> 
> <NativeBaseProvider>
>     <ClientOnly>
>         <App />
>     </ClientOnly>
> </NativeBaseProvider>
> ```
> 
> I know this is just a workaround for now. Once we've the stable version of [media-query implementation](https://github.com/GeekyAnts/NativeBase/tree/media-query-next) up, this workaround won't be needed. It would be great if RNW supports media-query just for min-width/max-width internally though.

it defeats the purpose of SSR/Nextjs, might as well use CRA
