### ISSUE TITLE
Invariant Violation on debug mode

### ISSUE THREAD

**Issue by el-lsan** [GeekyAnts/NativeBase#2603] opened 2019-02-21 12:59 UTC
## Issue Description
After updating my react-native from `^0.57.8` to `^0.58.5` my app is crashing **only** on **`debug mode`** and throwing following error :

![image](https://user-images.githubusercontent.com/1249548/53170054-5ca7f100-35df-11e9-909b-53ab75ecbbcd.png)

So by digging into my codes I found out that this error is caused by `paddingTop` styling which is applied to `Header` component and once I comment that line, the app doesn't crash but looks ugly 😅.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: `v8.11.4`
react-native: `^0.58.5`
react: `^16.8.2`
native-base: `^2.11.0`

### Expected behaviour
![image](https://user-images.githubusercontent.com/1249548/53169993-32eeca00-35df-11e9-9c4b-34ec425447f4.png)

### Actual behaviour
If I remove `paddingTop` from my header styling:

![image](https://user-images.githubusercontent.com/1249548/53170558-b361fa80-35e0-11e9-8ef4-3dd934127bc2.png)

If I add `paddingTop` to my header styling:

![image](https://user-images.githubusercontent.com/1249548/53170259-fec7d900-35df-11e9-8d8d-59c6b93c56b5.png)

### Steps to reproduce
Try adding `paddingTop:0` to your `Header` component and run your code in debug/staging mode.

### Code snippet
```
render() {
return (
<Header style={styles.header} searchBar rounded>
  <Item>
    <Icon name="ios-search" />
    <Input
      returnKeyType="search"
      placeholder="Search"
    />
  </Item>
</Header>
)

const styles = StyleSheet.create({
  header: {
    backgroundColor: Colors.primary,
    height: 40,
    paddingTop: Platform.OS === 'ios' ? 0 : 30, //!!!! removing this line would fix the "Invariant Violation" error but the stying would be broken
    paddingBottom: Platform.OS === 'ios' ? 0 : 30,
  },
});
```

**Comment by SupriyaKalghatgi** [comment] 2019-02-22 07:00
#2587

**Comment by tplorts** [comment] 2019-03-01 21:08
@SupriyaKalghatgi I don't think this is the same problem as #2587 

I'm getting the same error, and just like @el-lsan I only see it when running on iPhone X **and** the `paddingTop` of Header is set to `0`.

Digging a little into the Header code, I found some this bit that only applies to the paddingTop on iPhone X:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Header.js#L55
```
topPadder = (style.paddingTop ? style.paddingTop : style.padding) + InsetValues.topInset;
```
so, if we supply 0 as the user's paddingTop, that ternary is only checking for truthiness, so 0 makes it use the padding (which in my and @el-lsan 's cases is undefined).  Then it tries to do `undefined + InsetValues.topInset` which is resulting in `NaN`.

This can be easily fixed by checking whether paddingTop is finite rather than truthy:
```
topPadder = (_.isFinite(style.paddingTop) ? style.paddingTop : style.padding) + InsetValues.topInset;
```
(or `Number.isFinite` if you don't want to use lodash there)

**Comment by el-lsan** [comment] 2019-03-02 03:41
@tplorts Thanks for digging into this and make the issue more clear.
I also checked #2587 and other related issues and still it was more like a bug to me.
But since this issue got closed, I ended up changing my component and removing header wrapper to avoid this bug.
Hopefully with the details you provided this issue get reopened again for an upcoming fix.

Cheers 🍻

**Comment by SupriyaKalghatgi** [comment] 2019-03-04 07:57
I want more details on this to fix
Did you try with latest release of NativeBase? If yes, what is the theme you injected in `StyleProvider`?

**Comment by el-lsan** [comment] 2019-03-04 10:39
@SupriyaKalghatgi Yes.
I am using `"native-base": "^2.12.0",` and `material` as my theme.
Here's my theme provider component:

```
import React from 'react';
import { Provider } from 'react-redux';
import { StyleProvider } from 'native-base';
import getTheme from '../../native-base-theme/components';
import material from '../../native-base-theme/variables/material';

const ThemeProvider = ({ store, children }) => (
  <Provider store={store}>
    <StyleProvider style={getTheme(material)}>
      {children}
    </StyleProvider>
  </Provider>
);

export default ThemeProvider;
```

**Comment by SupriyaKalghatgi** [comment] 2019-03-04 11:45
I tried similar use case with iPhone X simulator, couldn't reproduce this issue

**Comment by el-lsan** [comment] 2019-03-04 12:04
@SupriyaKalghatgi Please try this tree from my fork:
https://github.com/el-lsan/NativeBase-KitchenSink/tree/produce-2603

![image](https://user-images.githubusercontent.com/1249548/53732353-fa23e000-3e7d-11e9-84a4-d39bd7b193f4.png)

**Comment by tplorts** [comment] 2019-03-05 00:10
> I tried similar use case with iPhone X simulator, couldn't reproduce this issue

Be sure that in addition to using the iPhone X simulator, you are rendering a `Header` whose style contains `paddingTop: 0`.  @el-lsan 's fork of the kitchen sink app has this so that should give you the error.

**Comment by SupriyaKalghatgi** [comment] 2019-03-05 03:27
> I tried similar use case with iPhone X simulator, couldn't reproduce this issue

This was wrt NativeBase KitchenSink

**Closed** 2019-03-06 08:43 UTC
Labels: awaiting response

**Comment by el-lsan** [comment] 2019-03-06 09:55
@SupriyaKalghatgi why `closed` ?

**Comment by anhhh11** [comment] 2019-04-23 14:22
I must adding condition:
paddingTop: isIos ? -24 : 0
To bypass this error
On  "native-base": "^2.12.1","react-native": "0.59.3"

**Comment by idrakimuhamad** [comment] 2019-05-03 10:29
Still happening in react-native `0.59.5` and native-base `2.12.1`. Its a simply wrong checking as mentioned by @tplorts 

You can negative padding as mentioned by @anhhh11 for a workaround.

**Comment by ilya-bmi** [comment] 2019-06-21 10:04
![image](https://user-images.githubusercontent.com/38156878/59915185-151a6000-942d-11e9-8754-17c7f1617953.png)
Same problem on IOS.

"react-native": "0.59.9",
"react": "16.8.3",
"native-base": "^2.12.0",

Fixed by adding height property to the Header style.

**Comment by aidanw** [comment] 2019-07-24 10:08
`"react-native": "0.60.4",`
`"native-base": "^2.12.2",`

I have this issue.
Nothing I have tried works around it.

**Comment by mikedpid** [comment] 2019-07-27 18:56
same here, "Invariant violation: [587, "RCTView",31,{"flex":1,"height":"<<NaN>>"} is not usable as a native method argument

The issue seems to come from <Panel /> component

**Comment by aidanw** [comment] 2019-07-27 18:58
I have just removed headers for the moment, and will remove NativeBase from my solution going forwards. It has been more trouble than it is worth!

**Comment by mikedpid** [comment] 2019-07-27 19:03
My issue is because of <Panel> component inside a <ListItem> component

**Comment by seunex** [comment] 2019-08-17 21:41
Setting the Height of the Header temporarily fix the problem

`<Header noShadow hasTabs style={{elevation: 0,height: Platform.OS === 'ios' ? 90 : 50}}>`

Hope it helps
https://github.com/GeekyAnts/NativeBase/issues/2837#issuecomment-517241556

**Comment by keshakishore** [comment] 2019-09-11 05:37
> `"react-native": "0.60.4",`
> `"native-base": "^2.12.2",`
> 
> I have this issue.
> Nothing I have tried works around it.

Quick fix:
https://github.com/GeekyAnts/NativeBase/issues/2889#issuecomment-530221294
