### ISSUE TITLE
Native Base Toast problems with mocha testing and native-base-shoutem-theme

### ISSUE THREAD

**Issue by IbraheemAlSaady** [GeekyAnts/NativeBase#1362] opened 2017-11-10 16:09 UTC
I have a react-native app setup with babel and mocha for testing Redux Sagas files.
and I'm importing the Toast from the `native-base` in a separate file and using it to fire toasts from the Sagas.

It's working good when I run the app whether on Emulator or real device.
But when it comes to testing, it throws this error.

```
[my_app_name]/node_modules/native-base-shoutem-theme/index.js:1
(function (exports, require, module, __filename, __dirname) { import connectStyle from './src/connectStyle';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
```

When I add the `ignore` to my `babelrc` file like this
`"ignore": "/node_modules(?!(?:\/|\\)((native-base-shoutem-theme)))/"`

I end up with this error.

![image](https://user-images.githubusercontent.com/14288490/32666721-10efd57a-c641-11e7-9f4f-f187d234cca8.png)

What I ended up doing instead of importing the `Toast` like this
` import { Toast } from 'native-base'`
I'm now doing this
```
let Toast = {
    show: () => {}   
};

if(process.env.NODE_ENV !== 'test')
    Toast = require('native-base').Toast;
```

Which is working for Emulator, device, and testing. But it doesn't really make sense to do it like that.
I put a question on [`stackoverflow`](https://stackoverflow.com/questions/46989860/mocha-with-babel-transpile-3rd-party-dependencies)

## react-native, react and native-base version
```
react-native: 0.50.0
native-base: 2.3.3
react: 16.0.0-alpha.12
```

**Comment by theohdv** [comment] 2017-12-19 14:58
Same problem for me but I think this is a duplicate of #713

**Comment by IbraheemAlSaady** [comment] 2017-12-19 15:25
@theohdv, you're right, but the suggested solution is for jest, not mocha :/

**Comment by SupriyaKalghatgi** [comment] 2018-06-29 07:08
Can someone check this with [2.5.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.0)

**Closed** 2018-07-03 05:29 UTC
Labels: question
