### ISSUE TITLE
Checkbox.Group broken in version 3.3.7, unable to select multiple checkboxes.

### ISSUE THREAD

**Issue by lisimba** [GeekyAnts/NativeBase#4660] opened 2022-02-20 16:24 UTC
### Description

I expected to be able to predictably select/deselect multiple checkboxes within a group

### CodeSandbox/Snack link

https://snack.expo.dev/q7cvmJupH

### Steps to reproduce

1. Go to the Snack link [https://snack.expo.dev/q7cvmJupH](https://snack.expo.dev/q7cvmJupH) 
2. Try to select multiple checkbox items

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

The issue seems to have been introduced somewhere in version 3.3 because if I downgrade to 3.2, the Checkbox group works as expected.

**Comment by exneval** [comment] 2022-02-21 02:56
confirm this issue as well

**Comment by surajahmed** [comment] 2022-02-21 09:51
@lisimba We'll consider this API for `Button` in the next release. Thanks for pointing this out.

**Comment by lisimba** [comment] 2022-02-21 19:58
> @lisimba We'll consider this API for `Button` in the next release.

Hi @surajahmed thanks for the acknowledgment however I’m not sure what you mean by the above; specially the mention of “button”. Are you able to clarify please?

**Comment by surajahmed** [comment] 2022-02-22 10:35
@lisimba My bad! I've sent you the wrong message. We're looking into this issue. It is working with version `3.3.6`. However, in version `3.3.7` it is not working properly. 
Hope to fix this in the coming release.

**Comment by enchorb** [comment] 2022-03-17 03:11
Any ETA on when this is expected to be fixed?

**Comment by Thejeshwar-Reddy** [comment] 2022-03-19 11:48
Facing the same issue in 3.0.7 any ETA on this

**Comment by SikoraKam** [comment] 2022-03-22 11:17
> @lisimba My bad! I've sent you the wrong message. We're looking into this issue. It is working with version `3.3.6`. However, in version `3.3.7` it is not working properly.
> Hope to fix this in the coming release.

Im experiencing this bug also in 3.3.6 which you mentioned as working

**Comment by bobbyrinaldy** [comment] 2022-03-23 09:30
any update for this to be added on next release ?

**Comment by jigneshkapdiya** [comment] 2022-04-07 10:44
![image](https://user-images.githubusercontent.com/8413866/162181496-c40e89f2-54a9-4d39-b371-4d6d1dd7220e.png)
![image](https://user-images.githubusercontent.com/8413866/162181748-9b7dce98-eaa7-4c91-85b4-7131727956e8.png)

Each time I check a new item, onChange returns wrong values

used Version 3.3.10

**Comment by enchorb** [comment] 2022-04-07 11:43
Any update on when this regression will be fixed...blocking production releases.

**Comment by om3** [comment] 2022-04-08 12:25
Hi, I have the same bug... Checkbox aren't marked in multiples.

**Comment by Viraj-10** [comment] 2022-04-08 12:34
Hi everyone, Thanks for your active participation. We are looking into this issue. for unknown reasons, this issue is coming into production. bear with us while we solve this bug. 
PS:- CheckBox Group is working in `V3.3.6`.

**Comment by draggie** [comment] 2022-04-08 15:04
> Hi everyone, Thanks for your active participation. We are looking into this issue. for unknown reasons, this issue is coming into production. bear with us while we solve this bug. PS:- CheckBox Group is working in `V3.3.6`.

In our case it was true some time ago, but since ~2 weeks this version is broken as well, therefore it might be some 3rd party dependency that has changed. Even building app in completely cleared env with directly set **3.3.6** it still presents the same behaviour

**Comment by ricohumme** [comment] 2022-04-11 09:31
I noticed that when I created a snack example, the code is working as expected, but when running it in my own environment (with 3.3.6) it's not working and behaving like 3.3.7.
I did the following to achieve the expected result for using 3.3.6:
```
rm yarn.lock
rm -rf node_modules
yarn cache clean
yarn
rm -rf /tmp/metro-cache
yarn web
```
Seeing my yarn.lock file after that, tells me 3.3.6 is installed. however, the effect it is showing me isn't

**Comment by Viraj-10** [comment] 2022-04-11 12:28
Hi Everone, Thanks for being patient. This issue has been resolved in the latest version of NativeBase `V3.3.12`.

**Closed by Viraj-10** 2022-04-11 12:28 UTC
Labels: bug, high priority, v3, triage

**Comment by ricohumme** [comment] 2022-04-11 13:23
Like a charm. Thanks !

**Comment by guidoabelleira** [comment] 2022-10-31 16:46
I have the same problem in "native-base": "^3.4.6".

Tengo el mismo problema en "native-base": "^3.4.6".

**Comment by HelioDantas** [comment] 2023-06-16 17:36
Estou com o mesmo problema em "native-base": "^3.4.26".

Tengo o mesmo problema em "native-base": "^3.4.26".

**Comment by kokosky93** [comment] 2023-08-08 15:37
same issue - "native-base": "~3.4.28",
