### ISSUE TITLE
Error styling using StyleSheet for Label component

### ISSUE THREAD

**Issue by yofriadi** [GeekyAnts/NativeBase#1687] opened 2018-03-13 17:46 UTC
package version : 
  * react : 16.2.0
  * react-native : 0.52.0
  * native-base : ^2.3.10

when I create style with StyleSheet in Label component it throws : 
**TypeError: in this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.**
but if I use inline styling it just fine.

**Comment by akhil-geekyants** [comment] 2018-03-14 07:08
@yofriadi unable to reproduce. Attaching a gif.

Gif

![label](https://user-images.githubusercontent.com/27768184/37387946-81222f38-2784-11e8-835d-e4f35b243eb1.gif)

**Comment by yofriadi** [comment] 2018-03-14 11:54
@akhil-geekyants here the gif of mine. it will error after I clicked on it.
![deepin-screen-recorder_desktop_20180314185155](https://user-images.githubusercontent.com/24536844/37400968-280ccce8-27b9-11e8-94c3-706ea0876d4e.gif)

**Comment by SupriyaKalghatgi** [comment] 2018-03-27 10:06
Fixed with [2.4.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.1)

**Closed by SupriyaKalghatgi** 2018-03-27 10:06 UTC
Labels: bug
