### ISSUE TITLE
iOS Spinner Styling Not Consistent

### ISSUE THREAD

**Issue by hirvesh** [GeekyAnts/NativeBase#5016] opened 2022-05-14 02:35 UTC
### Description

The Spinner component renders differently on iOS than on web and Android.

### CodeSandbox/Snack link

https://snack.expo.dev/@hirvesh/nativebase-template

### Steps to reproduce

1. Include a spinner component in the blank template, it shows up differently on iOS.

See GIF for current render.
![CleanShot 2022-05-14 at 06 34 32](https://user-images.githubusercontent.com/67500738/168407734-506f1b29-b226-4e67-b120-7a56ffee8e26.gif)

### NativeBase Version

3.4.5

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by rayan1810** [comment] 2022-05-16 08:33
This is the expected behavior since we want to render the native Activity Indicator. if you look closely it's actually different on all the three platforms. Closing this issue since it's not a bug.

**Closed by rayan1810** 2022-05-16 08:33 UTC
Labels: bug, v3, triage

**Comment by hirvesh** [comment] 2022-05-16 13:05
Alright, thanks for clarifying Rayan! However I have one follow up query - setting a size of size={10} does not seem to affect the Spinner size specifically on iOS - is this also expected behaviour?
