### ISSUE TITLE
error on nativebase 2.13.12 and expo 36.0.0 (REACT-NATIVE)

### ISSUE THREAD

**Issue by onurcskun** [GeekyAnts/NativeBase#3100] opened 2020-03-17 10:42 UTC
Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/native-base/dist/src/basic/IconNB.js"

**EDIT**
Downgrading 2.13.8 is an alternative solution:

- `npm i --save-exact native-base@2.13.8`

**Comment by juandav** [comment] 2020-03-17 14:07
I have the same error, what solution is there?

```
node_modules/native-base/dist/src/basic/IconNB.js
Module not found: Can't resolve '@expo/vector-icons/Fontisto' in 'node_modules\native-base\dist\src\basic'
```

**Comment by Gregoirevda** [comment] 2020-03-17 15:23
Same issue here

**Comment by onurcskun** [comment] 2020-03-17 15:25
I did not find a solution for 2.13.12 but just downgraded version to 2.13.8 and its fine

**Comment by Gregoirevda** [comment] 2020-03-17 15:32
`npm i --save-exact native-base@2.13.8` Expo should release a version with that version

**Comment by juandav** [comment] 2020-03-17 16:59
> 
> 
> `npm i --save-exact native-base@2.13.8` Expo should release a version with that version

I can't solve it with this

**Comment by onurcskun** [comment] 2020-03-17 17:01
@juandav try rm -rf node_modules && npm i

**Comment by juandav** [comment] 2020-03-17 17:22
> 
> 
> @juandav try rm -rf node_modules && npm i

TypeError: _utils.ViewPropTypes is undefined on this version

**Comment by juandav** [comment] 2020-03-17 17:32
> 
> 
> @juandav try rm -rf node_modules && npm i

it is not working on the web

**Comment by ceessay** [comment] 2020-03-18 16:54
I am also facing this issues. Downgraded the nativebase version as adivised by @onurcskun , removed node_modules and ran `watchmen watch-de-all` but the issue is still persisting. I am using Expo  SDK 36

**Comment by Hirbod** [comment] 2020-03-18 19:27
I can confirm this too. Nice testing

**Comment by lordjack** [comment] 2020-03-18 23:06
> 
> 
> I did not find a solution for 2.13.12 but just downgraded version to 2.13.8 and its fine

It worked for me too, I downgraded it to 2.13.8. Thanks for the tip @Gregoirevda

**Comment by juandav** [comment] 2020-03-19 03:02
https://github.com/expo/vector-icons/issues/112

**Comment by juandav** [comment] 2020-03-19 03:05
https://github.com/expo/vector-icons/pull/126

**Comment by DavidCorral94** [comment] 2020-03-19 09:58
Same here, using a tab example app generated by `expo` and latest version of `React Native`.

**Comment by hungdangdt** [comment] 2020-03-19 22:06
> `npm i --save-exact native-base@2.13.8` Expo should release a version with that version

It's work for me, thank

**Comment by ZzAth** [comment] 2020-03-21 15:47
> `npm i --save-exact native-base@2.13.8` Expo should release a version with that version

Worked for me

**Comment by Kaushald4** [comment] 2020-03-21 19:25
Actually i have solved this issue on my forked repo of expo vector icons

**Comment by jeanniton-mnr** [comment] 2020-03-23 05:05
> I did not find a solution for 2.13.12 but just downgraded version to 2.13.8 and its fine

it didn't work for me

**Comment by jeanniton-mnr** [comment] 2020-03-23 05:06
> > `npm i --save-exact native-base@2.13.8` Expo should release a version with that version
> 
> Worked for me

what version of expo do you have?

**Comment by jeanniton-mnr** [comment] 2020-03-23 18:58
I had to edit `IconNB.js`  and block comment on the importation of the *icons* from this module.    


**NB: The error I was getting and note also it is a temporary fix:**   
bundling failed: Error: Unable to resolve module `@expo/vector-icons/Fontisto` from `node_modules/native-base/dist/src/basic/IconNB.js` (*file to edit*): @expo/vector-icons/Fontisto could not be found within the project.    

*Cons*:
1. You might have to edit this file at every `npm install`.   
2. You might not be able to use this module, IconNB.js


![Screen Shot 2020-03-23 at 14 55 37](https://user-images.githubusercontent.com/11714176/77352935-6cc85d80-6d16-11ea-9517-cc70a8711879.png)

**Comment by lmisael** [comment] 2020-03-23 22:12
> Same here, using a tab example app generated by `expo` and latest version of `React Native`.
> 
> I managed to solve it with the following steps:
> 
> * `npm uninstall react-native --save`
> * Delete `node_modules` folder
> * `npm i react-native@2.13.8 --save`
> * `npm i`
> 
> Restart Android emulator, restart `expo` (`npm start`), and it works! Thanks @onurcskun!

Apparently, there is no more react-native@2.13.8:

`npm i react-native@2.13.8 --save`
`No matching version found for react-native@2.13.8`

**Comment by onurcskun** [comment] 2020-03-24 01:39
> > Same here, using a tab example app generated by `expo` and latest version of `React Native`.
> > I managed to solve it with the following steps:
> > 
> > * `npm uninstall react-native --save`
> > * Delete `node_modules` folder
> > * `npm i react-native@2.13.8 --save`
> > * `npm i`
> > 
> > Restart Android emulator, restart `expo` (`npm start`), and it works! Thanks @onurcskun!
> 
> Apparently, there is no more react-native@2.13.8:
> 
> `npm i react-native@2.13.8 --save`
> `No matching version found for react-native@2.13.8`

You should install native base 2.13.8 not react native :)

**Comment by onurcskun** [comment] 2020-03-24 01:46
@DavidCorral94 @lmisael  you should install native-base 2.13.8 not react native :)

**Comment by lmisael** [comment] 2020-03-24 02:29
@onurcskun wow, that's right! Thanks. I've just copied the previous code and didn't notice that.

**Comment by akrambichri** [comment] 2020-03-25 04:29
same thing for me

**Comment by tylerc** [comment] 2020-03-25 16:55
I ended up using https://www.npmjs.com/package/patch-package to patch this commit out of the pacakge: https://github.com/GeekyAnts/NativeBase/pull/3091

Also it looks like somebody has already submitted a pull request to Expo, though nobody has merged it yet: https://github.com/expo/vector-icons/pull/126

My patch is here: [native-base+2.13.12.txt](https://github.com/GeekyAnts/NativeBase/files/4382184/native-base%2B2.13.12.txt) You can drop it into `patches/native-base+2.13.12.patch` after setting up `patch-package`

**Comment by Ferkze** [comment] 2020-03-26 10:21
Yarn project? Take this:
`yarn add native-base@2.13.8`

**Comment by robtry** [comment] 2020-03-26 21:53
Add to scripts:
`"postinstall": "cp node_modules/@expo/vector-icons/FontAwesome.js node_modules/@expo/vector-icons/Fontisto.js",`

**Comment by gevinduM** [comment] 2020-03-27 04:02
I had the same problem, native-base": "^2.13.8" worked for me

**Comment by sidXpro** [comment] 2020-03-28 14:41
Actually, Fontisto is not included in @expo/vector-icons in "@expo/vector-icons": "^10.0.6" .
You can see it in "node_modules/@expo/vector-icons/build " directory ,there is no 'Fontisto.js' named file .
But it is required in "node_modules/native-base/dist/src/basic/IconNB.js" 
_

> **So, importing without existence will cause an error**

_
SOLUTION 1. (worked for me) 👍  dependencies {
"@expo/vector-icons": "^10.0.6",
  "native-base": "^2.13.12",
    "expo": "^36.0.2",
    "expo-font": "^8.1.0",
}
Refactor the code or search for '_Fontisto'  in "node_modules/native-base/dist/src/basic/IconNB.js" 
 and comment the lines as shown in figure
Following three lines are of no use and it needs to be commented
//var _Fontisto = require('react-native-vector-icons/Fontisto');
//var _Fontisto2 = _interopRequireDefault(_Fontisto);
 //case 'Fontisto': this.Icon = _Fontisto2.default; break;

![Screenshot (95)](https://user-images.githubusercontent.com/55379965/77825530-e786e380-712f-11ea-9961-ea5816a60c0f.png)
![Screenshot (96)](https://user-images.githubusercontent.com/55379965/77825533-ea81d400-712f-11ea-8a5a-cb2be6032b1c.png)

Though the paths in IconNB.js requires "react-native-vector-icons" but it is taking "expo/vector-icons" . This type of behaviour is shown when you use 

- 'native-base' and 'react-native' together 

- 'expo/vector-icons' and 'react-native-vector-icons' together

**Comment by juandav** [comment] 2020-03-31 00:38
Solution:

With Native-base ```>= v2.13.12```
```
 dependencies {
  "expo": "36.0.2",
  "@expo/vector-icons": "Kaushald4/vector-icons#master",
  "native-base": "2.13.12",
  "react-native": "0.62.0",
  "react-native-web": "0.11.7"
}
```

**Comment by isaacbatst** [comment] 2020-04-03 19:58
Downgrade did it for me.

**Comment by sanjeetCoder** [comment] 2020-04-04 08:18
It worked for me !!!   Just type command

npm i --save-exact native-base@2.13.8

**Comment by iamnader** [comment] 2020-04-06 19:24
This solution everyone is mentioning to downgrade, isn't a real solution.  We need to reverse this commit: https://github.com/GeekyAnts/NativeBase/pull/3091 or we need to understand what other dependencies need updating.

There are bug fixes since 2.13.8 that people need.

**Comment by kpose** [comment] 2020-04-07 09:22
Downgraded from @2.13.12 to @2.13.8 and it works fine. For yarn projects, use

yarn add native-base@2.13.8

**Comment by MateusPaixao** [comment] 2020-04-09 14:55
yarn add native-base@2.13.8

Work for me tks

**Comment by Victor211** [comment] 2020-04-14 23:31
que mucho busque con yarn, ahora lei los comentarios y me funciona a la perfeccion con
yarn add native-base@base2.13.8 
Muchas gracias comunidad!

**Comment by sebastianvz** [comment] 2020-04-20 22:07
> `npm i --save-exact native-base@2.13.8` Expo should release a version with that version

Work for me, thanks  a lot ...

**Comment by aaronhawkey48** [comment] 2020-04-21 23:42
Any update on a solution to the newer version? Proceeding with a downgrade to fix this. Docs should be updated with how long this issue has been open. Spent 3 days trying to figure out what was wrong when trying to install the library for the first time. Doesn't leave a good first impression.

**Comment by theoneit** [comment] 2020-04-25 13:53
npm i --save-exact native-base@2.13.8 works for me too!

**Comment by iamhussy** [comment] 2020-05-09 17:39
> 
> 
> Actually, Fontisto is not included in @expo/vector-icons in "@expo/vector-icons": "^10.0.6" .
> You can see it in "node_modules/@expo/vector-icons/build " directory ,there is no 'Fontisto.js' named file .
> But it is required in "node_modules/native-base/dist/src/basic/IconNB.js"
> _
> 
> > **So, importing without existence will cause an error**
> 
> _
> SOLUTION 1. (worked for me) 👍 dependencies {
> "@expo/vector-icons": "^10.0.6",
> "native-base": "^2.13.12",
> "expo": "^36.0.2",
> "expo-font": "^8.1.0",
> }
> Refactor the code or search for '_Fontisto' in "node_modules/native-base/dist/src/basic/IconNB.js"
> and comment the lines as shown in figure
> Following three lines are of no use and it needs to be commented
> //var _Fontisto = require('react-native-vector-icons/Fontisto');
> //var _Fontisto2 = _interopRequireDefault(_Fontisto);
> //case 'Fontisto': this.Icon = _Fontisto2.default; break;
> 
> ![Screenshot (95)](https://user-images.githubusercontent.com/55379965/77825530-e786e380-712f-11ea-9961-ea5816a60c0f.png)
> ![Screenshot (96)](https://user-images.githubusercontent.com/55379965/77825533-ea81d400-712f-11ea-8a5a-cb2be6032b1c.png)
> 
> Though the paths in IconNB.js requires "react-native-vector-icons" but it is taking "expo/vector-icons" . This type of behaviour is shown when you use
> 
>     * 'native-base' and 'react-native' together
> 
>     * 'expo/vector-icons' and 'react-native-vector-icons' together

Nice Research bro... helped me.. but i preferred downgrading native-base to 12.13.8

**Comment by michelazzam** [comment] 2020-06-25 20:16
What I did after trying several solutions:

> npm uninstall native-base

then whatever case you wanted to proceed with;
In my case I was receiving the error on npm install expo, so I re-run it:
>npm install expo.

and worked fine.

**Comment by shanhuiyang** [comment] 2020-07-31 09:33
OK, let's wait...

**Comment by hanykumar** [comment] 2020-09-14 12:47
Hi, please update NativeBase with the latest version 2.13.14 . Let us know if the issue still persists.

**Comment by FMCorz** [comment] 2020-09-22 13:39
Same problem here.

```
    "expo": "^39.0.0",
    "expo-constants": "~9.2.0",
    "expo-font": "~8.3.0",
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
```

**Comment by midoushitongtong** [comment] 2020-09-25 17:31
Installing this dependency solved my problem
I'm using it `expo 39.0.0`, `native-base 2.13.14`

```
yarn add @expo/vector-icons@10.1.0
or
npm i @expo/vector-icons@10.1.0
```

> we added this font in `@expo/vector-icons@10.1.0` - install it and you will have it now! it's also listed on 
https://github.com/expo/vector-icons/issues/112#issuecomment-602106766

**Closed** 2020-12-21 10:49 UTC
Labels: awaiting response
