### ISSUE TITLE
Drawer outupdated

### ISSUE THREAD

**Issue by senda-dev** [GeekyAnts/NativeBase#3119] opened 2020-04-08 17:45 UTC
>  WARN  Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Drawer

Where can I update the Drawer component?

**Comment by iamnader** [comment] 2020-04-09 21:30
Drawer is still using componentWillReceiveProps and componentWillMount

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Drawer
- node_modules/expo/build/logs/LogSerialization.js:166:14 in _captureConsoleStackTrace
- node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Drawer
- node_modules/expo/build/logs/LogSerialization.js:166:14 in _captureConsoleStackTrace
- node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

```

**Comment by iamnader** [comment] 2020-04-09 21:58
nativebase is using an unsupported drawer component.  I swapped it out for this one: https://github.com/react-native-community/react-native-side-menu

**Comment by senda-dev** [comment] 2020-04-10 09:32
@iamnader thanks for your reply. I also have changed to another drawer (React Navigation Drawer).

**Comment by hanykumar** [comment] 2020-09-09 11:38
Hi @senda-dev , NativeBase Drawer works fine. You can check it out here. Closing for now, let us know if the issue still persists.

<img width="358" alt="Screenshot 2020-09-09 at 5 04 24 PM" src="https://user-images.githubusercontent.com/15860517/92593340-91ad8e80-f2be-11ea-9f69-9c0ff20a6a61.png">

Sidebar.js
```
import React from "react";
import { View, Text } from "native-base";

export default Sidebar = (props) => (
  <View
    style={{
      flex: 1,
      width: "100%",
      backgroundColor: "white",
      height: "100%",
      justifyContent: "center",
    }}
  >
    <Text>Sidebar</Text>
  </View>
);
```

App.js
```
export default class App extends Component {
  constructor(props) {
    super(props);
  }
  closeDrawer = () => {
    this.drawer._root.close();
  };

  openDrawer = () => {
    this.drawer._root.open();
  };

  renderContainer = () => (
    <Root>
      <Container>
        <Header>
          <Right>
            <Button onPress={() => this.openDrawer()}>
              <Text>Menu</Text>
            </Button>
          </Right>
        </Header>
      </Container>
    </Root>
  );

  render() {
    return (
      <Drawer
        ref={(ref) => {
          this.drawer = ref;
        }}
        onClose={() => this.closeDrawer()}
        content={<Sidebar />}
      >
        {this.renderContainer()}
      </Drawer>
    );
  }
}

```

**Closed by hanykumar** 2020-09-09 11:38 UTC

**Comment by iamnader** [comment] 2020-09-09 11:52
Hi @hanykumar, the issue is not about whether it works, but about updating the underlying component so that it doesn't rely on the deprecated React lifecycle methods.  Thanks!

**Comment by hanykumar** [comment] 2020-09-09 12:01
@iamnader , we are working on it. 
Thanks.

**Comment by iamnader** [comment] 2020-09-09 12:11
Thanks for the update

**Comment by stevemer** [comment] 2020-11-19 20:07
Bump: This issue still exists. Please note that you can suppress this warning easily within the Drawer component.

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Comment by fosteruk** [comment] 2020-12-01 12:01
Why was this closed?

**Comment by rhayart** [comment] 2020-12-14 13:29
This issue is still running on the last version. It should be reopen.

**Comment by RimApp** [comment] 2021-01-22 03:13
I tested on the last version and it is still present. Nobody working on it?

**Comment by devanada** [comment] 2021-05-11 10:25
no update on this issue?

**Comment by keesbriggs** [comment] 2021-11-11 21:35
Still an issue
