### ISSUE TITLE
Button text color is black?

### ISSUE THREAD

**Issue by nolan-m** [GeekyAnts/NativeBase#690] opened 2017-03-28 22:18 UTC
I've been using this library for a few weeks and everything looked like the docs.  Now, for some reason the button color has switched to black.  The disabled button is rendering opposite color schemes.  (Grey on false, colored on true).  I didn't change my version so I'm wondering what conflicted with this library to do this.  Anyone had this happen?

```
import {
  Text,
  Button
} from 'native-base';

<Button
    block
    info
    onPress={ this._handleContinuePress }>
<Text>Continue</Text>
</Button>
```

![screen shot 2017-03-28 at 3 17 33 pm](https://cloud.githubusercontent.com/assets/5704672/24430069/b80cc654-13c9-11e7-8ddd-4d0b2783c20c.png)

**Comment by iiitmahesh** [comment] 2017-03-29 15:35
@nolan-m I have same problem !. have you solved this??

**Comment by nolan-m** [comment] 2017-03-29 15:44
@iiitmahesh Nope,  I'm about ready to remove NativeBase and create my own components since I can't figure out why this changed.

**Comment by nimerfarahty** [comment] 2017-03-29 18:06
same issue , waiting feedback

**Comment by nolan-m** [comment] 2017-03-30 00:13
Just noticed the Segment is messed up as well.

![screen shot 2017-03-29 at 5 14 29 pm](https://cloud.githubusercontent.com/assets/5704672/24481977/042af20c-14a3-11e7-9362-d5aba79e458e.png)

**Comment by himanshu-satija** [comment] 2017-03-30 06:42
@nolan-m Which version are you on?

**Comment by nolan-m** [comment] 2017-03-30 15:08
@himanshu-satija 2.1.0

**Comment by nolan-m** [comment] 2017-03-30 15:52
I removed all dependencies to see if something was conflicting, but no luck.

```
  "dependencies": {
    "babel": "^6.23.0",
    "moment": "^2.18.1",
    "native-base": "^2.1.0",
    "react": "15.4.2",
    "react-native": "^0.42.3",
    "react-navigation": "^1.0.0-beta.6",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-plugin-module-resolver": "^2.5.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-native-cli": "^2.0.1",
    "react-test-renderer": "15.4.2"
  },
```

**Comment by nolan-m** [comment] 2017-03-30 16:47
Did some more digging around.  Looked at a demo project that I knew had the correct colors.  Downgraded my versions and this combo seems to work.   Hoping someone with more knowledge of this project can figure out what is conflicting between newer version.

```
    "native-base": "2.0.11",
    "react-native": "0.41.2",
``

**Comment by himanshu-satija** [comment] 2017-03-30 18:13
Try uninstalling and reinstalling native-base (`npm uninstall native-base && npm install native-base`) and see if that fixes your issue. 

If you have ejected native-base theme, try ejecting it again from the latest version.

**Comment by nolan-m** [comment] 2017-03-30 18:35
I did that first and nothing changed.  Have not ejected.

**Comment by himanshu-satija** [comment] 2017-03-31 08:36
@nolan-m I tested this and I can confirm that this is a bug introduced in v2.1.0. Button text looks fine inside Content but gets incorrect style when used without Content. 

It will be fixed in the next version.

**Comment by himanshu-satija** [comment] 2017-03-31 09:49
@nolan-m There was an issue in one of our dependencies which directly gets installed from GitHub. I have fixed it. Uninstalling and reinstalling native-base should fix your issue. 

I know we should ideally release a patch but we'll go with a quick fix for now. Anyone facing this issue ( @nimerfarahty @iiitmahesh ) should run `npm uninstall native-base && npm i native-base`

**Comment by elinlindberg** [comment] 2017-04-04 08:42
himanshu-satija's solution worked for me.

**Comment by mcapodici** [comment] 2017-04-09 05:08
> ` npm uninstall native-base && npm i native-base`

Didn't work for me unfortunately. Anything else to try?

**Comment by himanshu-satija** [comment] 2017-04-13 07:38
@mcapodici Try `npm uninstall native-base @shoutem/theme && npm i native-base` and let me know if it works.

**Comment by mcapodici** [comment] 2017-04-13 08:27
@himanshu-satija thanks for the tip.

That didn't work unfortunately either.

For further information I get this every time I do npm install:

```
npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/theme@0.8.8 requires a peer of react@^15.1.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
```

And this is my package.json:

```
{
  "name": "WhoCanICall",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "immutability-helper": "^2.1.2",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "native-base": "^2.1.1",
    "react": "16.0.0-alpha.6",
    "react-mixin": "^3.0.5",
    "react-native": "0.43.2",
    "react-native-communications": "^2.2.1",
    "react-timer-mixin": "^0.13.3"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by himanshu-satija** [comment] 2017-04-17 13:49
@mcapodici Try with NativeBase v2.1.2. If you had ejected native-base-theme earlier, try ejecting again. 

If you're still facing issues, please post a code snippet.

**Comment by shivrajkumar** [comment] 2017-04-24 05:28
Closing this as the above solution should work.

**Closed** 2017-04-24 05:27 UTC
Labels: awaiting response

**Comment by ChrisLusted** [comment] 2017-04-24 19:25
Not sure if it will help anyone else but realised I had this Issue because I was importing the Text component from` 'react-native'` rather than `'native-base' `

**Comment by ghalex** [comment] 2017-11-07 09:45
I had the same issue on NativeBase v2.3.3 and the work around is to add primary to text:
```
<Button primary>
    <Text primary>Click Me</Text>
</Button>
```

**Comment by troylutton** [comment] 2018-01-09 11:43
Thank @ChrisLusted  that was what fixed it for me!

**Comment by ThomasLabstep** [comment] 2018-03-21 09:24
v2.3.10 here

This is still not working for some reason, and putting primary in Text won't work.

I will try to eject again. Why don't they use the recommended textStyle button prop instead ?

**Comment by akhil-geekyants** [comment] 2018-03-21 09:53
@ThomasLabstep you should import Text from native-base. Attaching a gif.

Gif

![buttontextcolor](https://user-images.githubusercontent.com/27768184/37703384-85ecc0c2-2d1b-11e8-9e8d-6b5e108e96c1.gif)
