### ISSUE TITLE
Accordion: Problems overriding style

### ISSUE THREAD

**Issue by PaulMEDITECH** [GeekyAnts/NativeBase#2378] opened 2018-10-18 18:42 UTC
## Issue Description
Passing 'style' prototype to Accordion component will completely replace the underlying FlatList's style property instead of overriding the individual style properties.

### node, npm, react-native, react and native-base version, expo version if used
react-native: 0.55.4, react: 16.3.1, native-base: 2.7.0
### Expected behaviour
Trying to remove the border for some implementations of the accordion.
### Actual behaviour
The border is always removed for all accordions.
### Steps to reproduce
Here is my implementation of the Accordion component:
`      <Accordion
        dataArray={[{ title, content }]}
        renderHeader={headerRenderer}
        style={type === 'expandcollapse' ? { borderWidth: 0 } : undefined}
        renderContent={this.renderContent}
        expanded={this.props.expanded ? 0 : undefined}
      />
`
  In the process of troubleshooting the issue I found the {...this.props} line towards the bottom of Accordion.js:
`
  render() {
    const variables = this.context.theme
      ? this.context.theme['@@shoutem.theme/themeStyle'].variables
      : variable;
    return (
      <FlatList
        data={this.props.dataArray}
        extraData={this.state}
        style={[
          {
            borderColor: variables.accordionBorderColor,
            borderWidth: variables.borderWidth
          },
          this.props.style
        ]}
        keyExtractor={(item, index) => String(index)}
...
            expandedIcon={this.props.expandedIcon}
            expandedIconStyle={this.props.expandedIconStyle}
          />
        )}
        {...this.props}
      />
    );
  }
}
`
If I comment out the {...this.props} line, the Accordion component works as expected.
I think this line is adding anything in this.props as properties to FlatList which is causing any value in this.props.style to overwrite the FlatList's style property which defeats the use of this.props.style to override individual properties of the FlatList's style.
### Is the bug present in both iOS and Android or in any one of them?
I have only tried it on Android at this point.

**Comment by suvenduchhatoi** [comment] 2018-12-24 11:32
@PaulMEDITECH 
Accordion is designed in such a way that it all its elements should behave homogenously...as like a ListItem within a List...So, if you want to apply different styles to elements of Accordion, you have to use inline styling...

**Comment by suvenduchhatoi** [comment] 2018-12-24 12:01
Closing the issue...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Closed by suvenduchhatoi** 2018-12-24 12:01 UTC
