### ISSUE TITLE
This is why my client says react native sucks

### ISSUE THREAD

**Issue by roma86** [GeekyAnts/NativeBase#1878] opened 2018-05-08 14:14 UTC
Hi! Thanks for huge work for NativeBase!
I understand how hard it is to develop and maintain this framework, but there are some glitches i can not pass by.

I just run `yarn run ios` on freshly downloaded master branch and opened **Header/Icon and Text Buttons**.
![rnb](https://user-images.githubusercontent.com/3889620/39762039-530554de-52e2-11e8-8c21-fc7c39024ef0.jpg)
Did you see how title text aligned in the "back" button? And what is the strange padding size for the right bar button?

I trying to return to react native + Nativebase every 2-3 month, but every time i faces some glitches like this which stops me to use this technology, beside it offer cross platform development. 

The questions for RN developers:
- do you really fix every small similar issue like this by the hand?
- do you really fix every small similar issue like this or you just does not recognise them?
- does your users really enjoy using your applications with such UI full of cracks?

**Comment by andidev** [comment] 2018-05-11 19:06
I must say I'm a bit disappointed myself with the issues with this framework. This issue has already been reported and closed without being fixed, see #1724 . I stopped caring about this issue because I struggled to get #1731 fixed which was not easy. It took three releases to get #1731 fixed. Even though I provided a concrete example of the bug and a hint of what may be wrong the fix was not tested before closing the issue. I really struggled to convince the issue was still there with examples but my examples was never used for testing the fix.
I understand that this is a community project so I cannot expect too much but still this have been a bit too much. One thing that really bothers me though is this project has at the moment 8726 github stars and still almost no other people backed me up on these issues in the core functionality of this framework. And since the development team did not care too much about them I almost felt I was reporting issues caused by incorrect usage.

**Comment by SupriyaKalghatgi** [comment] 2018-05-16 06:28
Check `fix/header` for fix

**Comment by SupriyaKalghatgi** [comment] 2018-05-18 14:02
@roma86 @andidev Fixed with [2.4.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.5)

Check [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink) for updated code

Check [NativeBase Docs Header](https://docs.nativebase.io/Components.html#header-def-headref)

**Closed by SupriyaKalghatgi** 2018-05-18 14:02 UTC

**Comment by SupriyaKalghatgi** [comment] 2018-05-21 06:26
![screen shot 2018-05-15 at 11 05 55 am](https://user-images.githubusercontent.com/13464885/40293278-d6438324-5ced-11e8-8a15-403c3b44f550.png)
![screen shot 2018-05-15 at 11 11 02 am](https://user-images.githubusercontent.com/13464885/40293286-e2a4c286-5ced-11e8-9c28-e76129f08e5c.png)
![screen shot 2018-05-15 at 11 15 28 am](https://user-images.githubusercontent.com/13464885/40293297-ea42e09a-5ced-11e8-977e-87c4f2686c7a.png)
