### ISSUE TITLE
Button.js theme backgroundColor: null crashing on RN 0.59.1 Android NoSuchKey Exception: backgroundColor

### ISSUE THREAD

**Issue by dguillamot** [GeekyAnts/NativeBase#2673] opened 2019-04-19 08:29 UTC
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
RN . 0.59.1 Android.. native-base 2.12.1
### Expected behaviour
Using custom theme via ejectTheme.js should work on iOS and Android. 

### Actual behaviour
Android release crashing with error: NoSuchKeyException backgroundColor when using transparent and/or disabled style for Button.. native-base-theme/components/Button.js has multiple background: null entries.... changing these to background: transparent appears to resolve isssue. 

### Is the bug present in both iOS and Android or in any one of them?
only Android, only release

**Comment by SupriyaKalghatgi** [comment] 2019-04-22 04:51
Need `Steps to reproduce`

**Comment by jmcneese** [comment] 2019-04-22 15:42
@dguillamot if you change any `backgroundColor: null` to `backgroundColor: 'transparent'`, it fixes the issue

**Comment by SupriyaKalghatgi** [comment] 2019-04-26 05:24
Any `backgroundColor: null`? which file?

**Comment by dguillamot** [comment] 2019-04-29 03:50
For us it was line 177 of the native base theme file native-base/components/Button.js 

Changing it to backgroundColor: 'transparent' resolves it for us.

**Comment by AmeerHamzaRiaz** [comment] 2019-04-30 16:17
When passing transparent property to button, it crashes.

![image](https://user-images.githubusercontent.com/28997655/56976877-5d37a780-6b8d-11e9-81c2-d5fd016de1a6.png)

**Comment by Jlexyc** [comment] 2019-05-01 18:28
The same issue I have. Trying to get why. iOS works.
It happened after i've updated to RN 0.59.1

**Comment by jeveloper** [comment] 2019-05-15 22:17
I think its disabled property that crashes it.

i passed disabled transparent small

**Comment by artshevtsov** [comment] 2019-05-22 10:23
I am also facing this issue on Android 7.0 (Samsung Galaxy A3) real device.
App crashes when I open screen with disabled Button, because of "backgroundColor: null," at native-base-theme/components/Button.js:85 (const buttonTheme)
```
"native-base": "^2.12.0",
"react": "^16.8.3",
"react-native": "^0.59.8"
```

```
05-21 17:09:58.659  5983  6115 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-21 17:09:58.659  5983  6115 E AndroidRuntime: Process: com.company.appName, PID: 5983
05-21 17:09:58.659  5983  6115 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: backgroundColor
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getInt(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.uimanager.av.a(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.uimanager.l.a(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.uimanager.l.a(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.uimanager.aj.a(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.uimanager.aj.a(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source)
05-21 17:09:58.659  5983  6115 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
```

**Comment by jeveloper** [comment] 2019-05-22 17:10
The fix right now is adding style with backgroundColour: 'transparent' 
Its very annoying @SupriyaKalghatgi  decided to not bother with this simple fix

**Comment by venkatmithunk** [comment] 2019-06-03 07:31
have the same issue

**Comment by tattivitorino** [comment] 2019-06-03 14:44
Guys, changing all instances of backgroundColor:null to backgroundColor:"transparent" in the Buttons.js native-base-theme solved my issue.. in case you ejected the theme

**Comment by venkatmithunk** [comment] 2019-06-04 08:11
> The fix right now is adding style with backgroundColour: 'transparent'
> Its very annoying @SupriyaKalghatgi decided to not bother with this simple fix

this is adding a border around button

**Comment by Vadimushka** [comment] 2019-06-04 11:21
[eng]
also crashes with such parameters in the Button component
`<Button transparent dark>{this.props.children}</Button>`
one by one, the props data works fine, everything falls together

[rus]
также же крушится при таких параметрах в компонент Button
`<Button transparent dark>{this.props.children}</Button>`
по одиночке данные props нормально работает, вместе все падает

**Comment by ivnnv** [comment] 2019-06-11 08:01
this definintelly needs an urgent fix, <Button transparent /> totally breaks at the moment.

**Comment by jeveloper** [comment] 2019-06-11 17:15
@SupriyaKalghatgi whats happening with your organization?

**Comment by kpheasey** [comment] 2019-07-10 19:06
Temporary workaround:

```jsx
<Button transparent style={{backgroundColor: 'transparent'}}>
```

**Comment by Iamhere** [comment] 2019-07-11 06:39
To remove a border around button: `style={{backgroundColor: 'transparent', elevation: 0}}`

**Comment by helielson** [comment] 2019-07-20 21:00
I'm facing the same problem. @SupriyaKalghatgi any updates here?

**Comment by sanketsahusoft** [comment] 2019-07-22 08:02
cc @sankhadeeproy007

**Comment by sankhadeeproy007** [comment] 2019-07-23 08:59
Fixed in #2799. Will be available with the next version.

**Comment by t0m0120** [comment] 2019-08-01 12:31
This issue ABIs are occurring at the terminals of armeabi-v7a; armeabi?

**Comment by PlabanJr** [comment] 2019-08-16 13:59
Please try our latest release [v.2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).

**Closed by PlabanJr** 2019-08-16 13:59 UTC
Labels: android, bug, high priority
