### ISSUE TITLE
[Picker] Related/Connected Picker doesn't get updated. Works fine with React Native Picker.

### ISSUE THREAD

**Issue by janzenz** [GeekyAnts/NativeBase#636] opened 2017-03-12 16:52 UTC
## Expected behaviour
Related Picker component doesn't get updated. Works fine with React Native Picker.

![screen capture on 2017-03-13 at 00-48-43](https://cloud.githubusercontent.com/assets/1410147/23833852/ec47e5a6-0786-11e7-82e6-3e58ec0f4a1c.gif)

## Actual behaviour
It works the first time with Native Base. 

## Screenshot of emulator/device
![screen capture on 2017-03-13 at 00-50-22](https://cloud.githubusercontent.com/assets/1410147/23833865/2a1db0cc-0787-11e7-9c56-c03914349645.gif)

## Is the bug present in both ios and android or in any one of them?
Testing on iOS only

**Comment by sankhadeeproy007** [comment] 2017-03-13 06:29
Duplicate of #628

**Comment by janzenz** [comment] 2017-03-13 06:39
@sankhadeeproy007 That bug is for the Chrome Debugger tool which occurs if turned on. This one is more of "related" Pickers when a Picker is dependent on the state set by another Picker. You'll also notice in here that the Pickers are working unlike #628. Or am I missing something?

**Comment by sankhadeeproy007** [comment] 2017-03-13 06:48
Oh okay, will take a look into it.

**Comment by janzenz** [comment] 2017-03-13 06:51
@sankhadeeproy007 thank you I also tried looking but I'm too noob to identify. Will try again and add info if I find something. My guess is that the component isn't getting updated when the `this.props.children` have changed. So I'm looking into the `shouldComponentUpdate` method.

**Comment by sankhadeeproy007** [comment] 2017-03-13 07:42
I think the second picker isn't getting the right condition to render the new list.
When you select the brand in the first picker, then there should be a condition for the second picker. Something similar to a switch case statement, where the second list would depend on the value of the first list.
I'm not sure though that this is a native-base issue.

**Comment by janzenz** [comment] 2017-03-13 12:10
@sankhadeeproy007 here's my code\

```
              <Item inlineLabel>
                <Label>Brand</Label>
                <Picker
                     iosHeader="Select Brand"
                     mode="dropdown"
                     selectedValue={this.state.brand}
                     onValueChange={(value) => this.setState({
                       brand: value
                     })}>
                     {carData.getBrands().map(brand => {
                       return <Picker.Item key={brand}
                        label={carData.cars[brand].name}
                        value={brand} />
                     })}
                </Picker>
              </Item>
              <Item inlineLabel last>
                <Label>Model</Label>
                {this.state.brand && <Picker
                  iosHeader="Select Model"
                  mode="dropdown"
                  selectedValue={this.state.model}
                  enableEmptySections={true}
                  onValueChange={(model) => this.setState({model})}>
                  {carData.toArray(carData.getBrandModels(this.state.brand)).map(model => {
                    return <Picker.Item key={model.id}
                      label={model.name}
                      value={model.id} />
                  })}
                </Picker>}
              </Item>
```

The list is actually dependent on the the `this.state.brand`. So the dependent Picker should update it's child items when the `this.state.brand` changes.

**Comment by sankhadeeproy007** [comment] 2017-03-13 12:44
In your second `<Picker />`, you have the selectedValue as `this.state.model`. So when the brand is changed, what is `this.state.model`?

**Comment by ravitez** [comment] 2017-03-15 06:13
Having a similar issue on IOS. But works fine on Android
Trouble getting the Picker to update on state changes.
Any workarounds  ?

**Comment by harishsn** [comment] 2017-03-15 13:35
Same here..

**Comment by cseelus** [comment] 2017-03-21 03:49
Have the same issue.

Seems similar to an older React Native ListView issue: http://stackoverflow.com/a/33439771/973852

**Comment by encorex** [comment] 2017-03-21 17:38
Same here...

**Comment by sankhadeeproy007** [comment] 2017-03-22 07:12
@janzenz @ravitez @harishsn @cseelus @encorex I've updated a fix to master. 
Can any of you please check it out and see if that works?

**Comment by janzenz** [comment] 2017-03-22 12:09
@sankhadeeproy007 I just tried on my end and it doesn't work. I'm not sure if it's because of my `package.json` setup to get the master.

`"native-base": "github:geekyants/NativeBase#master",`

Is that correct?

**Comment by sankhadeeproy007** [comment] 2017-03-22 12:15
Just check the above commit and see if the code is there inside the native-base package.

**Comment by janzenz** [comment] 2017-03-22 12:41
@sankhadeeproy007 yup I can the changes in there. So yes that doesn't fix it unfortunately.

**Comment by sankhadeeproy007** [comment] 2017-03-22 12:49
```
const items = ['Simon Mignolet','Nathaniel Clyne','Dejan Lovren','Mama Sakho','Emre Can'];

var BUTTONS = [
  'Option 0',
  'Option 1',
  'Option 2',
  'Delete',
  'Cancel',
];

export default class testBase2 extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selected1: 'key1'
    }
  }
  getItems(val) {
    if (val === 'key1') {
      return items;
    }
    else {
      return BUTTONS;
    }
  }
  onValueChange (value: string) {
   this.setState({
     selected1 : value
   });
 }
 onValueChange2 (value: string) {
  this.setState({
    selected2 : value
  });
}
  render() {
    return (
        <Container>
          <Header>
            <Left>
              <Button transparent>
                <Icon name="heart" size={20} color='red' />
              </Button>
            </Left>
            <Body>
              <Title>Hello</Title>
            </Body>
            <Right />
          </Header>
          <Content padder>
            <Picker
                iosHeader="Select one"
                mode="dropdown"
                selectedValue={this.state.selected1}
                onValueChange={this.onValueChange.bind(this)}>
                <Item label="Wallet" value="key0" />
                <Item label="ATM Card" value="key1" />
                <Item label="Debit Card" value="key2" />
                <Item label="Credit Card" value="key3" />
                <Item label="Net Banking" value="key4" />
           </Picker>
           <Picker
               iosHeader="Select one"
               mode="dropdown"
               defaultLabel={"waiting"}
               selectedValue={this.state.selected2}
               onValueChange={this.onValueChange2.bind(this)}>
               {this.getItems(this.state.selected1).map((item, i) => {
                 console.log('item', item);
                return <Item label={item} key={`${i}+1`} value={i} />
               })}
          </Picker>
          </Content>
        </Container>
    );
  }
}
```
![picker](https://cloud.githubusercontent.com/assets/10998047/24198439/f2453aa6-0f2b-11e7-89a3-524e3e38af96.gif)

**Comment by cseelus** [comment] 2017-03-22 12:50
@sankhadeeproy007 @janzenz Can confirm it works now. Referenced it with `"native-base": "GeekyAnts/NativeBase",` inside `package.json`.

**Comment by sankhadeeproy007** [comment] 2017-03-22 12:51
This is an example I put together. The list of the second picker is determined by the first. The function `getItems(val)` checks the state and updates the list. As you can see, when the selected value is `key1`, we see a different list for picker.

**Comment by shivrajkumar** [comment] 2017-04-17 10:36
Closing the issue as it seem be resolved.

**Closed by shivrajkumar** 2017-04-17 10:36 UTC

**Comment by priyanga2496** [comment] 2018-05-15 11:05
@sankhadeeproy007
Hi could u pls tell me how to get state values assigned for picker dynamically?

**Comment by aminalali8** [comment] 2020-02-25 17:05
how is this closed again ?

**Comment by jiahuey99** [comment] 2020-11-22 18:00
working tho, Thank ya
