### ISSUE TITLE
ForwardRef(HStack)(...): Nothing was returned from render. Issue while rendering a component to test using jest/react-native-testing library.

### ISSUE THREAD

**Issue by Barrylimarti** [GeekyAnts/NativeBase#4615] opened 2022-02-08 19:13 UTC
### Description

  I want to test a basic component name TitleHeader which uses HStack and VStack from native base. But the component is not rendering properly even after trying to mock native-base.

### CodeSandbox/Snack link

https://snack.expo.dev/yMur6PJVo

### Steps to reproduce

Although I have provided the link to the expo snack reproduction....it is actually not possible to reproduce this there. It will have to be in your system only. I got this error while using react-native-cli in a bigger project. Please find the complete description with code here :- https://stackoverflow.com/questions/70982745/nativebase-showing-error-while-using-in-jest-testing

### NativeBase Version

3.3.5

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

Error Screenshot :-
![Hstackerror](https://user-images.githubusercontent.com/65606499/153058313-b791b62d-de0d-4de6-a98b-302698f6a6bd.png)
I am thinking this might be issue of not mocking native-base correctly. Is there any mock for native-base? If yes, can anyone help me write a correct mock for all the native-base components?

**Comment by Viraj-10** [comment] 2022-02-14 14:52
Hi @Barrylimarti, Thanks for reporting the issue. We will look into it.

**Comment by Viraj-10** [comment] 2022-02-15 11:07
Hi @Barrylimarti, Try using the following code.

- `renderer.create()` doesn't have wrapper option. render has the option to pass wrapper. you can find documentation [here](https://testing-library.com/docs/react-testing-library/setup#custom-render).
- Also remove `jest.mock('native-base');` 

### App.test.js

```
import React from 'react';
import { render } from '@testing-library/react-native';
import TitleHeader from './components/TitleHeader';
import { NavigationContainer } from '@react-navigation/native';
import { NativeBaseProvider } from 'native-base';

const wrapper = ({ children }) => {
  console.log('children', children);
  return (
    <NativeBaseProvider
      initialWindowMetrics={{
        frame: { x: 0, y: 0, width: 0, height: 0 },
        insets: { top: 0, left: 0, right: 0, bottom: 0 },
      }}
    >
      {children}
    </NativeBaseProvider>
  );
};
describe('Testing Title Header for screens', () => {
  test('should render title header', () => {
    const tree = render(
      <NavigationContainer>
        <TitleHeader title={'HEADER TEST'} />
      </NavigationContainer>,
      { wrapper }
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

**Comment by rahul-keyworks** [comment] 2022-02-15 22:01
> 

Hey @Viraj-10 . I did as you said and got this new error. Can you look into this please?
![Hstackerror2](https://user-images.githubusercontent.com/98030637/154156703-2bff9b6e-c4e5-4492-85a0-b98c0065b239.png)
![Hstackerror3](https://user-images.githubusercontent.com/98030637/154156726-aa01fd07-90a8-4c64-920b-e00938046570.png)

**Comment by Barrylimarti** [comment] 2022-02-15 22:05
> Hi @Barrylimarti, Try using the following code.
> 
>     * `renderer.create()` doesn't have wrapper option. render has the option to pass wrapper. you can find documentation [here](https://testing-library.com/docs/react-testing-library/setup#custom-render).
> 
>     * Also remove `jest.mock('native-base');`
> 
> 
> ### App.test.js
> 
> ```
> import React from 'react';
> import { render } from '@testing-library/react-native';
> import TitleHeader from './components/TitleHeader';
> import { NavigationContainer } from '@react-navigation/native';
> import { NativeBaseProvider } from 'native-base';
> 
> const wrapper = ({ children }) => {
>   console.log('children', children);
>   return (
>     <NativeBaseProvider
>       initialWindowMetrics={{
>         frame: { x: 0, y: 0, width: 0, height: 0 },
>         insets: { top: 0, left: 0, right: 0, bottom: 0 },
>       }}
>     >
>       {children}
>     </NativeBaseProvider>
>   );
> };
> describe('Testing Title Header for screens', () => {
>   test('should render title header', () => {
>     const tree = render(
>       <NavigationContainer>
>         <TitleHeader title={'HEADER TEST'} />
>       </NavigationContainer>,
>       { wrapper }
>     ).toJSON();
>     expect(tree).toMatchSnapshot();
>   });
> });



> ```

Hey @Viraj-10 . I did everything as you said and got this new error. Can you please look into this?
![Hstackerror2](https://user-images.githubusercontent.com/65606499/154157233-d4ac1acb-7b8b-457a-a369-d771fbf3390b.png)
![Hstackerror3](https://user-images.githubusercontent.com/65606499/154157242-14e43e6d-0999-4d37-b515-463de17de545.png)

**Comment by Viraj-10** [comment] 2022-02-17 09:45
Hi @Barrylimarti, I am unable to replicate this bug. Can you share your code?

**Comment by rahul-keyworks** [comment] 2022-02-22 13:45
Hi @Viraj-10. Thanks for your help...the problem is solved I think. I had some other mocks that was causing this issue.

**Comment by Barrylimarti** [comment] 2022-02-22 13:48
Hi @Viraj-10 the problem is solved I think. There were some other mocks in the code that was causing this issue. Thanks for your help.

**Comment by Viraj-10** [comment] 2022-02-22 13:53
Thanks for replying back closing this issue. feel free to reopen if any problem occurs.

**Closed by Viraj-10** 2022-02-22 13:53 UTC
Labels: bug, v3, triage
