### ISSUE TITLE
Cards not displaying properly for some iOS users (possible iOS 11 issue)

### ISSUE THREAD

**Issue by slickdev** [GeekyAnts/NativeBase#1276] opened 2017-10-04 17:57 UTC
## react-native, react and native-base version

"native-base": "^2.3.2",
"react": "16.0.0-alpha.12",
"react-native": "0.48.4",

## Expected behaviour

Cards should render properly for all devices.

## Actual behaviour

Cards render properly on my device (iOS 10) as well as emulators. Some users with iOS 11 are experiencing issues.

## Steps to reproduce (code snippet or screenshot)

Create a Card with CardItem and button set to {true}. Put an image inside the card. Try it on iOS 11 with an iPhone 7 or 8 PLUS.

## Screenshot of emulator/device

![22279500_1200014113433693_5736505437588889893_n](https://user-images.githubusercontent.com/2987924/31191220-568fa1ee-a8f2-11e7-947f-016bc6683b16.jpg)

The above is what the bug looks like. The card's image don't appear, and it is no longer clickable. I have another page with a card and an image and it loads fine, but this card does not have button={true} set, so this might be an issue specifically with card buttons.

![img_1869](https://user-images.githubusercontent.com/2987924/31191372-bd2d85ba-a8f2-11e7-87bc-119a0eed4862.PNG)

^ This is what it should look like

## Is the bug present in both ios and android or in any one of them?

Only tried iOS

## Any other additional info which would help us debug the issue quicker.

My cards are structured like this:

```
<Container>
        <Content padder>
          <Card>
            <CardItem cardBody button={true} onPress={() => { navigate('Samplers') }}>
              <Image source={require('./assets/images/categories/samplers.jpg')} style={{height: 200, width: null, flex: 1}}/>
              <Text style={styles.cardTextOverlay}>SAMPLERS</Text>
            </CardItem>
          </Card>
        </Content>
</Container>
```

**Comment by slickdev** [comment] 2017-10-04 22:03
I downloaded the latest Xcode and dug around some more. This issue seems to only occur on iOS 11 on iPhone 7 Plus, not the regular iPhone 7. Will test others as well.

Specifically, it relates to the `style` attribute on the <Image> component. If I remove the styling, it works properly. It might be an issue with the `width: null` part?

Also I'm not entirely sure if this is a NativeBase issue, or a react-native issue. Anyone have any insight?

**Comment by slickdev** [comment] 2017-10-04 22:11
Only if I remove the width and height attributes, the image loads properly (although improperly sized). Very strange.

**Comment by slickdev** [comment] 2017-10-04 22:25
It gets deeper... it has to do with the height I set the images to. If I try a taller height, the issue seems to go away. My images were set to `height: 200` and if I changed it to `height: 260` it works. I tried it with JPGs and PNGs. Seems to be an issue with the image scaling.

**Comment by mtebele** [comment] 2017-10-06 02:33
Try setting `flexWrap: 'nowrap'` on Card style.

**Comment by anmolmayank** [comment] 2017-10-10 09:46
Is there any solution?
I am trying to use this card  inside a deskSwiper,
I tried to give flexWrap: 'nowrap' to the card and I was able get the entire image inside a card > cardItem index[0], but other items are not displaying properly.

**Comment by akhil-geekyants** [comment] 2017-11-09 06:47
@anmolmayank 
tried deckswiper using slickdev's card adding card style`flexWrap: 'nowrap'`. It was working fine. Attaching a gif

![cardsissue](https://user-images.githubusercontent.com/27768184/32592027-efa84626-c547-11e7-91cd-eab5c1467389.gif)

**Comment by akhil-geekyants** [comment] 2017-11-20 06:05
Closing the issue due to no response

**Comment by slickdev** [comment] 2017-11-20 06:06
The issue wasn't regarding deckswiper. It was regarding the card component.

**Comment by mtebele** [comment] 2017-11-21 18:29
@akhil-geekyants there's no solution yet. The issue is about the card component, not about deckswiper.

**Comment by SupriyaKalghatgi** [comment] 2017-11-22 05:54
Sorry! There might be some confusion in answering between the issues
We will reconsider this

**Comment by shobhitnpm** [comment] 2017-11-23 08:48
It can be fixed by using flexWrap: 'nowrap' on Card style.
thanks to mtebele

**Comment by SupriyaKalghatgi** [comment] 2017-11-28 12:09
@slickdev @mtebele The comment [here](https://github.com/GeekyAnts/NativeBase/issues/1276#issuecomment-343062900) by @akhil-geekyants was answer to @anmolmayank query [here]
(https://github.com/GeekyAnts/NativeBase/issues/1276#issuecomment-335420062)

@akhil-geekyants There is no confusion now

**Comment by SupriyaKalghatgi** [comment] 2017-11-28 12:34
@slickdev @mtebele @anmolmayank @shobhitnpm 
```
<Card>
  <CardItem cardBody button={true}>
    <Image
      source={require("../../../assets/NavLogo.png")}
      style={{ width: null, flex: 1 }}
    />
  </CardItem>
  <CardItem>
    <Text>SAMPLERS</Text>
  </CardItem>
</Card>
```
This seems to be working fine with iOS 11 iPhone 7Plus
The issue was due to improper value of height with Image

**Comment by SupriyaKalghatgi** [comment] 2017-11-28 12:35
for that matter `width` is not mandatory
the above snippet works without providing width to Image

**Comment by ikhsanalatsary** [comment] 2017-12-05 05:44
same issue here. but tested on 
Device: iPhone 6S+
iOS: 10.3.3

also 

Device: Tab Lenovo A5500
Android: Jellybean

**Comment by akhil-geekyants** [comment] 2018-01-10 13:39
@ikhsanalatsary can you check with native-base version 2.3.6

**Comment by SupriyaKalghatgi** [comment] 2018-01-11 10:53
![image](https://user-images.githubusercontent.com/13464885/34822078-b2e6b562-f6eb-11e7-8be1-861ba02d22bd.png)

This is from NativeBase-KitchenSink
Card with Image renders fine on iPhone 6s+

**Closed by SupriyaKalghatgi** 2018-01-11 10:53 UTC
Labels: awaiting response

**Comment by ikhsanalatsary** [comment] 2018-01-15 15:10
Yes, it's works
