### ISSUE TITLE
Upgrade to Babel 7 React Native 0.56 -- Breaking Change

### ISSUE THREAD

**Issue by dharmilsan** [GeekyAnts/NativeBase#2028] opened 2018-06-19 08:14 UTC
RN v0.56 is going to introduce a **breaking change** in terms of upgrading to **babel7. babel7** is **NOT** backwards-compatible with babel6 and hence all the plugins will need to be manually updated to import the new babel scoped packages. Read more here: https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#056 and https://babeljs.io/docs/en/next/v7-migration

Given that native-base's dependencies use babel 6 (native-base-shoutem-theme, react-native-vector-icons amongst the ones I've checked), what is the migration plan? I've tried monkey patching both the packages manually but ES6 imports still fail with my config.

**Comment by SupriyaKalghatgi** [comment] 2018-06-20 09:58
https://github.com/facebook/react-native/issues/19819

**Comment by SupriyaKalghatgi** [comment] 2018-06-20 10:10
@dharmilsan Did you try to run RN app with RN 0.56.0 or 0.56.0-rc.2?

**Comment by dharmilsan** [comment] 2018-06-22 04:15
@SupriyaKalghatgi Honestly speaking, I was trying to get this running using react-native-web and Next.js which uses Babel 7 by default. That being said, I can probably try checking if I can build v0.56 today

**Comment by SupriyaKalghatgi** [comment] 2018-06-22 05:18
https://github.com/facebook/react-native/issues/19820
https://github.com/facebook/react-native/issues/19789

**Comment by jacargentina** [comment] 2018-06-25 02:09
@SupriyaKalghatgi about #2035, `ReactNativePropRegistry` exists in 0.55.4 **but it does not exists in 0.56.0-rc.3**

So that should be taken into account here too!

**Comment by ms502040** [comment] 2018-07-01 00:38
Any patch for RN 0.56.0?    
if I manual copy old react-native/Libraries/Renderer/shims/ReactNativePropRegistry.js I can run RN app, but it`s dirty workaround.
---
"@babel/core": "^7.0.0-beta.47",
"native-base": "^2.6.1",
"react": "^16.4.1",
"react-native": "^0.56.0-rc.3",
"babel-jest": "23.0.1",
"babel-plugin-module-resolver": "^3.1.1",
"babel-preset-react-native": "^5.0.2",

**Comment by fhadsheikh** [comment] 2018-07-05 16:19
Getting the same error:

```
Error: Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `/node_modules/native-base/dist/src/Utils/computeProps.js`: Module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` does not exist in the Haste module map
```

Is there a plan to fix this?

**Comment by elhachimi** [comment] 2018-07-05 16:32
hey! getting the same error as @fhadsheikh after upgrading to RN 0.56.0

**Comment by stueynet** [comment] 2018-07-05 16:38
Anyone on Nativebase team seeing this? Can you acknowledge?

**Comment by trandromeda** [comment] 2018-07-05 18:29
Being blocked on this like the last few posters too... any update appreciated!

**Comment by stokesbga** [comment] 2018-07-05 18:33
Im glad people are getting blocked if they're too stupid to read

**Comment by stueynet** [comment] 2018-07-05 18:40
> Im glad people are getting blocked if they're too stupid to read
@stokesbga Too stupid to read what? We saw your fork and thanks for taking the time to do it. I think on our end we would prefer to not adjust react native to make native-base work so we were hoping, as the first post asks, we could see if there is a migration plan for it.

**Comment by stueynet** [comment] 2018-07-05 18:42
@stokesbga here is a search of this repo's issues relating to 56. https://github.com/GeekyAnts/NativeBase/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+56

As you can see this is the only thread. I think its more than appropriate to comment right here.

**Comment by stokesbga** [comment] 2018-07-05 18:44
The answer to your question is yes. There is a plan for native-base support RN56. If you insist of moving to latest RN version, you have to be patient with third party libs.

**Comment by stueynet** [comment] 2018-07-05 18:46
Yeah we have not moved yet. We just started testing 56 and so far this is the only stopper. This issue has been open for a few weeks now with no specific reply so I think people here are just trying to drum up some attention from the team. If they are on it then a simple comment would be all thats required.

**Comment by ujwal-setlur** [comment] 2018-07-05 21:28
The contents of said file ReactNativePropRegistry.js is interesting:

```js
/**
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @providesModule ReactNativePropRegistry
 * @flow
 */

'use strict';

const {
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED,
} = require('ReactNative');

module.exports =
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactNativePropRegistry;
```

I don't believe any third party library should be dependent on this. It's been an issue with native-base for a while, unfortunately.

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 02:17
We are aware of this, and will fix soon

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 02:20
This issue is opened quite days ago, but we cannot start making changes to our package depending on `rc` release of React Native

**Comment by ujwal-setlur** [comment] 2018-07-06 02:46
Completely understand that. I was just questioning the dependency of a third party library like native-base on an internal API.

**Comment by redefinered** [comment] 2018-07-06 06:20
I have a project which is due 4 business days from now and I heavily rely on native base. Someone please help? :( Please tell me what RN version is going to work with the latest native base release? Thanks!

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 06:40
https://github.com/facebook/react-native/issues/20015
https://github.com/facebook/react-native/issues/18247

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 15:44
Fixed with [2.7.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.0)

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 15:44
Keeping this issue open over this weekend
let me know in case of any issues

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 15:49
Upgraded [NativeBase KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by ujwal-setlur** [comment] 2018-07-06 15:55
@SupriyaKalghatgi, thanks! Very prompt! 

Is this still backwards compatible with react-native < 0.56.0? Some of other libraries that I use have issues as well so I need to wait 😄

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 15:56
@ujwal-setlur This is mentioned in release notes
You can also find this information with ReadMe

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 16:12
I tried these 
```
    "native-base": "2.7.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
```
worked fine

**Comment by ujwal-setlur** [comment] 2018-07-06 16:15
Thanks!

**Comment by stueynet** [comment] 2018-07-06 16:16
Thanks you so much @SupriyaKalghatgi! I think everyone here appreciates the work to get this updated!

**Comment by stokesbga** [comment] 2018-07-07 04:54
Thank you guys. Not the useless morons, but the native-base team

**Comment by stueynet** [comment] 2018-07-07 10:08
> Thank you guys. Not the useless morons, but the native-base team

@stokesbga for posterity

**Comment by redefinered** [comment] 2018-07-08 22:51
@SupriyaKalghatgi I tried
```
   "native-base": "2.7.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
```
I get this error:

<img width="355" alt="screen shot 2018-07-09 at 6 48 45 am" src="https://user-images.githubusercontent.com/5173630/42424771-7c64f374-8344-11e8-8238-2875be16aa7b.png">

**Comment by JonathanGuo** [comment] 2018-07-08 23:44
@redefinered Have you upgraded your `babel-preset-react-native`?

Try upgrade it in your `package.json`.

```json
"babel-preset-react-native": "^5.0.2",
```

**Comment by SupriyaKalghatgi** [comment] 2018-07-09 04:09
@redefinered The screenshot says error is due to babel-preset-react-native, then you must share this too along with NativeBase, React and React Native versions

**Comment by SupriyaKalghatgi** [comment] 2018-07-09 04:10
Closing this today

**Comment by rfviolato** [comment] 2018-07-09 07:56
I can confirm that the issue is gone and everything is working. Thanks! :)

```
"native-base": "^2.7.0",
"react": "16.4.1",
"react-native": "0.56.0",
"babel-preset-react-native": "^5",
```

**Closed** 2018-07-10 04:13 UTC

**Comment by bonlemuel** [comment] 2018-07-30 06:38
@redefinered were you able to solve the issue?

**Comment by duranmla** [comment] 2018-08-11 00:38
Basically, I use the same approach as https://github.com/GeekyAnts/NativeBase/issues/396#issuecomment-270116326 and now it works as expected.

**Comment by haotangio** [comment] 2018-10-04 01:30
Problem reoccur on RN 0.57 & `"native-base": "^2.8.1"`
<img width="567" alt="screen shot 2018-10-04 at 8 28 54 am" src="https://user-images.githubusercontent.com/8952752/46448168-ad918700-c7af-11e8-94c7-2bfc31e38d1d.png">

**Comment by haotangio** [comment] 2018-10-04 02:18
> Problem reoccur on RN 0.57 & `"native-base": "^2.8.1"`
> <img alt="screen shot 2018-10-04 at 8 28 54 am" width="567" src="https://user-images.githubusercontent.com/8952752/46448168-ad918700-c7af-11e8-94c7-2bfc31e38d1d.png">

Fixed with last effort of adding the file manually seems to fix the issue
https://github.com/facebook/react-native/blob/0.49-stable/Libraries/Renderer/shims/ReactNativePropRegistry.js

**Comment by SupriyaKalghatgi** [comment] 2018-10-04 05:02
All fine with React Native 0.57 and NativeBase 2.8.1
![image](https://user-images.githubusercontent.com/13464885/46453734-aaeb5d80-c7c0-11e8-9668-b7d67ee5e00f.png)

**Comment by pabloLarios24** [comment] 2018-10-04 18:46
Module `react-native/Libraries/Renderer/shims/ReactNativeBridgeEventPlugin` does not exist in the Haste module map, how fix it?

**Comment by SEWilco** [comment] 2018-10-05 23:00
I've spent several days fighting dependencies, and now find that my fresh install can't handle my app's code because the development platform broke itself? Ick.

**Comment by SEWilco** [comment] 2018-10-06 02:43
> I've spent several days fighting dependencies, and now find that my fresh install can't handle my app's code because the development platform broke itself? Ick.

Hey, is there a link in here to where all the similar breaking items are listed? I need to know what else has been broken in the past year.

**Comment by melkishengue** [comment] 2019-02-15 15:54
Facing the same issue with following configuration:

`"@babel/core": "^7.1.0",
    "@ptomasroos/react-native-multi-slider": "^0.0.12",
    "apisauce": "^0.14.3",
    "babel-core": "7.0.0-bridge.0",
    "eslint": "^4.15.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "moment": "^2.21.0",
    "native-base": "^2.7.0",
    "prop-types": "^15.6.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-autolink": "^1.4.0",
    "react-native-collapsible": "^0.10.0",
    "react-native-config": "^0.11.5",
    "react-native-easy-grid": "^0.1.17",
    "react-native-fast-image": "4.0.14",
    "react-native-i18n": "^2.0.10",
    "react-native-maps": "^0.21.0",
    "react-native-modal": "^5.3.0",
    "react-native-render-html": "^3.9.0",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-splash-screen": "^3.0.6",
    "react-native-swiper": "^1.5.13",
    "react-native-timer": "^1.3.1",
    "react-native-vector-icons": "^4.5.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"`

In.babelrc:

`{
  "presets": ["react-native"]
}`

**Comment by melkishengue** [comment] 2019-02-15 15:55
``"@babel/core": "^7.1.0",
    "@ptomasroos/react-native-multi-slider": "^0.0.12",
    "apisauce": "^0.14.3",
    "babel-core": "7.0.0-bridge.0",
    "eslint": "^4.15.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "moment": "^2.21.0",
    "native-base": "^2.7.0",
    "prop-types": "^15.6.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-autolink": "^1.4.0",
    "react-native-collapsible": "^0.10.0",
    "react-native-config": "^0.11.5",
    "react-native-easy-grid": "^0.1.17",
    "react-native-fast-image": "4.0.14",
    "react-native-i18n": "^2.0.10",
    "react-native-maps": "^0.21.0",
    "react-native-modal": "^5.3.0",
    "react-native-render-html": "^3.9.0",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-splash-screen": "^3.0.6",
    "react-native-swiper": "^1.5.13",
    "react-native-timer": "^1.3.1",
    "react-native-vector-icons": "^4.5.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"``

**Comment by melkishengue** [comment] 2019-02-15 15:57
I am also facing the same issue with the following configuration:

```"@babel/core": "^7.1.0",
    "@ptomasroos/react-native-multi-slider": "^0.0.12",
    "apisauce": "^0.14.3",
    "babel-core": "7.0.0-bridge.0",
    "eslint": "^4.15.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "moment": "^2.21.0",
    "native-base": "^2.7.0",
    "prop-types": "^15.6.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-autolink": "^1.4.0",
    "react-native-collapsible": "^0.10.0",
    "react-native-config": "^0.11.5",
    "react-native-easy-grid": "^0.1.17",
    "react-native-fast-image": "4.0.14",
    "react-native-i18n": "^2.0.10",
    "react-native-maps": "^0.21.0",
    "react-native-modal": "^5.3.0",
    "react-native-render-html": "^3.9.0",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-splash-screen": "^3.0.6",
    "react-native-swiper": "^1.5.13",
    "react-native-timer": "^1.3.1",
    "react-native-vector-icons": "^4.5.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
```

.babelrc:

```
{
  "presets": ["react-native"]
}
```

**Comment by radjivF** [comment] 2019-05-01 11:38
I have following all the steps in this issue but I still have it the error
