### ISSUE TITLE
ref Error of Content.js on React Native 0.63.1

### ISSUE THREAD

**Issue by emclab** [GeekyAnts/NativeBase#3189] opened 2020-07-18 01:51 UTC
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

On latest RN 0.63.1/native-base 2.13.12, `Content` throws error:

[Fri Jul 17 2020 18:38:19.215]  ERROR    Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Content`.
    in Unknown (at Content.js:37)
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (at Content.js:36)
    in Content (at connectStyle.js:392)
    in Styled(Content) (at Itie.js:207)
    in RCTView (at View.js:34)
    in View (at Container.js:12)
    in Container (at connectStyle.js:392)
    in Styled(Container) (at Itie.js:189)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at Itie.js:185)
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (at Itie.js:184)
    in Itie (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at AppScreen.js:82)
    in AppScreen (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at App.js:31)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:376)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:30)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 12.18
yarn: 1.22.4
react 16.13.1
native-base:2.13.12
Android emulator
#### Steps to reproduce
1. create react native project
2. install native-base 2.13.12
3. Use the following render structure to reproduce error
:
=SafeAreaView> 
  =ScrollView>
    =Container> //<<<=native base component
        =Header>
        =Content padder> //<<<==Content causes error
               =Form>
                       =Input onChangeText={nameChange} placeholder={'Name'} />
                       =Textarea padder rowSpan={2} bordered placeholder="Spec" onChangeText={despChange} /> 
        =Footer>

The error screen:
![Capture](https://user-images.githubusercontent.com/946013/87842105-c07b2b80-c85e-11ea-895d-df7dbf548955.JPG)

#### Is the bug present in both iOS and Android or in any one of them?
Error on Android platform. Not tested on IOS
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by droM4X** [comment] 2020-07-18 07:26
Duplicate of #3183

**Comment by codler** [comment] 2020-07-19 06:57
I have [forked](https://github.com/codler/NativeBase) the repo to fix this issue.
```
npm i @codler/native-base
```
You might need to remove old fonts in `Copy Bundle Resources` in Xcode after install

**Comment by JerakRus** [comment] 2020-07-20 12:30
@sankhadeeproy007 
is the repository really failing anymore? and will this critical issue be fixed?

**Comment by sankhadeeproy007** [comment] 2020-07-20 13:04
Hey, we just published a new version with the latest dependency fixes.
Can you please upgrade and let us know?

**Comment by ankitghosh** [comment] 2020-07-20 15:37
This has been fixed after the latest merge :)

**Comment by hanykumar** [comment] 2020-09-07 11:48
Hi @emclab , closing for now. Let us know if the issue still persists.

**Closed by hanykumar** 2020-09-07 11:48 UTC
