### ISSUE TITLE
Typescript error when using variant on Text

### ISSUE THREAD

**Issue by bilmaijer** [GeekyAnts/NativeBase#4240] opened 2021-10-26 20:05 UTC
**Describe the bug**
I want to use variants on Text, but it's throwing an error

**To Reproduce**
Define Text variant in extendTheme. Use that variant in Text component.

Also some elements, including Text are warning that all(a lot) props are required after upgrading to 3.2.1

Everything works as expected when running on device, just the error appears. I can't use typecheck pre-commit hook :(

**Expected behaviour**
No errors

**Screenshots**

![Screenshot 2021-10-26 at 23 01 00](https://user-images.githubusercontent.com/7389069/138952303-3235af8b-8ef5-4c99-883d-593e71e1f4c6.png)

![Screenshot 2021-10-26 at 23 03 18](https://user-images.githubusercontent.com/7389069/138952489-c5fbc487-fc26-4eef-943b-b7849a6801de.png)

**Platform**

- NativeBase version [3.2.1]
- Device: [iPhone Xr]
- OS: [iOS14.7.1]
- React Native version [0.66.0]
- node [v12.14.1]
- npm [6.13.4]

**Comment by lucanisi** [comment] 2021-10-31 11:16
> This is happening, because in default theme Text has no variants, and so variant prop in not defined. I'm not sure if that's intentional.
> 
> As a workaround you can extend the ITextProps interface manually:
> 
> ```ts
> const theme = extendTheme();
> type CustomThemeType = typeof theme;
> 
> declare module 'native-base' {
>   type ICustomTheme = CustomThemeType;
> 
>   interface ITextProps {
>     variant?: keyof CustomThemeType['components']['Text']['variants'];
>   }
> }
> ```

This helped me a lot, but I had to move the declaration outside the extendTheme since It was throwing a typescript error on ['variants'].

This is my solution, hope it helps.

```ts
import {extendTheme, ITheme} from 'native-base';
declare type IExtendThemeParam = ITheme | Record<string, any>;

const customTheme: IExtendThemeParam = {
  components: {
    Text: {
      variants: {
        caption: {
          color: '#ccc',
        },
      },
    },
  },
};

const theme = extendTheme(customTheme);
type CustomThemeType = typeof customTheme;

declare module 'native-base' {
  interface ITextProps {
    variant?: keyof CustomThemeType['components']['Text']['variants'];
  }
}
 ```

**Comment by makkarMeenu** [comment] 2021-11-15 10:41
This has been resolved in NativeBase 3.2.2 . Please let us know if you face any issue.

**Comment by seeden** [comment] 2021-11-21 18:12
@makkarMeenu variants are not working for Text component in NativeBase 3.2.2. When I use any of my variants it will be completely ignored

**Closed** 2021-11-22 07:10 UTC
Labels: v3

**Comment by makkarMeenu** [comment] 2021-11-22 07:37
> @makkarMeenu variants are not working for Text component in NativeBase 3.2.2. When I use any of my variants it will be completely ignored

We cannot reproduce it, you can share a link of the snack if you face the same issue, we will re-open this issue.

**Comment by makkarMeenu** [comment] 2021-11-22 09:03
> @makkarMeenu variants are not working for Text component in NativeBase 3.2.2. When I use any of my variants it will be completely ignored

We are unable to reproduce this. You can share your issue with repo link, so that we can help you regarding this.

**Comment by seeden** [comment] 2021-11-22 13:25
Thank you. Sure, I will prepare codesandbox today
