### ISSUE TITLE
Icons not properly handling responsive Size prop in React Native 

### ISSUE THREAD

**Issue by GollyJer** [GeekyAnts/NativeBase#5174] opened 2022-07-18 00:28 UTC
### Description

Feeding responsive object prop to icon Size does not work.

### Expo Snack

https://snack.expo.dev/@gollyjer/nativebase-responsive-icon-size

### Steps to reproduce

1. Go to the expo snack and run it on your device.
2. See how the third icon isn't sized, but the wrapper is completely blown out
3. Comment out lines 37-43 and uncomment line 36
4. See things work as expected.

After finally getting a great version of our app working on phones we set out to make everything responsive for iPad and Web but we're running into issues with responsive Icons; which feeds into Buttons and IconButtons also.

The code path for Icon size leads here in the `usePropsResolution` hook.
https://github.com/GeekyAnts/NativeBase/blob/2af374e586034366dcefce9a0f23983836a7901f/src/hooks/useThemeProps/usePropsResolution.tsx#L336

I'll keep troubleshooting but hoping someone else might be able to help as well.

Thanks~

### NativeBase Version

3.4.9

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by GollyJer** [comment] 2022-07-18 01:01
Taking notes as I debug....

Doing some console.logging of `resolvedProps` in `usePropsResolution.tsx`...

When I pass in 
```javascript 
size="2xl"
``` 
it logs
```javascript 
Object {
  "as": [Function Icon],
  "borderWidth": 1,
  "color": "muted.500",
  "name": "home",
  "size": 8, // 👈
}

```

When I pass in 
```javascript 
size={{
  base: '2xl',
  sm: '2xl',
  md: '2xl',
  lg: '2xl',
  xl: '2xl',
}}
``` 
it logs

```javascript 
Object {
  "as": [Function Icon],
  "borderWidth": 1,
  "color": "muted.500",
  "name": "home",
  "size": "2xl", // 👈
}
```

**Comment by GollyJer** [comment] 2022-07-18 03:42
OK, I figured this out working locally and then went into the source code here and github...

Here's the weird thing. Even though I pulled down latest, `3.4.9`, the `usePropsResolution.tsx`  file in `node_modules` is completely different than the one in the source code. 

How does this happen? Simply copying the code from source and completely pasting over `usePropsResolution.tsx` in `node_modules` fixes the problem. The current code is significantly improved over what gets `yarn installed`.

How does this happen? How much of the other code is old? I did a `yarn cache clean --all` and completely wiped `node_modules` and rebuilt... same thing happens. The wrong code is pulled down.

The same issue shows up in the Snack linked in the opening post of this thread.

Not sure what to do about this. Any pointers is appreciated.

**Comment by Krithikj20** [comment] 2022-07-20 05:18
Thank you for reporting this issue @GollyJer, We will try to fix it at the earliest.

**Comment by GollyJer** [comment] 2022-07-20 16:16
You're welcome @ankit-tailor.

I'm curious how this happens? Is the file not picked up in the build process somehow? I've never run into a case where the source and the node_modules didn't match.

**Comment by GollyJer** [comment] 2022-07-22 14:43
@ankit-tailor @Krithikj20 
Is there an alpha build with this change that we can install?

I just found out that patch-package doesn't work with the newest react native builds so I have no way to update for our production builds. (We use expo eas).

I spent a week converting our entire app over to native-base and can't deploy. 😐

**Comment by ankit-tailor** [comment] 2022-07-27 11:58
Hey @GollyJer, This shouldn't be happening. I've tried reproducing the issue but couldn't find anything. Please provide some snack link for that. 

Also regarding the icon size issue, I've tried and it looks like size passed as responsive props are not getting resolved. I am looking into the issue. Thanks for reporting the issue.

**Comment by ankit-tailor** [comment] 2022-08-04 07:06
Hey @GollyJer, This issue is fixed in `v3.4.11`

**Closed by ankit-tailor** 2022-08-04 07:06 UTC
Labels: bug, v3, triage

**Comment by GollyJer** [comment] 2022-08-05 20:05
Thanks @ankit-tailor! Verified working.
https://twitter.com/GollyJer/status/1555645880098729984

**Comment by ankit-tailor** [comment] 2022-09-06 06:34
Hi @GollyJer, With current changes, we are facing `SSR` issue so we are reverting this Pr. but instead of using declaratively, you can use it imperatively.

```js
const size= useBreakpointValue({
  base: '2xl',
  sm: '2xl',
  md: '2xl',
  lg: '2xl',
  xl: '2xl',
})

<Button size={size} />
```

**Comment by GollyJer** [comment] 2022-09-06 20:02
@ankit-tailor The title of this issue is a bit misleading... it's not just about the Icons. 
If you revert this change, responsiveness across the nativebase components will stop working.

I assume you're talking about the update to the `usePropsResolution` function. Is that correct?

**Comment by ankit-tailor** [comment] 2022-09-06 20:42
@GollyJer  No, Responsiveness across components won't break. Just `variant`, `size`, and `colorScheme` will not be resolved responsively.  For that, you can use the above workaround.
