### ISSUE TITLE
TypeError: Cannot read property 'panHandlers' of undefined (SwipeRow)

### ISSUE THREAD

**Issue by onurcskun** [GeekyAnts/NativeBase#2819] opened 2019-07-26 14:32 UTC
TypeError: Cannot read property 'panHandlers' of undefined

This error is located at:
    in SwipeRow (at connectStyle.js:392)
    in Styled(SwipeRow) (at feedback-list-item/index.js:295)
    in FeedbackListItem (at inbox-screen/index.js:303)
    in RCTView (at View.js:45)
    in View (at inbox-screen/index.js:299)
    in StaticRenderer (at ListView.js:463)
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:952)
    in ScrollView (at ListView.js:324)
    in ListView (at inbox-screen/index.js:555)
    in RCTView (at View.js:45)
    in View (at inbox-screen/index.js:527)
    in InboxScreenComponent (at inbox/index.js:355)
......

dependencies
"dependencies": {
    "@expo/vector-icons": "^10.0.3",
    "@react-native-community/async-storage": "^1.5.1",
    "@unimodules/core": "^2.0.1",
    "@unimodules/react-native-adapter": "^2.0.1",
    "babel-core": "^7.0.0-bridge.0",
    "expo-asset": "^5.0.1",
    "expo-constants": "^5.0.1",
    "expo-file-system": "^5.0.1",
    "expo-font": "^5.0.1",
    "i18n": "^0.8.3",
    "i18n-js": "^3.2.1",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "native-base": "^2.11.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-dom": "^16.8.6",
    "react-native": "^0.57.1",
    "react-native-error-boundary": "^1.0.2",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-crop-picker": "^0.25.0",
    "react-native-image-picker": "^1.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-permissions": "^1.1.1",
    "react-native-push-notification": "^3.1.3",
    "react-native-render-html": "^4.1.2",
    "react-native-sentry": "^0.43.2",
    "react-native-simple-markdown": "^1.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.0",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.0.4"
  },

![image](https://user-images.githubusercontent.com/20303109/61959034-2e35a400-afcb-11e9-8d78-c415bc1e1acc.png)

**Comment by kozillla** [comment] 2019-07-27 13:36
having same issue
...
"native-base": "^2.13.4",
"react-native": "0.60.4",
...

**Comment by onurcskun** [comment] 2019-07-29 08:46
> having same issue
> ...
> "native-base": "^2.13.4",
> "react-native": "0.60.4",
> ...

**Comment by onurcskun** [comment] 2019-07-29 08:47
@kozillla it's removed on that version.

**Comment by PlabanJr** [comment] 2019-08-16 14:15
This is a duplicate of #2866.

**Closed by PlabanJr** 2019-08-16 14:15 UTC
