### ISSUE TITLE
Items with floatingLabel are broken in release mode

### ISSUE THREAD

**Issue by jalpedersen** [GeekyAnts/NativeBase#2264] opened 2018-09-06 07:57 UTC
Items with floatingLabels are not rendered correctly when building a release - only a single input is rendered and it looses all properties such as keyboardType, onChangeText, etc

The issue is not present in 2.7.2

## node, npm, react-native, react and native-base version, expo version if used
node v10.9.0
npm 6.4.0
react-native 0.56.0
react 16.4.1
native-base 2.8.0

## Expected behaviour
I would expect that the item would look and behave the same in dev and release mode
## Actual behaviour
Only an input with no properties is rendered in release mode
## Steps to reproduce should include code snippet and screenshot. Include code snippet in 
minimal example including screenshots: 
    https://github.com/jalpedersen/native_base_floating

## Is the bug present in both iOS and Android or in any one of them?
Both iOS And Android

**Comment by SupriyaKalghatgi** [comment] 2018-09-07 05:10
Check commit https://github.com/GeekyAnts/NativeBase/commit/8664ffb75a262df3de336ddff1f6ebe283977cb0

**Comment by gvarandas** [comment] 2018-09-08 03:32
As the author of the original PR, I will investigate the exact cause of this break in production mode.
Only reverting the commit will bring back the HOC issue with floating labels.
Its not productive imho.

**Comment by gvarandas** [comment] 2018-09-11 17:00
@SupriyaKalghatgi I've identified the cause of the problem. Should I open a new issue so we can discuss this? A new PR?

**Comment by Sourabhd1164** [comment] 2018-09-17 17:49
Is this issue fixed. I have similar issue in Release APK but floating labels are totally disappearing in Release version

**Comment by vauruk** [comment] 2018-09-17 21:33
> @gvarandas yes, true that
> I take the basic functionality of this component i.e., label floats up on click, at highest priority. Than HOC and other functionalities.
> 
> You can go ahead and dig into this

Hi when make a new release? or how i genereted new release in my project? tks

**Comment by vauruk** [comment] 2018-09-18 12:29
I find new bug, i dont find error in the code ! i need help! tks
![imagem nativebase](https://user-images.githubusercontent.com/12579082/45687517-65266800-bb25-11e8-864c-4fccb5535c84.jpeg)

**Comment by SupriyaKalghatgi** [comment] 2018-09-19 05:14
@Sourabhd1164 Yes it is fixed and available on `master`

**Comment by SupriyaKalghatgi** [comment] 2018-09-19 05:14
@vauruk Will release this week

**Comment by SupriyaKalghatgi** [comment] 2018-09-19 05:15
@vauruk Can you share code snippet for above screenshot?
Is it in debug or release mode?
Version of NativeBase?

**Comment by vauruk** [comment] 2018-09-19 15:52
> @vauruk Can you share code snippet for above screenshot?
> Is it in debug or release mode?
> Version of NativeBase?
Sorry
@SupriyaKalghatgi , i using version master release, 
"Version of NativeBase?" - i download last release!,
 "Is it in debug or release mode?" - both
 My code:

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { Redirect } from 'react-router-dom';
import { Platform, StyleSheet, Image } from 'react-native';
import logo from '../../../assets/logo.jpg'
import {
    Container, Header,
    Content, Button, Form,
    Item, Input, Label, Text,
    Toast, Spinner, Grid, Row, Col
} from 'native-base'
import { I18n, Analytics } from 'aws-amplify';
import { signIn } from '../../../redux/actions/auth'

import styles from '../Theme'

import Loading from '../Loading'

type Props = {};
class Login extends Component<Props> {

    constructor(props) {
        super(props);
        this.state = {
            textEmail: null,
            textPassword: null
        }
    }

    handleSignIn = () => {
        if (this.state.textEmail && this.state.textEmail.length > 0
            && this.state.textPassword && this.state.textPassword.length) {
            this.props.signIn(this.state.textEmail, this.state.textPassword)
            Analytics.record('SignIn App')
        } else {
            Toast.show({
                text: 'Favor inserir usuário e senha!',
                //buttonText: 'Okay'
            })
        }

    }

    handleRegister = () => {
        this.props.history.push('/register')
    }
    handleForgot = () => {
        this.props.history.push('/forgot')
    }

    render() {
        const { currentUser } = this.props;

        if (currentUser) {
            // console.log('entrou login')
            return <Redirect to="/" />;
        }
        if (this.props.loadingAuth) {
            return (
                <Loading />
            );

        } else {
            return (
                <Container style={styles.container}>

                    <Content style={{ padding: 5 }}>
                        <Grid style={styles.centerGrid}>
                            <Image source={logo} />
                        </Grid>
                        <Grid style={styles.centerGrid}>
                            {this.props.message ?
                                <Text style={{ color: 'red' }}>{I18n.get(this.props.message)}</Text>
                                : undefined}
                        </Grid>
                        <Form>
                            <Item floatingLabel >
                                <Label>{I18n.get('Email')}</Label>
                                <Input
                                    value={this.state.textEmail}
                                    keyboardType='email-address' maxLength={60}
                                    onChangeText={(textEmail) => this.setState({ textEmail })} />
                            </Item>
                            <Item floatingLabel >
                                <Label>{I18n.get('Password')}</Label>
                                <Input
                                    value={this.state.textPassword}
                                    secureTextEntry={true}
                                    onChangeText={(textPassword) => this.setState({ textPassword })} />
                            </Item>
                        </Form>
                        <Button block style={{ marginTop: 50 }} onPress={() => this.handleSignIn()}>
                            <Text style={{ color: '#ffffff' }}>{I18n.get('Sign In')}</Text>
                        </Button>
                        <Row>
                            <Col>
                                <Button block transparent onPress={() => this.handleForgot()}>
                                    <Text>{I18n.get('Forgot Password')}</Text>
                                </Button>
                            </Col>
                            <Col>
                                <Button block transparent onPress={() => this.handleRegister()}>
                                    <Text>{I18n.get('Register')}</Text>
                                </Button>
                            </Col>
                        </Row>
                    </Content>
                </Container>
            );
        }
    }
}

const mapStateToProps = (state) => ({
    currentUser: state.auth.currentUser,
    loadingAuth: state.auth.loadingAuth,
    message: state.auth.message
});

const mapDispatchToProps = dispatch => bindActionCreators({
    signIn
}, dispatch)


export default connect(mapStateToProps, mapDispatchToProps)(Login);

**Comment by Sourabhd1164** [comment] 2018-09-19 22:52
@SupriyaKalghatgi @vauruk  Yes, checked the master branch just now and Im getting that cut-off bug too on both release and debug modes. Will share the code and screenshot if needed?

**Comment by SupriyaKalghatgi** [comment] 2018-09-20 03:34
yes

**Comment by SupriyaKalghatgi** [comment] 2018-09-24 05:56
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/c491eccfa5519d296a05b253f123f7df119eeacf, pushed to `master`
![image](https://user-images.githubusercontent.com/13464885/45938962-76bbb400-bfec-11e8-9743-3083a31eaed0.png)

**Closed by SupriyaKalghatgi** 2018-09-24 05:56 UTC

**Comment by digitwo** [comment] 2018-09-24 19:39
still have same issue like @jalpedersen described on the top

**Comment by vauruk** [comment] 2018-09-24 22:36
> still have same issue like @jalpedersen described on the top

in mode release in Android!

**Comment by SupriyaKalghatgi** [comment] 2018-09-25 03:34
You need to eject theme to find the fix related to cropping label
Else you can check the changes made in commit, and make those changes in your ejected theme (if already ejected)

**Comment by ZeroCool00** [comment] 2018-09-25 05:43
nothing chage.. i just update native-base.. and make new release .ipa. still same issue. onChangeText, secureTextEntry, floating label, nothing working.

**Comment by SupriyaKalghatgi** [comment] 2018-09-25 05:45
@ZeroCool00 It is better to read before rushing into the process
https://github.com/GeekyAnts/NativeBase/issues/2264#issuecomment-423882218

**Comment by MehdiJarraya** [comment] 2018-09-25 17:26
@SupriyaKalghatgi
Hi, I uninstall and install the latest version and I changed the file src/theme/components/Item.js but the issue still persists.
onChangeText, secureTextEntry and floating label works only in emulator not in release mode.

**Comment by MehdiJarraya** [comment] 2018-09-25 18:10
@SupriyaKalghatgi You can downgrade to native-base version "^2.6.0".
This issue exist in native-base version "^2.8.0".

**Comment by sourabhdadapure** [comment] 2018-09-26 04:47
A quick workaround for the label cut-off issue is to add {top:someValue} to the label style

**Comment by SupriyaKalghatgi** [comment] 2018-09-28 08:40
@MehdiJarraya Tested and committed https://github.com/GeekyAnts/NativeBase/issues/2264#issuecomment-423882218 and https://github.com/GeekyAnts/NativeBase/issues/2264#issuecomment-424196694

Probably cache issue on your side

**Comment by SupriyaKalghatgi** [comment] 2018-09-28 08:40
@sourabhdadapure https://github.com/GeekyAnts/NativeBase/issues/2264#issuecomment-425365484

**Comment by pateljaykesh** [comment] 2018-09-29 18:41
When will it be release in master? If it is taking longer time then can you guide me how do i integrate your commit into existing native base 2.8.0? Kindly help on this.

**Comment by Jordan4jc** [comment] 2018-10-02 13:47
This is still not working in 2.8.0, I have to use a different label layout for my input to work as intended

**Comment by anthonye2007** [comment] 2018-10-02 14:31
Did not work in 2.8.0. Downgraded to 2.6.1 and it works now.

**Comment by SupriyaKalghatgi** [comment] 2018-10-03 09:55
https://github.com/GeekyAnts/NativeBase/releases/tag/v2.8.1

**Comment by udarts** [comment] 2018-10-16 17:13
Guys, 2.8.1 still has the cut off floating label. I just downloaded the latest version and on Android (real device and simulator) the floating label is still cut off.

Can this please be fixed properly?

**Comment by SupriyaKalghatgi** [comment] 2018-10-24 05:50
@udarts I tried it now, no issues on device
May be you can create a test repo or on snack for me to look into

**Comment by anmolmalik97** [comment] 2018-10-27 20:53
floating labels are broken (not visible) in production mode but working fine in debugging mode in android (native-base 2.8.1)!

**Comment by SupriyaKalghatgi** [comment] 2018-10-30 07:52
@anmolmalik97 You can check all my comments above

**Comment by Laapi** [comment] 2018-11-05 14:15
@SupriyaKalghatgi  Hi, problem is real.
https://github.com/GeekyAnts/NativeBase/pull/2421 
I fix this bug.
The head of problem - Styled components in production named shorter then in development mode.

**Comment by sweetijha** [comment] 2018-12-29 06:57
maxLength is not wotking in react-native-floating-labels

**Comment by davekedar** [comment] 2019-01-18 05:52
Floating lable is not accepting padding or margin bottom 
![image](https://user-images.githubusercontent.com/11268363/51367991-38a24d00-1b13-11e9-8949-dc72d35ac040.png)
while in ios it is working perfectly 
![image](https://user-images.githubusercontent.com/11268363/51367995-448e0f00-1b13-11e9-90fe-51e3d9ef0ce0.png)
please help

**Comment by suvenduchhatoi** [comment] 2019-02-11 09:19
FloatingLabel seems to be working fine in the latest NB version(2.11.0),RN(0.58.3)...
![screen shot 1440-06-06 at 2 43 51 pm](https://user-images.githubusercontent.com/44160581/52554208-15b24280-2e0c-11e9-84c0-fb542c3a01e1.png)
![screen shot 1440-06-06 at 2 38 59 pm](https://user-images.githubusercontent.com/44160581/52554210-15b24280-2e0c-11e9-9dad-61721627e706.png)

**Comment by srinivasmangipudi** [comment] 2019-03-27 11:41
The issue is still reproduced in NB.2.11 and latest reactnative.

**Comment by cowai** [comment] 2019-06-27 19:13
Has anyone this problem in 0.59/Expo SDK 33 ?

**Comment by Imran-cse** [comment] 2020-06-29 15:31
The is still in the release mode

**Comment by satsuya0114** [comment] 2020-07-15 07:15
This is still in release mode. Please fix it !!!
