### ISSUE TITLE
NativeBase not working with NextJS 12 Native ES Modules Support

### ISSUE THREAD

**Issue by exneval** [GeekyAnts/NativeBase#4358] opened 2021-11-29 08:26 UTC
**Describe the bug**
As we already know, Native ESM already supported by Next JS 12, so the use of [next-transpile-modules](https://github.com/martpie/next-transpile-modules) can be removed as Next JS will transpile it automatically, but not with NativeBase, the NextJS 12 + RNW minimal setup won't work for NativeBase, unless use next-transpile-modules v9

**To Reproduce**
Install NativeBase v3 using NextJS 12 + React Native Web

**Expected behaviour**
Should benefit from it

**Comment by Ajamuar** [comment] 2021-12-01 07:06
Duplicate of #4295

**Closed by Ajamuar** 2021-12-01 07:06 UTC
Labels: high priority, v3
