### ISSUE TITLE
<Item> rendering error with children in Native Base 2.8.1

### ISSUE THREAD

**Issue by danghuyminh** [GeekyAnts/NativeBase#2364] opened 2018-10-14 18:35 UTC
Hi NativeBase dev team,

## Issue Description
Since I updated Native Base to version 2.8.1, I have encountered this error when using Native Base <Item error floatingLabel> with {children} inside:

> TypeError: TypeError: TypeError: undefined is not an object (evaluating 'this.props.children[i].props.name')

![2018-10-15_01h10_18](https://user-images.githubusercontent.com/44143309/46920357-5e511f00-d017-11e8-81e1-77f2bc7171af.png)

### node, npm, react-native, react and native-base version, expo version if used
`"dependencies": {
    "expo": "^30.0.1",
    "native-base": "^2.8.1",
    "react": "16.3.1",
    "redux-form": "^7.4.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
  }`

### Expected behaviour

![2018-10-15_01h25_17](https://user-images.githubusercontent.com/44143309/46920488-3793e800-d019-11e8-854c-0d801f06123f.png)

### Actual behaviour

Error as I described above.

### Steps to reproduce
Add an InputField:
![2018-10-15_01h22_24](https://user-images.githubusercontent.com/44143309/46920465-d5d37e00-d018-11e8-8dc7-58e1b2978991.png)

Then add a FieldWrapper:
![2018-10-15_01h22_17](https://user-images.githubusercontent.com/44143309/46920466-d704ab00-d018-11e8-8888-98b813b9cec9.png)

When `touched` = true and `error` = true, the error `TypeError: TypeError: TypeError: undefined is not an object (evaluating 'this.props.children[i].props.name')` appears.

### Is the bug present in both iOS and Android or in any one of them?
I am testing on Android.

### Any other additional info which would help us debug the issue quicker.
It works perfectly with the same code in 2.8.0 but it is not working in 2.8.1.

The error can be resolved if I remove either {children} or `<Icon>` in these lines:
` <Item error floatingLabel>
                        {children}
                        <Icon name='close-circle' />
                    </Item>`

**Comment by minhdang-idev** [comment] 2018-10-16 09:11
I think there must be a critical issue with 2.8.1. Can you please check changes committed recently?

**Comment by danghuyminh** [comment] 2018-10-16 16:30
Not only the issue that I reported, but also basic feature like floating label was broken on 2.8.1. I need to emphasis that it works normally on 2.8.0.

![2018-10-16_23h29_07](https://user-images.githubusercontent.com/44143309/47031990-63d77200-d19b-11e8-9f25-91532a7770cf.png)

**Comment by SupriyaKalghatgi** [comment] 2018-10-24 03:49
As of now, Accordion takes in text type parameter only. No custom components or custom values can be passed to accordion
We have considered #2163 as enhancement to accordion component
So please stay tuned for updates

**Comment by SupriyaKalghatgi** [comment] 2018-10-24 05:50
@danghuyminh This was fixed https://github.com/GeekyAnts/NativeBase/issues/2264

**Comment by SupriyaKalghatgi** [comment] 2018-10-24 05:54
About the code in issue description https://github.com/GeekyAnts/NativeBase/issues/2364#issue-369930273

That appears to be incomplete code for me to test. Include complete code wrt floatingLabel
Also do not put screenshots of code, paste code OR put it over snack

**Comment by minhdang-idev** [comment] 2018-10-24 09:22
Thank you @SupriyaKalghatgi. I will send another sample code to reproduce the issue so that you can easily test it. Please wait me for some hours.

**Comment by danghuyminh** [comment] 2018-10-24 18:08
@SupriyaKalghatgi sorry for using another account at home. 

This code works with 2.8.1 and 2.8.0 (case A):
```jsx
<Item error floatingLabel>
    <Label>Label here</Label>
    <Input value="value"/>
    <Icon name='close-circle' />
</Item>
```

This won't work with 2.8.1 (but works with 2.8.0 - case B):
```jsx
<Item error floatingLabel>
      {children}
      <Icon name='close-circle' />
</Item>
```

With {children} is:
```jsx
<Label>Label here</Label>
<Input value="value"/>
```

A should be equivalent to B. But I am not sure why the way B causes the error.

**Comment by SupriyaKalghatgi** [comment] 2018-10-31 06:30
#2350

**Comment by minhdang-idev** [comment] 2018-10-31 08:41
@SupriyaKalghatgi I am sorry but I think the two issues are different. You may just test my provided code in any available 2.8.1 project to reproduce it.

My snippet is:

```jsx
//Parent.js
import React from 'react';
import { Item, Icon } from 'native-base';

export default class Parent extends React.Component {
   return (
      <Item error floatingLabel>
         {children}
	 <Icon name='close-circle' />
      </Item>
    );
}
```

```jsx
// Main.js (render this component to see the error)
import React from 'react';
import Parent from './Parent';
import { Input, Label } from 'native-base';

export default class Main extends React.Component {

  return (
       <Parent>
          <Label>Label here</Label>
          <Input value="value"/>
       </Parent>
    );
}
```

Because this works perfectly in 2.8.0 so I may properly think that it is a bug.

**Comment by minhdang-idev** [comment] 2018-10-31 08:53
@SupriyaKalghatgi I've updated the code on snack so that you can easily see the issue. Thank you.

**Comment by minhdang-idev** [comment] 2018-12-24 07:04
@SupriyaKalghatgi Can you please re-open my issue? Because the issue marked as duplicated with this issue is actually different. 

Can you please check my snippet? It is really simple to reproduce. Thank you.

**Comment by suvenduchhatoi** [comment] 2018-12-27 07:11
@danghuyminh 
Try the following way:-

![screenshot 2018-12-27 at 12 32 53 pm](https://user-images.githubusercontent.com/44160581/50469715-b1f6c600-09d3-11e9-873d-866f6340d7d4.png)

**Comment by minhdang-idev** [comment] 2018-12-27 07:32
Thank you very much! I will try your solution and let you know soon.

**Closed** 2018-12-31 05:57 UTC
Labels: awaiting response
