### ISSUE TITLE
Tab containers are trying to acheve the same height after switching back and forth

### ISSUE THREAD

**Issue by stonecold123** [GeekyAnts/NativeBase#577] opened 2017-02-27 09:23 UTC
All of my tabs contain lists. I notice that the tab component in 2.0.10 would make all tab containers of equal height after you switch back and forth between the tabs. 

For example, the first tab, which is shorter, is trying to adjust the height after switching to a longer tab:

![Image of Yaktocat](https://media.giphy.com/media/xTiN0Lx5DdJVnQsWZi/source.gif)

````
render(){
   let list = []
   for(let i = 0;i < 20;i++){
        list.push(<ListItem><Text>{i}</Text></ListItem>)
   }
   return(
            <Container>
                <Content>
                    <Tabs>
                        <Tab heading={<TabHeading><Text>Tab1</Text></TabHeading>}>
                            <Grid>
                                <Row>
                                    <Text>Lorem Ipsum is simply</Text>
                                </Row>
                                <Row>
                                    <Text>Lorem Ipsum is simply</Text>
                                </Row>
                            </Grid>
                        </Tab>
                        <Tab heading={<TabHeading><Text>Tab2</Text></TabHeading>}>
                            <List initialListSize={3}>{list}</List>
                        </Tab>
                        <Tab heading={<TabHeading><Text>Tab3</Text></TabHeading>}>
                            <List initialListSize={3}>{list}</List>
                        </Tab>
                    </Tabs>
                </Content>
            </Container>
     )
}
````

**Comment by peter1a** [comment] 2017-03-01 08:03
This bug is already introduced in #508

**Comment by sankhadeeproy007** [comment] 2017-03-03 10:48
Duplicate of #508, let's track it there.

**Closed by sankhadeeproy007** 2017-03-03 10:48 UTC

**Comment by sankhadeeproy007** [comment] 2017-03-03 11:10
![test](https://cloud.githubusercontent.com/assets/10998047/23548984/11ca7586-0030-11e7-879b-c9cf1cd11c58.gif)
I tried but couldn't replicate the behaviour.

**Comment by Zilleabbas10** [comment] 2018-04-12 10:13
Still getting height issue in tabs. i have two tabs and my tabs adopt height of the tab which have heighest height. please help, i have implmented almost all solutions either by placing content of tab with in `<Content>` tag or by passing whole data to Flatlist. your help is appreciated in advance. Thankyou

**Comment by Zilleabbas10** [comment] 2018-04-12 10:13
Still getting height issue in tabs. i have two tabs and my tabs adopt height of the tab which have heighest height. please help, i have implmented almost all solutions either by placing content of tab with in `<Content>` tag or by passing whole data to Flatlist. your help is appreciated in advance. Thankyou
