### ISSUE TITLE
input onSubmitEditing focus() to next input using ref

### ISSUE THREAD

**Issue by hotaryuzaki** [GeekyAnts/NativeBase#5634] opened 2023-01-05 04:58 UTC
### Description

there is no focus() for Input in ref object, we need that to make user focus to the next input using onSubmitEditing

### CodeSandbox/Snack link

https://snack.expo.dev/5zbmn_l2M

### Steps to reproduce

1. create 2 input
2. input no 1 add onSubmitEditing focus() to input no 2 ref
3. input no 2 add ref

```
import React, { useRef } from 'react';
import { Input, Stack, NativeBaseProvider } from 'native-base';

export default function App() {
  let fPassword = useRef(null);

  return (
    <NativeBaseProvider>
      <Stack>
        <Input
          variant="filled"
          placeholder="Email"
          focusOutlineColor="transparent"
          keyboardType="email-address"
          returnKeyType="next"
          autoCapitalize="none"
          onSubmitEditing={() => {
            fPassword._root.focus();
          }}
        />
        <Input
          placeholder="Password"
          returnKeyType="next"
          autoCapitalize="none"
          ref={fPassword}
        />
      </Stack>
    </NativeBaseProvider>
  )
}
```

### NativeBase Version

3.4.25

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by chris-chapin** [comment] 2023-01-09 05:31
Just call fPassword.current?.focus(). You might not get the Intellisense but it will work.

**Comment by hotaryuzaki** [comment] 2023-01-09 07:45
> Just call fPassword.current?.focus(). You might not get the Intellisense but it will work.

yes it works.
but how to implement this in class component?
this is the [snack](https://snack.expo.dev/BiCQQtBZy)

**Comment by chris-chapin** [comment] 2023-01-10 17:40
Replace useRef with React.createRef.

https://reactjs.org/docs/refs-and-the-dom.html

Then close this issue since it's not a bug against NativeBase.

**Comment by hotaryuzaki** [comment] 2023-01-11 07:40
> Replace useRef with React.createRef.
> 
> https://reactjs.org/docs/refs-and-the-dom.html
> 
> Then close this issue since it's not a bug against NativeBase.

thanks a lot

**Closed** 2023-01-11 07:40 UTC
Labels: bug, v3, triage
