### ISSUE TITLE
Header component adds unwanted paddingTop

### ISSUE THREAD

**Issue by rpuls** [GeekyAnts/NativeBase#2929] opened 2019-09-17 14:30 UTC
I wonder why this issue: https://github.com/GeekyAnts/NativeBase/issues/2694 is closed, as there is no solution to it.

I'm facing the same issue. here is a screenshot with inspector:
![image](https://user-images.githubusercontent.com/14924038/65050517-cf0b6480-d967-11e9-8085-43b8e8a8e6b8.png)

I think I know what is going on. The component is checking what device it is on, and then trying to offset the header so that it doesn't cover the status bar. as you can see the paddingTop is 42 pixels, which happens to be the same as my custom status bar has.

I would like to be able to turn the padding off, but it doesn't seem like the component allow that. I have tried giving it style
`paddingtop: 0` which causes an error, and `paddingTop: 1` which does reduce the padding, but only down to 25. I need zero top padding.

Please **don't** suggest "have you tried without safe area", I'm interested in getting control of the padding, not changing settings.

Cheers.

**Comment by barisesen** [comment] 2019-09-23 11:03
React Navigation is trying to use header as standard. Since you added a new header, you create a new header under the standard header from navigation.

```
static navigationOptions = {
header: null,
};
```
@rpuls

**Comment by jannikbuschke** [comment] 2019-09-28 14:29
Im seeing this issue without using react navigation. For me this seems to be related to native-base.

**Comment by rpuls** [comment] 2019-10-01 09:40
> React Navigation is trying to use header as standard. Since you added a new header, you create a new header under the standard header from navigation.
> 
> ```
> static navigationOptions = {
> header: null,
> };
> ```
> 
> @rpuls

Where should I pass these navigationOptions ? file/component

**Comment by barisesen** [comment] 2019-10-01 10:38
> > React Navigation is trying to use header as standard. Since you added a new header, you create a new header under the standard header from navigation.
> > ```
> > static navigationOptions = {
> > header: null,
> > };
> > ```
> > 
> > 
> > @rpuls
> 
> Where should I pass these navigationOptions ? file/component
```

export default class CoolComponentName extends Component {

  static navigationOptions = {
    header: null,
  }

  ...
}
```

**Comment by rpuls** [comment] 2019-10-02 08:17
It does not seem to have any effect, or maybe I am still doing something wrong. I have placed it inside the app.js (the main file).

**Like this:**

```
import React, { Component } from 'react';
import { WebView } from 'react-native-webview';
import { Body, View, Root, Button, Icon, Header, Title } from 'native-base';
import LoadingScreen from './component/loadingScreen';
import DeviceStatusBar, { height, statusBarHeight } from './component/deviceStatusBar';
import styles from './styles/styles';

export default class App extends Component {

  static navigationOptions = {
    header: null,
  }

  constructor(props) {
    super(props)
    this.state = {
      ...
    }
  }

  render() {
    const mainScreen =
      <View style={styles.mainContainer}>
        {this.state.loading && <LoadingScreen />}
        <WebView
          ref={WEBVIEW_REF => { !this.state.webviewRef && this.setState({ webviewRef: WEBVIEW_REF }) }}
          key={this.state.uri}
          source={{ uri: this.state.shareUrl || this.state.uri }}

        />
        <View style={{ position: 'absolute', zIndex: 4, width: '100%', height: '100%' }}>
          <Header>
            <Button transparent onPress={() => this.toggleSecondaryWebview({ show: false, position: this.state.secondaryWVTop })}>
              <Icon name='arrow-back' />
            </Button>
            <Body><Title>{this.state.externalContentUrl}</Title></Body>
          </Header>
          <WebView key="secondaryWebview" source={{ uri: this.state.externalContentUrl }} />
        </View>
      </View>

    return (
      <Root>
        <Body style={{ width: '100%', height: '100%' }}>
          <DeviceStatusBar backgroundColor={styles.Var['primaryColor']} barStyle="light-content" />
          {mainScreen}
        </Body>
      </Root>
    );
  }
}
```
@barisesen

**Comment by gertvdkolk** [comment] 2019-11-07 08:05
+1 - I'm facing the same issue!

**Comment by gertvdkolk** [comment] 2019-11-07 10:10
I tested on a couple of device simulators and the problem occurred only on the following
[X] - iPhone 11 max (6.5")
[  ] - iPad 3rd generation (12.9") 
[  ] - iPhone 8 plus (5.5")

Could this be device-related?

**Comment by martinatti** [comment] 2019-11-30 03:06
Up

**Comment by LightningXCE** [comment] 2019-12-12 02:29
Seeing this behavior on the Galaxy s10/s10e as well.

![image](https://user-images.githubusercontent.com/720172/70677491-4dbd2880-1c5d-11ea-9c41-716432b455c7.png)

I believe it's thinking there's a notch, causing the padding to be added

**Comment by StainlessSteelRat** [comment] 2020-01-15 17:00
I'm having the same problems with the header and the tabNavigation bar at the bottom.

I've just set the paddingTop on the header to -30 and its back to looking normal, but of course it messes it up for all the other devices. :-(

Stuart.

**Comment by vijeeshin** [comment] 2020-07-24 15:29
In RN 5, try this in options 
`safeAreaInsets: {
                          top: 0,
                        },`

**Comment by hanykumar** [comment] 2020-09-18 12:56
Hi, It has been fixed. Update Native-base v2.13.14 . Please let us know if the issue still persists by providing minimal code reproduction for the same. Closing for now.

**Closed by hanykumar** 2020-09-18 12:56 UTC
